.TH "anonymous_namespace{SbViewVolume.cpp}" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{SbViewVolume.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclip_face\fP (\fBSbClip\fP &clipper, const \fBSbVec3f\fP &v0, const \fBSbVec3f\fP &v1, const \fBSbVec3f\fP &v2, const \fBSbVec3f\fP &v3, const \fBSbPlane\fP *planes, \fBSbBox3f\fP &isect)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
