.TH "anonymous_namespace{SoPrimitiveVertexCache.cpp}" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{SoPrimitiveVertexCache.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "SbBool \fBSoGLLazyElement_enabled\fP (const \fBSoState\fP *state)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
