.TH "bundles" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bundles \- The bundle classes are internal to Coin\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoBundle\fP"
.br
.RI "The \fBSoBundle\fP class is the superclass for all bundle classes\&. "
.ti -1c
.RI "class \fBSoMaterialBundle\fP"
.br
.RI "The \fBSoMaterialBundle\fP class simplifies material handling\&.
.PP
Every shape node should create (on the stack) an instance of this class and call \fBsendFirst()\fP before sending anything to GL\&. During rendering, \fBsend()\fP should be used to send material values to GL\&. "
.ti -1c
.RI "class \fBSoNormalBundle\fP"
.br
.RI "The \fBSoNormalBundle\fP class simplifies normal handling\&.
.PP
This class is currently not used in Coin but is provided for API compatibility\&. "
.ti -1c
.RI "class \fBSoVertexAttributeBundle\fP"
.br
.RI "The \fBSoVertexAttributeBundle\fP class simplifies vertex attribute handling\&. "
.ti -1c
.RI "class \fBSoTextureCoordinateBundle\fP"
.br
.RI "The \fBSoTextureCoordinateBundle\fP class simplifies texture coordinate handling\&.
.PP
It is unlikely that application programmers should need to know how to use this class, as it is mostly intended for internal use\&. "
.in -1c
.SH "Detailed Description"
.PP 
The bundle classes are internal to Coin\&. 

The Bundle Classes
The bundle classes are mostly internal to Coin\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
