.TH "cc_debugerror" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cc_debugerror
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcc_error\fP \fBsuper\fP"
.br
.ti -1c
.RI "CC_DEBUGERROR_SEVERITY \fBseverity\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
