.TH "coin200" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin200New Features in Coin v2\&.0\&.0 
 \- This is a brief summary of the new features in Coin v2\&.0\&.0:
.IP "\(bu" 2
Big-Image Support
.IP "\(bu" 2
3D Textures Support
.IP "\(bu" 2
3D Sound Support
.IP "\(bu" 2
VRML97 Support
.IP "\(bu" 2
Mac OS X Support
.IP "\(bu" 2
Multi-Pipe Rendering Support 
.PP

