.TH "coin220" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin220New Features in Coin v2\&.2\&.0 
 \- This is a brief summary of the new features in Coin v2\&.2\&.0:
.IP "\(bu" 2
Multi-Texturing (see \fBSoTextureUnit\fP)
.IP "\(bu" 2
Bump-Mapping
.IP "  \(bu" 4
\fBSoBumpMap\fP
.IP "  \(bu" 4
\fBSoBumpMapCoordinate\fP
.IP "  \(bu" 4
\fBSoBumpMapTransform\fP
.PP

.IP "\(bu" 2
Better Font Support
.IP "\(bu" 2
TrueType font support for all 3D text primitive types\&.
.IP "\(bu" 2
Render To Texture Support (see \fBSoSceneTexture2\fP)
.IP "\(bu" 2
REPLACE texture model support for \fBSoTexture2\fP
.IP "\(bu" 2
pbuffer support for \fBSoOffscreenRenderer\fP
.IP "\(bu" 2
New transparency rendering type, SORTED_LAYERS_BLEND 
.PP

