.TH "coin313" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin313New Features in Coin v3\&.1\&.3 
 \- This is a bugfix release\&.
.PP
Due to an underlying buildsystem upgrade, the default location of the generated HTML docs changed from $datarootdir/share/Coin/html to $datarootdir/share/doc/coin/html\&. 
