.TH "coin240" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin240New Features in Coin v2\&.4\&.0 
 \- The primary reason for the 2\&.4\&.0 release was the option of finally building Coin from source on MS Windows without having to go through the Cygwin process\&.
.PP
There had also been various optimization work on rendering traversal code, file i/o and other things\&.
.PP
For v2\&.4\&.1, \fBSoExtSelection\fP LASSO and RECTANGLE select could be aborted by the end-user by hiting the 'END' key\&. No API-changes was needed for this of course\&.
.PP
For v2\&.4\&.2, we hacked in support for compressed textures through an API/ABI-invisible field in \fBSoTexture2\fP, called 'enableCompressedTexture'\&. This field will remain 'invisible' until Coin v3\&.0\&.0 is released, and can only be accessed from \&.iv-file input or through the \fBSoFieldContainer\fP API\&.
.PP
For v2\&.4\&.6, \fBSbViewVolume::getAlignRotation()\fP was implemented, and \fBSoToVRML2Action\fP got support for \fBSoUnits\fP in relation to \fBSoVRMLTransform\fP nodes\&. 
