.TH "Coin_environment_variables" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coin_environment_variablesEnvironment variables 
 \- Debug related:
.PP
COIN_DEBUG_GLU_INFO COIN_DEBUG_FONTSUPPORT COIN_DEBUG_3DS COIN_DEBUG_AUDIO COIN_DEBUG_BREAK COIN_DEBUG_CACHING COIN_DEBUG_DL COIN_DEBUG_IMPORT COIN_DEBUG_LISTMODULES COIN_DEBUG_SOINPUT_FINDFILE COIN_DEBUG_SOOFFSCREENRENDERER COIN_DEBUG_WRITEREFS COIN_RANDOMIZE_RENDER_CACHING
.PP
Font/Text rendering related:
.PP
COIN_FREETYPE2_LIBNAME COIN_FORCE_FREETYPE_OFF COIN_FORCE_WIN32FONTS_OFF COIN_FONT_PATH
.PP
COIN_DISABLE_UTF8
.PP
COIN_GLU_LIBNAME COIN_AGLGLUE_NO_PBUFFERS COIN_DEBUG_DL COIN_SIMAGE_LIBNAME COIN_GLXGLUE_NO_GLX13_PBUFFERS COIN_GLXGLUE_NO_PBUFFERS COIN_ZLIB_LIBNAME COIN_BZIP2_LIBNAME COIN_WGLGLUE_NO_PBUFFERS COIN_DONT_MANGLE_OUTPUT_NAMES COIN_EXTSELECTION_SAVE_OFFSCREENBUFFER COIN_FORCE_TILED_OFFSCREENRENDERING COIN_GLERROR_DEBUGGING COIN_IDA_DEBUG COIN_OFFSCREENRENDERER_MAX_TILESIZE COIN_OFFSCREENRENDERER_TILEHEIGHT COIN_OFFSCREENRENDERER_TILEWIDTH COIN_OLDSTYLE_FORMATTING COIN_SEPARATE_DIFFUSE_TRANSPARENCY_OVERRIDE COIN_SOINPUT_SEARCH_GLOBAL_DICT COIN_SOOFFSCREENRENDERER_TILEPREFIX COIN_SORTED_LAYERS_USE_NVIDIA_RC
.PP
Sound related:
.PP
COIN_SOUND_BUFFER_LENGTH COIN_SOUND_DISABLE COIN_SOUND_DRIVER_NAME COIN_SOUND_ENABLE COIN_SOUND_INTRO_PAUSE COIN_SOUND_NUM_BUFFERS COIN_SOUND_THREAD_SLEEP_TIME COIN_OPENAL_LIBNAME
.PP
Texture control related:
.PP
COIN_TEX2_LINEAR_LIMIT COIN_TEX2_LINEAR_MIPMAP_LIMIT COIN_TEX2_MIPMAP_LIMIT COIN_TEX2_SCALEUP_LIMIT COIN_TEX2_USE_GLTEXSUBIMAGE COIN_MAXIMUM_TEXTURE2_SIZE COIN_MAXIMUM_TEXTURE3_SIZE
.PP
Rendering (OpenGL) related:
.PP
COIN_USE_GL_VERTEX_ARRAYS COIN_NORMALIZATION_CUBEMAP_SIZE OIV_NUM_SORTED_LAYERS_PASSES COIN_MAX_VBO_MEMORY COIN_NUM_SORTED_LAYERS_PASSES COIN_QUADMESH_PRECISE_LIGHTING COIN_ENABLE_CONFORMANT_GL_CLAMP COIN_GLBBOX
.PP
IV_SEPARATOR_MAX_CACHES COIN_AUTOCACHE_LOCAL_MAX COIN_AUTOCACHE_LOCAL_MIN COIN_AUTOCACHE_REMOTE_MAX COIN_AUTOCACHE_REMOTE_MIN COIN_AUTO_CACHING COIN_ENABLE_VBO
.PP
COIN_SOOFFSCREENRENDERER_ALLOW_RESOURCEHOG
.PP
SO_DRAGGER_DIR SO_SHADER_DIR COINDIR 
