.TH "CoinResources::anonymous_namespace{CoinResources.cpp}" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinResources::anonymous_namespace{CoinResources.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< const char *, ResourceHandle * > \fBResourceMap\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ResourceHandle * \fBgetResourceHandle\fP (const char *resloc)"
.br
.ti -1c
.RI "ResourceHandle * \fBcreateResourceHandle\fP (const char *resloc)"
.br
.ti -1c
.RI "void \fBcleanup\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ResourceMap * \fBresourcemap\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
