.TH "coin210" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin210New Features in Coin v2\&.1\&.0 
 \- This is a brief summary of the new features in Coin v2\&.1\&.0:
.IP "\(bu" 2
HardCopy Support: Vector output to PostScript\&.
.IP "\(bu" 2
FreeType and Win32 TrueType Font Support
.IP "\(bu" 2
Intersection Detection with \fBSoIntersectionDetectionAction\fP
.IP "\(bu" 2
\fBSoLineHighlightRenderAction\fP / \fBSoBoxHighlightRenderAction\fP and Multiple \fBSoSelection\fP Nodes
.IP "\(bu" 2
Compressed File I/O Support (see \fBSoOutput::setCompression()\fP, \fBSoOutput::getAvailableCompressionMethods()\fP)
.IP "\(bu" 2
Additional Convenience Functions \fBSoInput::setStringArray()\fP and \fBSoAction::apply(SoAction *)\fP
.IP "\(bu" 2
NO_COPY \fBSoSFImage\fP CopyPolicy, \fBSoSFImage::setValue\fP with CopyPolicy::NO_COPY implemented\&. 
.PP

