.TH "details" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details \- Detail classes are objects that deliver additional information wherever the \fBSoPrimitiveVertex\fP class is used\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoDetail\fP"
.br
.RI "The \fBSoDetail\fP class is the superclass for all classes storing detailed information about particular shapes\&.
.PP
Detail information about shapes is used in relation to picking actions in Coin\&. They typically contain the relevant information about what particular part of the shape a pick ray intersected with\&. "
.ti -1c
.RI "class \fBSoConeDetail\fP"
.br
.RI "The \fBSoConeDetail\fP class contains information about the parts of a \fBSoCone\fP shape\&.
.PP
Instances of this class are used for storing information about hit points on cone geometry after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoCubeDetail\fP"
.br
.RI "The \fBSoCubeDetail\fP class contains information about the parts of a \fBSoCube\fP shape\&.
.PP
Instances of this class are used for storing information about hit points on cone geometry after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoCylinderDetail\fP"
.br
.RI "The \fBSoCylinderDetail\fP class contains information about the parts of a \fBSoCylinder\fP shape\&.
.PP
Instances of this class are used for storing information about hit points on cylinder geometry after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoFaceDetail\fP"
.br
.RI "The \fBSoFaceDetail\fP class is for storing detailed polygon information\&.
.PP
Instances of this class are used among other things for storing information about polygons after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoLineDetail\fP"
.br
.RI "The \fBSoLineDetail\fP class is for storing detailed 3D line information\&.
.PP
Instances of this class are used among other things for storing information about lines after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoNodeKitDetail\fP"
.br
.RI "The \fBSoNodeKitDetail\fP class is yet to be documented\&.
.PP
When a pick action is executed and geometry within a nodekit is hit, the nodekit generates an \fBSoNodeKitDetail\fP object which contains information about the specific part inside the nodekit hit by the pick ray\&. "
.ti -1c
.RI "class \fBSoPointDetail\fP"
.br
.RI "The \fBSoPointDetail\fP class is for storing detailed information for a single 3D point\&.
.PP
Instances of this class are used among other things for storing information about the vertices of lines and polygons after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoTextDetail\fP"
.br
.RI "The \fBSoTextDetail\fP stores information about a character in a string\&.
.PP
Instances of this class are used for storing information about hit points on textual 2D or 3D geometry after pick operations, and for storing information returned to tessellation callbacks\&. "
.ti -1c
.RI "class \fBSoDetailList\fP"
.br
.RI "The \fBSoDetailList\fP class is a container for pointers to \fBSoDetail\fP objects\&.
.PP
This list class will delete the details when destructed/truncated, or when a detail in the list is replaced by another detail\&. The caller is responsible for allocating the details passed to the list, but should not deallocate them since this will be handled by the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Detail classes are objects that deliver additional information wherever the \fBSoPrimitiveVertex\fP class is used\&. 

This goes for ray picking results, and it also goes for primitive generation by \fBSoShape\fP classes for the \fBSoCallbackAction\fP class and fallback shape rendering through primitive generation (a useful debugging trick when debugging for instance raypicking)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
