.TH "foreignfilesupport" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
foreignfilesupportForeign File Format Support 
 \- This is a page describing foreign file format support in Coin\&.
.PP
Formats supported so far:
.IP "\(bu" 2
STL / Stereolithography files (\&.stl)
.PP
.PP
The \fBSoSTLFileKit\fP server as a first example on how foreign file format support can be implemented through the \fBSoForeignFileKit\fP interface nodekit\&. For STL, the file format is so trivial that it maps directly into a few Open Inventor nodes\&. For other file formats, the direct mapping might not be possible or desirable (maybe important information will get lost in such a conversion), and the implementor might choose to implement a set of internal custom nodes for doing the rendering (and applying the other actions), and choose to first do pure Open Inventor organization when the node kit is asked to write its contents as a scene graph\&.
.PP
FIXME: Document autoloading when implemented and tested
.PP
\fBSee also:\fP
.RS 4
\fBSoForeignFileKit\fP, \fBSoSTLFileKit\fP 
.RE
.PP

