.TH "JSErrorReport" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSErrorReport
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "uintN \fBlineno\fP"
.br
.ti -1c
.RI "const char * \fBlinebuf\fP"
.br
.ti -1c
.RI "const char * \fBtokenptr\fP"
.br
.ti -1c
.RI "const jschar * \fBuclinebuf\fP"
.br
.ti -1c
.RI "const jschar * \fBuctokenptr\fP"
.br
.ti -1c
.RI "uintN \fBflags\fP"
.br
.ti -1c
.RI "uintN \fBerrorNumber\fP"
.br
.ti -1c
.RI "const jschar * \fBucmessage\fP"
.br
.ti -1c
.RI "const jschar ** \fBmessageArgs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
