.TH "JSFunctionSpec" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSFunctionSpec
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "JSNative \fBcall\fP"
.br
.ti -1c
.RI "uint8_t \fBnargs\fP"
.br
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.ti -1c
.RI "uint16_t \fBextra\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
