.TH "navigation" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
navigation \- These contains the actual implementation of the \fBScXML\fP based navigation system\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoScXMLNavigation\fP"
.br
.RI "Static class for some static init/cleanup/synchronization functions\&. "
.ti -1c
.RI "class \fBSoScXMLNavigationTarget\fP"
.br
.RI "base class for navigation system SCXML event target services "
.ti -1c
.RI "class \fBSoScXMLPanTarget\fP"
.br
.RI "Navigation system event target for panning operations\&. "
.ti -1c
.RI "class \fBSoScXMLRotateTarget\fP"
.br
.RI "Navigation system event target for rotating operations\&. "
.ti -1c
.RI "class \fBSoScXMLSeekTarget\fP"
.br
.RI "Navigation system event target for seekmotion operations\&. "
.ti -1c
.RI "class \fBSoScXMLSpinTarget\fP"
.br
.RI "Navigation system event target for spinning operations\&. "
.ti -1c
.RI "class \fBSoScXMLZoomTarget\fP"
.br
.RI "SCXML event target service for zoom-behaviour\&. "
.ti -1c
.RI "class \fBSoScXMLDollyTarget\fP"
.br
.RI "SCXML event target service for zoom-behaviour\&. "
.ti -1c
.RI "class \fBSoScXMLMiscTarget\fP"
.br
.RI "Some misc navigation utility functions\&. "
.ti -1c
.RI "class \fBSoScXMLFlightControlTarget\fP"
.br
.RI "SCXML navigation service for typical flight motions\&. "
.ti -1c
.RI "class \fBSoScXMLMotionTarget\fP"
.br
.RI "to be used in parallel with other non-moving targets when parallel states are implemented\&. "
.in -1c
.SH "Detailed Description"
.PP 
These contains the actual implementation of the \fBScXML\fP based navigation system\&. 


.PP
\fBSee also:\fP
.RS 4
\fBState Chart XML Classes\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
