.TH "rwmutex.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rwmutex.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/C/basic\&.h>\fP
.br
\fC#include <Inventor/C/threads/common\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcc_rwmutex\fP * \fBcc_rwmutex_construct\fP (void)"
.br
.ti -1c
.RI "\fBcc_rwmutex\fP * \fBcc_rwmutex_construct_etc\fP (\fBcc_precedence\fP policy)"
.br
.ti -1c
.RI "void \fBcc_rwmutex_destruct\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_write_lock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_write_try_lock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_write_unlock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_read_lock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_read_try_lock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.ti -1c
.RI "\fBint\fP \fBcc_rwmutex_read_unlock\fP (\fBcc_rwmutex\fP *rwmutex)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcc_rwmutex\fP* cc_rwmutex_construct (void)"
Construct a read-write mutex, with read precedence\&. 
.SS "\fBcc_rwmutex\fP* cc_rwmutex_construct_etc (enum \fBcc_precedence\fP policy)"
Construct a read-write mutex, with read precedence or write precedence\&. 
.SS "void cc_rwmutex_destruct (\fBcc_rwmutex\fP * rwmutex)"
Destruct a read-write mutex\&. 
.SS "\fBint\fP cc_rwmutex_write_lock (\fBcc_rwmutex\fP * rwmutex)"
Locks the specified \fIrwmutex\fP for writing\&. 
.SS "\fBint\fP cc_rwmutex_write_try_lock (\fBcc_rwmutex\fP * rwmutex)"
Check whether the given \fIrwmutex*\fP is available for write locking\&. 
.SS "\fBint\fP cc_rwmutex_write_unlock (\fBcc_rwmutex\fP * rwmutex)"
Unlock the write lock on the given \fIrwmutex\fP\&. 
.SS "\fBint\fP cc_rwmutex_read_lock (\fBcc_rwmutex\fP * rwmutex)"
Locks the specified \fIrwmutex\fP for reading\&. 
.SS "\fBint\fP cc_rwmutex_read_try_lock (\fBcc_rwmutex\fP * rwmutex)"
Check whether the given \fIrwmutex*\fP is available for read locking\&. 
.SS "\fBint\fP cc_rwmutex_read_unlock (\fBcc_rwmutex\fP * rwmutex)"
Unlock the read lock on the given \fIrwmutex\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
