.TH "SbStorage" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbStorage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSbStorage\fP (unsigned \fBint\fP size)"
.br
.ti -1c
.RI "\fBSbStorage\fP (unsigned \fBint\fP size, cc_storage_f *constr, cc_storage_f *destr)"
.br
.ti -1c
.RI "void * \fBget\fP (void)"
.br
.ti -1c
.RI "void \fBapplyToAll\fP (SbStorageApplyFunc *func, void *closure)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
