.TH "SbTypeInfo< SbRotation >" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbTypeInfo< SbRotation >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBisPrimitive\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBDimensions\fP = 4 }"
.br
.ti -1c
.RI "typedef \fBSbRotation\fP \fBType\fP"
.br
.ti -1c
.RI "typedef const \fBType\fP & \fBParamType\fP"
.br
.ti -1c
.RI "typedef float \fBPrimitiveType\fP"
.br
.ti -1c
.RI "typedef \fBSoSFRotation\fP \fBSFieldType\fP"
.br
.ti -1c
.RI "typedef \fBSoMFRotation\fP \fBMFieldType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBgetTypeName\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
