.TH "SbTypeInfo< SbBox2i32 >" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbTypeInfo< SbBox2i32 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBDimensions\fP = 2 }"
.br
.ti -1c
.RI "typedef \fBSbBox2i32\fP \fBType\fP"
.br
.ti -1c
.RI "typedef const \fBType\fP & \fBParamType\fP"
.br
.ti -1c
.RI "typedef int32_t \fBPrimitiveType\fP"
.br
.ti -1c
.RI "typedef \fBSbVec2i32\fP \fBVecType\fP"
.br
.ti -1c
.RI "typedef \fBSoSFBox2i32\fP \fBSFieldType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
