.TH "SbTypeInfo< SbVec2us >" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbTypeInfo< SbVec2us >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBDimensions\fP = 2 }"
.br
.ti -1c
.RI "typedef \fBSbVec2us\fP \fBType\fP"
.br
.ti -1c
.RI "typedef \fBType\fP \fBParamType\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBPrimitiveType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
