.TH "SbTypeInfo< unsigned short >" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbTypeInfo< unsigned short >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned short \fBType\fP"
.br
.ti -1c
.RI "typedef Type \fBParamType\fP"
.br
.ti -1c
.RI "typedef \fBSbVec2us\fP \fBVec2Type\fP"
.br
.ti -1c
.RI "typedef \fBSbVec3us\fP \fBVec3Type\fP"
.br
.ti -1c
.RI "typedef \fBSbVec4us\fP \fBVec4Type\fP"
.br
.ti -1c
.RI "typedef \fBSoSFUShort\fP \fBSFieldType\fP"
.br
.ti -1c
.RI "typedef \fBSoMFUShort\fP \fBMFieldType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
