.TH "SbTypeInfo< double >" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbTypeInfo< double >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBisPrimitive\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBDimensions\fP = 1 }"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef Type \fBParamType\fP"
.br
.ti -1c
.RI "typedef \fBSbVec2d\fP \fBVec2Type\fP"
.br
.ti -1c
.RI "typedef \fBSbVec3d\fP \fBVec3Type\fP"
.br
.ti -1c
.RI "typedef \fBSbVec4d\fP \fBVec4Type\fP"
.br
.ti -1c
.RI "typedef \fBSbBox2d\fP \fBBox2Type\fP"
.br
.ti -1c
.RI "typedef \fBSbBox3d\fP \fBBox3Type\fP"
.br
.ti -1c
.RI "typedef \fBSoSFDouble\fP \fBSFieldType\fP"
.br
.ti -1c
.RI "typedef \fBSoMFDouble\fP \fBMFieldType\fP"
.br
.ti -1c
.RI "typedef \fBSbDPPlane\fP \fBPlaneType\fP"
.br
.ti -1c
.RI "typedef \fBSbDPLine\fP \fBLineType\fP"
.br
.ti -1c
.RI "typedef \fBSbDPMatrix\fP \fBMatrixType\fP"
.br
.ti -1c
.RI "typedef \fBSbDPRotation\fP \fBRotationType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
