.TH "SbVec3us" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbVec3us
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/SbVec3us\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSbVec3us\fP (const unsigned short v[3])"
.br
.ti -1c
.RI "\fBSbVec3us\fP (unsigned short x, unsigned short y, unsigned short z)"
.br
.ti -1c
.RI "\fBSbVec3us\fP (const \fBSbVec3s\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP (const \fBSbVec3ub\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP (const \fBSbVec3ui32\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBsetValue\fP (const unsigned short v[3])"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBsetValue\fP (unsigned short x, unsigned short y, unsigned short z)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBsetValue\fP (const \fBSbVec3s\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBsetValue\fP (const \fBSbVec3ub\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBsetValue\fP (const \fBSbVec3ui32\fP &v)"
.br
.ti -1c
.RI "const unsigned short * \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "void \fBgetValue\fP (unsigned short &x, unsigned short &y, unsigned short &z) const"
.br
.ti -1c
.RI "unsigned short & \fBoperator[]\fP (\fBint\fP i)"
.br
.ti -1c
.RI "const unsigned short & \fBoperator[]\fP (\fBint\fP i) const"
.br
.ti -1c
.RI "int32_t \fBdot\fP (const \fBSbVec3us\fP &v) const"
.br
.ti -1c
.RI "void \fBnegate\fP (void)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator*=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator*=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator/=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator/=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator+=\fP (const \fBSbVec3us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP & \fBoperator\-=\fP (const \fBSbVec3us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec3us\fP \fBoperator\-\fP (void) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBvec\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
