.TH "SbVec2ub" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbVec2ub
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/SbVec2ub\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSbVec2ub\fP (const uint8_t v[2])"
.br
.ti -1c
.RI "\fBSbVec2ub\fP (uint8_t x, uint8_t y)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP (const \fBSbVec2b\fP &v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP (const \fBSbVec2us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP (const \fBSbVec2ui32\fP &v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBsetValue\fP (const uint8_t v[2])"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBsetValue\fP (uint8_t x, uint8_t y)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBsetValue\fP (const \fBSbVec2b\fP &v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBsetValue\fP (const \fBSbVec2us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBsetValue\fP (const \fBSbVec2ui32\fP &v)"
.br
.ti -1c
.RI "const uint8_t * \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "void \fBgetValue\fP (uint8_t &x, uint8_t &y) const"
.br
.ti -1c
.RI "uint8_t & \fBoperator[]\fP (\fBint\fP i)"
.br
.ti -1c
.RI "const uint8_t & \fBoperator[]\fP (\fBint\fP i) const"
.br
.ti -1c
.RI "int32_t \fBdot\fP (\fBSbVec2ub\fP v) const"
.br
.ti -1c
.RI "void \fBnegate\fP (void)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator*=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator*=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator/=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator/=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator+=\fP (\fBSbVec2ub\fP v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP & \fBoperator\-=\fP (\fBSbVec2ub\fP v)"
.br
.ti -1c
.RI "\fBSbVec2ub\fP \fBoperator\-\fP (void) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBvec\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
