.TH "SbVec4us" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbVec4us
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSbVec4us\fP (const unsigned short v[4])"
.br
.ti -1c
.RI "\fBSbVec4us\fP (unsigned short x, unsigned short y, unsigned short z, unsigned short w)"
.br
.ti -1c
.RI "\fBSbVec4us\fP (const \fBSbVec4s\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP (const \fBSbVec4ub\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP (const \fBSbVec4ui32\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBsetValue\fP (const unsigned short v[4])"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBsetValue\fP (unsigned short x, unsigned short y, unsigned short z, unsigned short w)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBsetValue\fP (const \fBSbVec4s\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBsetValue\fP (const \fBSbVec4ub\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBsetValue\fP (const \fBSbVec4ui32\fP &v)"
.br
.ti -1c
.RI "const unsigned short * \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "void \fBgetValue\fP (unsigned short &x, unsigned short &y, unsigned short &z, unsigned short &w) const"
.br
.ti -1c
.RI "unsigned short & \fBoperator[]\fP (\fBint\fP i)"
.br
.ti -1c
.RI "const unsigned short & \fBoperator[]\fP (\fBint\fP i) const"
.br
.ti -1c
.RI "int32_t \fBdot\fP (const \fBSbVec4us\fP &v) const"
.br
.ti -1c
.RI "void \fBnegate\fP (void)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator*=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator*=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator/=\fP (\fBint\fP d)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator/=\fP (double d)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator+=\fP (const \fBSbVec4us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP & \fBoperator\-=\fP (const \fBSbVec4us\fP &v)"
.br
.ti -1c
.RI "\fBSbVec4us\fP \fBoperator\-\fP (void) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBvec\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
