.TH "SbVec3fList" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbVec3fList \- The \fBSbVec3fList\fP class is a container for arrays of \fBSbVec3f\fP pointers\&.
.PP
Note that upon using the equality and inequality operators, the \fBSbVec3f\fP objects themselves are not compared, only the pointer values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/lists/SbVec3fList\&.h>\fP
.PP
Inherits \fBSbPList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSbVec3fList\fP (void)"
.br
.ti -1c
.RI "\fB~SbVec3fList\fP ()"
.br
.ti -1c
.RI "void \fBappend\fP (const \fBSbVec3f\fP *item)"
.br
.ti -1c
.RI "void \fBinsert\fP (const \fBSbVec3f\fP *item, const \fBint\fP insertbefore)"
.br
.ti -1c
.RI "\fBSbVec3f\fP * \fBoperator[]\fP (const \fBint\fP idx) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSbVec3fList\fP class is a container for arrays of \fBSbVec3f\fP pointers\&.
.PP
Note that upon using the equality and inequality operators, the \fBSbVec3f\fP objects themselves are not compared, only the pointer values\&. 

Note also that all calls to \fBappend()\fP and \fBinsert()\fP will cause the list to allocate a new \fBSbVec3f\fP object\&. These objects are freed when the list is destructed\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbList\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SbVec3fList::SbVec3fList (void)\fC [inline]\fP"
Default constructor\&. 
.SS "SbVec3fList::~SbVec3fList ()"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SbVec3fList::append (const \fBSbVec3f\fP * item)\fC [inline]\fP"
Overridden from parent to allocate a new \fBSbVec3f\fP instance when called\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbPList::append()\fP 
.RE
.PP

.SS "void SbVec3fList::insert (const \fBSbVec3f\fP * item, const \fBint\fP insertbefore)\fC [inline]\fP"
Overridden from parent to allocate a new \fBSbVec3f\fP instance when called\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbPList::insert()\fP 
.RE
.PP

.SS "\fBSbVec3f\fP * SbVec3fList::operator[] (const \fBint\fP idx) const\fC [inline]\fP"
Overridden from parent to return an \fBSbVec3f\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
