.TH "ScXMLDataElt" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLDataElt \- the \fC<data>\fP SCXML element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/scxml/ScXMLDataElt\&.h>\fP
.PP
Inherits \fBScXMLElt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "virtual void \fBsetIDAttribute\fP (const char *ID)"
.br
.ti -1c
.RI "virtual const char * \fBgetIDAttribute\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetSrcAttribute\fP (const char *src)"
.br
.ti -1c
.RI "virtual const char * \fBgetSrcAttribute\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetExprAttribute\fP (const char *expr)"
.br
.ti -1c
.RI "virtual const char * \fBgetExprAttribute\fP (void) const"
.br
.ti -1c
.RI "virtual SbBool \fBhandleXMLAttributes\fP (void)"
.br
.ti -1c
.RI "virtual void \fBcopyContents\fP (const \fBScXMLElt\fP *rhs)"
.br
.ti -1c
.RI "virtual const \fBScXMLElt\fP * \fBsearch\fP (const char *attrname, const char *attrvalue) const"
.br
.ti -1c
.RI "virtual void \fBsetValueObj\fP (\fBScXMLDataObj\fP *value)"
.br
.ti -1c
.RI "virtual \fBScXMLDataObj\fP * \fBgetValueObj\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBScXMLEltReader\fP * \fBgetElementReader\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char * \fBID\fP"
.br
.ti -1c
.RI "char * \fBsrc\fP"
.br
.ti -1c
.RI "char * \fBexpr\fP"
.br
.ti -1c
.RI "\fBScXMLDataObj\fP * \fBvalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
the \fC<data>\fP SCXML element\&. 

The \fC<data>\fP SCXML element is for storing variables\&. They need to be contained within a \fC<datamodel>\fP element\&. \fC<data>\fP elements are only functional in state machines with a profile that has an implementation of the Data Module\&. The \fC'minimum'\fP profile does not, but the \fC'x-coin'\fP profile does\&.
.PP
The following attributes are accepted: 
.PD 0

.IP "\(bu" 2
\fCID\fP 
.IP "\(bu" 2
\fCsrc\fP - not supported 
.IP "\(bu" 2
\fCexpr\fP 
.PP
The \fCID\fP attribute is required and specified the variable name\&. The variable name must be unique for the whole SCXML state machine specification\&.
.PP
The \fCsrc\fP attribute is not supported\&.
.PP
The \fCexpr\fP attribute specifies the value of the variable\&. The attribute is evaluated based on which profile the state machine is using\&.
.PP
The value of the \fC<data>\fP variable can be changed through the use of \fC<assign>\fP elements, and their values can be passed on to other systems through the use of the \fI<send>\fP element in the External Communications Module\&.
.PP
\fBSince:\fP
.RS 4
Coin 4\&.0 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBScXMLDataModelElt\fP, \fBScXMLAssignElt\fP, \fBScXMLSendElt\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP ScXMLDataElt::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBScXMLElt\fP\&.
.SS "SbBool ScXMLDataElt::handleXMLAttributes (void)\fC [virtual]\fP"
This method is called when the file reader has set all the XML attributes on the object, and wants the object to handle them and report if the values were ok or if a read error should be produced\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the attributes are ok, and FALSE on error\&.
.RE
.PP
This base class implementation does nothing and just returns TRUE\&. 
.PP
Reimplemented from \fBScXMLElt\fP\&.
.SS "const \fBScXMLElt\fP * ScXMLDataElt::search (const char * attrname, const char * attrvalue) const\fC [virtual]\fP"
This method searches the SCXML structure for an element with the given attributevalue for the given attribute\&.
.PP
Returns NULL if nothing was found\&.
.PP
This function needs to be reimplemented to traverse child elements\&. 
.PP
Reimplemented from \fBScXMLElt\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
