.TH "ScXMLExprDataObj" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLExprDataObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBScXMLDataObj\fP\&.
.PP
Inherited by \fBScXMLAddOpExprDataObj\fP, \fBScXMLAndOpExprDataObj\fP, \fBScXMLAppendOpExprDataObj\fP, \fBScXMLCoinLengthFuncExprDataObj\fP, \fBScXMLDivideOpExprDataObj\fP, \fBScXMLEqualsOpExprDataObj\fP, \fBScXMLMinimumExprDataObj\fP, \fBScXMLMultiplyOpExprDataObj\fP, \fBScXMLNegateOpExprDataObj\fP, \fBScXMLNotOpExprDataObj\fP, \fBScXMLOrOpExprDataObj\fP, \fBScXMLReferenceDataObj\fP, and \fBScXMLSubtractOpExprDataObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const =0"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "\fBScXMLDataObj\fP * \fBevaluate\fP (\fBScXMLStateMachine\fP *sm)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual SbBool \fBevaluateNow\fP (\fBScXMLStateMachine\fP *sm, \fBScXMLDataObj\fP *&pointer) const =0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSoType\fP ScXMLExprDataObj::getTypeId (void) const\fC [pure virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBScXMLDataObj\fP\&.
.PP
Implemented in \fBScXMLNegateOpExprDataObj\fP, \fBScXMLDivideOpExprDataObj\fP, \fBScXMLMultiplyOpExprDataObj\fP, \fBScXMLSubtractOpExprDataObj\fP, \fBScXMLAddOpExprDataObj\fP, \fBScXMLEqualsOpExprDataObj\fP, \fBScXMLNotOpExprDataObj\fP, \fBScXMLOrOpExprDataObj\fP, \fBScXMLAndOpExprDataObj\fP, \fBScXMLReferenceDataObj\fP, \fBScXMLCoinLengthFuncExprDataObj\fP, \fBScXMLCoinDivideOpExprDataObj\fP, \fBScXMLCoinMultiplyOpExprDataObj\fP, \fBScXMLAppendOpExprDataObj\fP, \fBScXMLCoinSubtractOpExprDataObj\fP, \fBScXMLCoinAddOpExprDataObj\fP, \fBScXMLInExprDataObj\fP, \fBScXMLCoinEqualsOpExprDataObj\fP, and \fBScXMLMinimumExprDataObj\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
