.TH "ScXMLXPathEvaluator" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLXPathEvaluator \- implements the XPath evaluator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/scxml/ScXMLXPathEvaluator\&.h>\fP
.PP
Inherits \fBScXMLEvaluator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "virtual \fBScXMLDataObj\fP * \fBevaluate\fP (const char *expression) const"
.br
.ti -1c
.RI "virtual SbBool \fBsetAtLocation\fP (const char *location, \fBScXMLDataObj\fP *obj)"
.br
.ti -1c
.RI "virtual \fBScXMLDataObj\fP * \fBlocate\fP (const char *location) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
implements the XPath evaluator\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP ScXMLXPathEvaluator::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBScXMLEvaluator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
