.TH "ScXMLDocument" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLDocument
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/scxml/Document\&.h>\fP
.PP
Inherits \fBScXMLObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "void \fBsetFilename\fP (const char *filename)"
.br
.ti -1c
.RI "const char * \fBgetFilename\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetRoot\fP (\fBScXMLScxmlElt\fP *root)"
.br
.ti -1c
.RI "\fBScXMLScxmlElt\fP * \fBgetRoot\fP (void) const"
.br
.ti -1c
.RI "\fBScXMLAbstractStateElt\fP * \fBgetStateById\fP (\fBSbName\fP id) const"
.br
.ti -1c
.RI "\fBScXMLDataElt\fP * \fBgetDataById\fP (\fBSbName\fP id) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.ti -1c
.RI "static \fBScXMLDocument\fP * \fBreadFile\fP (const char *filename)"
.br
.ti -1c
.RI "static \fBScXMLDocument\fP * \fBreadBuffer\fP (const \fBSbByteBuffer\fP &buffer)"
.br
.ti -1c
.RI "static \fBScXMLDocument\fP * \fBreadXMLData\fP (\fBcc_xml_doc\fP *xmldoc)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The <\fBScXMLDocument\fP class is a container class for a complete SCXML document\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP ScXMLDocument::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBScXMLObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
