.TH "ScXMLStateMachine.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLStateMachine.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/scxml/ScXMLEventTarget\&.h>\fP
.br
\fC#include <Inventor/SbName\&.h>\fP
.br
\fC#include <Inventor/lists/SbList\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScXMLStateMachine\fP"
.br
.RI "Manager for processing events and setting states in SCXML structures\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBScXMLStateMachineDeleteCB\fP(void *userdata, \fBScXMLStateMachine\fP *statemachine)"
.br
.ti -1c
.RI "typedef void \fBScXMLStateChangeCB\fP(void *userdata, \fBScXMLStateMachine\fP *statemachine, const char *stateidentifier, SbBool enterstate, SbBool success)"
.br
.ti -1c
.RI "typedef void \fBScXMLParallelStateChangeCB\fP(void *userdata, \fBScXMLStateMachine\fP *statemachine, \fBint\fP numstates, const char **stateidentifiers, SbBool enterstate, SbBool success)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "void ScXMLStateMachineDeleteCB"
This is the type definition for all callback functions to be invoked when a state machine is deleted\&. 
.SS "ScXMLStateChangeCB"
This callback type is for notifying listeners on when the state machine enters and exits states that are tagged as 'tasks' for logging purposes\&. This is what the Boolean 'task' attribute in the state element sets up\&.
.PP
The \fIsuccess\fP argument is currently unsupported (will always be TRUE), but has been preemptively added to avoid a signature change later\&.
.PP
\fBSee also:\fP
.RS 4
addStateChangeCallback 
.RE
.PP

.SS "void ScXMLParallelStateChangeCB"
This typedef is currently unused\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
