.TH "ScXMLEltReader" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLEltReader \- base class for element reader objects  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/scxml/ScXMLElt\&.h>\fP
.PP
Inherited by ScXMLAnchorEltReader, ScXMLAssignEltReader, ScXMLContentEltReader, ScXMLDataEltReader, ScXMLDataModelEltReader, ScXMLElseEltReader, ScXMLElseIfEltReader, ScXMLEventEltReader, ScXMLFinalEltReader, ScXMLFinalizeEltReader, ScXMLHistoryEltReader, ScXMLIfEltReader, ScXMLInitialEltReader, ScXMLInvokeEltReader, ScXMLLogEltReader, ScXMLOnEntryEltReader, ScXMLOnExitEltReader, ScXMLParallelEltReader, ScXMLParamEltReader, ScXMLScriptEltReader, ScXMLScxmlEltReader, ScXMLSendEltReader, ScXMLStateEltReader, ScXMLTransitionEltReader, and ScXMLValidateEltReader\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScXMLEltReader\fP (const char *eltname)"
.br
.ti -1c
.RI "virtual \fBScXMLElt\fP * \fBread\fP (\fBScXMLElt\fP *container, cc_xml_elt *elt, \fBScXMLDocument\fP *doc, \fBScXMLStateMachine\fP *sm)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetXMLAttributes\fP (\fBScXMLElt\fP *scxmlelt, cc_xml_elt *xmlelt)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const char * \fBelement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
base class for element reader objects 


.PP
\fBSince:\fP
.RS 4
2008-11-23 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
