.TH "ScXMLMinimumExprDataObj" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScXMLMinimumExprDataObj \- implements the data objects for the evaluator for the minimum profile\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/scxml/ScXMLMinimumEvaluator\&.h>\fP
.PP
Inherits \fBScXMLExprDataObj\fP\&.
.PP
Inherited by \fBScXMLInExprDataObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const =0"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
implements the data objects for the evaluator for the minimum profile\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSoType\fP ScXMLMinimumExprDataObj::getTypeId (void) const\fC [pure virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBScXMLExprDataObj\fP\&.
.PP
Implemented in \fBScXMLInExprDataObj\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
