.TH "SoActionMethodList.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoActionMethodList.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/lists/SbPList\&.h>\fP
.br
\fC#include <Inventor/SoType\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoActionMethodList\fP"
.br
.RI "The \fBSoActionMethodList\fP class contains function pointers for action methods\&.
.PP
An \fBSoActionMethodList\fP contains one function pointer per node type\&. Each action contains an SoActioMethodList to know which functions to call during scene graph traversal\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBSoActionMethod\fP) (\fBSoAction\fP *, \fBSoNode\fP *)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "void(* SoActionMethod)(\fBSoAction\fP *, \fBSoNode\fP *)"
The type definition for all action method functions\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
