.TH "SoActionMethodList" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoActionMethodList \- The \fBSoActionMethodList\fP class contains function pointers for action methods\&.
.PP
An \fBSoActionMethodList\fP contains one function pointer per node type\&. Each action contains an SoActioMethodList to know which functions to call during scene graph traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/lists/SoActionMethodList\&.h>\fP
.PP
Inherits \fBSbPList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoActionMethodList\fP (\fBSoActionMethodList\fP *const parentlist)"
.br
.ti -1c
.RI "\fB~SoActionMethodList\fP ()"
.br
.ti -1c
.RI "\fBSoActionMethod\fP & \fBoperator[]\fP (const \fBint\fP index)"
.br
.ti -1c
.RI "void \fBaddMethod\fP (const \fBSoType\fP node, const \fBSoActionMethod\fP method)"
.br
.ti -1c
.RI "void \fBsetUp\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoActionMethodList\fP class contains function pointers for action methods\&.
.PP
An \fBSoActionMethodList\fP contains one function pointer per node type\&. Each action contains an SoActioMethodList to know which functions to call during scene graph traversal\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoActionMethodList::SoActionMethodList (\fBSoActionMethodList\fP *const parentlist)"
The constructor\&. The \fIparentlist\fP argument is the parent action's action method list\&. It can be \fCNULL\fP for action method lists that are not based on inheriting from a parent action\&. 
.SS "SoActionMethodList::~SoActionMethodList ()"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SoActionMethodList::addMethod (const \fBSoType\fP node, const \fBSoActionMethod\fP method)"
Add a function pointer to a node type's action method\&. 
.SS "void SoActionMethodList::setUp (void)"
This method must be called as the last initialization step before using the list\&. It fills in \fCNULL\fP entries with the parent's method\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
