.TH "SoCallback.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoCallback.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoSubNode\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoCallback\fP"
.br
.RI "The \fBSoCallback\fP class is a node type which provides a means of setting callback hooks in the scene graph\&.
.PP
By inserting \fBSoCallback\fP nodes in a scene graph, the application programmer can set up functions to be executed at certain points in the traversal\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBSoCallbackCB\fP(void *userdata, \fBSoAction\fP *action)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "void SoCallbackCB"
Signature that callback functions need to have\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
