.TH "SoCoordinateElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoCoordinateElement \- The \fBSoCoordinateElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoCoordinateElement\&.h>\fP
.PP
Inherits \fBSoReplacedElement\fP\&.
.PP
Inherited by \fBSoGLCoordinateElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "int32_t \fBgetNum\fP () const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "SbBool \fBis3D\fP () const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec3f\fP & \fBget3\fP (const \fBint\fP index) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec4f\fP & \fBget4\fP (const \fBint\fP index) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec3f\fP * \fBgetArrayPtr3\fP () const"
.br
.ti -1c
.RI "const \fBSbVec4f\fP * \fBgetArrayPtr4\fP () const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (FILE *file) const"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset3\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const int32_t \fBnumCoords\fP, const \fBSbVec3f\fP *const coords)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBset4\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const int32_t \fBnumCoords\fP, const \fBSbVec4f\fP *const coords)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static const \fBSoCoordinateElement\fP * \fBgetInstance\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static \fBSbVec3f\fP \fBgetDefault3\fP ()"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static \fBSbVec4f\fP \fBgetDefault4\fP ()"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoCoordinateElement\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBnumCoords\fP"
.br
.ti -1c
.RI "const \fBSbVec3f\fP * \fBcoords3D\fP"
.br
.ti -1c
.RI "const \fBSbVec4f\fP * \fBcoords4D\fP"
.br
.ti -1c
.RI "SbBool \fBareCoords3D\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoCoordinateElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoCoordinateElement::~SoCoordinateElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoCoordinateElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoCoordinateElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoCoordinateElement\fP class\&. 
.SS "const \fBSbVec3f\fP * SoCoordinateElement::getArrayPtr3 (void) const"
Returns a pointer to the 3D coordinate array\&. Don't use this method unless \fBSoCoordinateElement::is3D()\fP returns \fCTRUE\fP\&.
.PP
This method is not part of the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 1\&.0 
.RE
.PP

.SS "const \fBSbVec4f\fP * SoCoordinateElement::getArrayPtr4 () const"
Returns a pointer to the 4D coordinate array\&. Don't use this method unless \fBSoCoordinateElement::is3D()\fP returns \fCFALSE\fP\&.
.PP
This method is not part of the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 1\&.0 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "SoCoordinateElement::numCoords\fC [protected]\fP"
FIXME: write doc\&. 
.SS "SoCoordinateElement::coords3D\fC [protected]\fP"
FIXME: write doc\&. 
.SS "SoCoordinateElement::coords4D\fC [protected]\fP"
FIXME: write doc\&. 
.SS "SoCoordinateElement::areCoords3D\fC [protected]\fP"
FIXME: write doc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
