.TH "SoCreaseAngleElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoCreaseAngleElement \- The \fBSoCreaseAngleElement\fP class stores the crease angle during a scene graph traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoCreaseAngleElement\&.h>\fP
.PP
Inherits \fBSoFloatElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const float complexity)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, const float complexity)"
.br
.ti -1c
.RI "static float \fBget\fP (\fBSoState\fP *const state)"
.br
.ti -1c
.RI "static float \fBget\fP (\fBSoState\fP *const state, const SbBool isvrml1)"
.br
.ti -1c
.RI "static float \fBgetDefault\fP (void)"
.br
.ti -1c
.RI "static float \fBgetDefault\fP (const SbBool isvrml1)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoCreaseAngleElement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoCreaseAngleElement\fP class stores the crease angle during a scene graph traversal\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoCreaseAngleElement::~SoCreaseAngleElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoCreaseAngleElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoCreaseAngleElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
This function initializes the element type in the given \fBSoState\fP\&. It is called for the first element of each enabled element type in \fBSoState\fP objects\&. 
.PP
Reimplemented from \fBSoFloatElement\fP\&.
.SS "void SoCreaseAngleElement::set (\fBSoState\fP *const state, \fBSoNode\fP *const node, const float complexity)\fC [static]\fP"
Sets the value of this element\&. 
.SS "void SoCreaseAngleElement::set (\fBSoState\fP *const state, const float complexity)\fC [static]\fP"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. 
.SS "float SoCreaseAngleElement::get (\fBSoState\fP *const state)\fC [static]\fP"
Returns the element value\&. This method can be used if you know that the node that is going to use the crease angle is an Inventor node\&. 
.SS "float SoCreaseAngleElement::get (\fBSoState\fP *const state, const SbBool isvrml1)\fC [static]\fP"
Returns the element value\&. \fIisvrml1\fP should be TRUE if the node requesting the value is a VRML1 node\&.
.PP
This method is an extension versus the Open Inventor API\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoNode::getNodeType()\fP 
.RE
.PP

.SS "float SoCreaseAngleElement::getDefault (void)\fC [static]\fP"
Returns the default value for Inventor scene graphs (0\&.0)\&. 
.SS "float SoCreaseAngleElement::getDefault (const SbBool isvrml1)\fC [static]\fP"
Returns the default value for this element\&. \fIisvrml1\fP should be TRUE if the node requesting the value is a VRML1 node\&.
.PP
This method is an extension versus the Open Inventor API\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoNode::getNodeType()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
