.TH "SoDepthBufferElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoDepthBufferElement \- The \fBSoDepthBufferElement\fP controls the depth buffer settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoDepthBufferElement\&.h>\fP
.PP
Inherits \fBSoElement\fP\&.
.PP
Inherited by \fBSoGLDepthBufferElement\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDepthWriteFunction\fP { \fBNEVER\fP, \fBALWAYS\fP, \fBLESS\fP, \fBLEQUAL\fP, \fBEQUAL\fP, \fBGEQUAL\fP, \fBGREATER\fP, \fBNOTEQUAL\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpush\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpop\fP (\fBSoState\fP *state, const \fBSoElement\fP *prevTopElement)"
.br
.ti -1c
.RI "virtual SbBool \fBmatches\fP (const \fBSoElement\fP *element) const"
.br
.ti -1c
.RI "virtual \fBSoElement\fP * \fBcopyMatchInfo\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *state, SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)"
.br
.ti -1c
.RI "static void \fBget\fP (\fBSoState\fP *state, SbBool &test_out, SbBool &write_out, DepthWriteFunction &function_out, \fBSbVec2f\fP &range_out)"
.br
.ti -1c
.RI "static SbBool \fBgetTestEnable\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "static SbBool \fBgetWriteEnable\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "static DepthWriteFunction \fBgetFunction\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "static \fBSbVec2f\fP \fBgetRange\fP (\fBSoState\fP *state)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoDepthBufferElement\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetElt\fP (SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SbBool \fBtest\fP"
.br
.ti -1c
.RI "SbBool \fBwrite\fP"
.br
.ti -1c
.RI "DepthWriteFunction \fBfunction\fP"
.br
.ti -1c
.RI "\fBSbVec2f\fP \fBrange\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoDepthBufferElement\fP controls the depth buffer settings\&. 

Be aware that this class is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&. 
.PP
\fBSince:\fP
.RS 4
Coin 3\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoDepthBufferElement::~SoDepthBufferElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoDepthBufferElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDepthBufferElement::initClass (void)\fC [static]\fP"
This function initializes the \fBSoDepthBufferElement\fP class type for Coin\&. 
.SS "void SoDepthBufferElement::set (\fBSoState\fP * state, SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)\fC [static]\fP"
Set this element's values\&. 
.SS "void SoDepthBufferElement::get (\fBSoState\fP * state, SbBool & test_out, SbBool & write_out, DepthWriteFunction & function_out, \fBSbVec2f\fP & range_out)\fC [static]\fP"
Fetches this element's values\&. 
.SS "SbBool SoDepthBufferElement::getTestEnable (\fBSoState\fP * state)\fC [static]\fP"
Returns the depth test enabled state\&. 
.SS "SbBool SoDepthBufferElement::getWriteEnable (\fBSoState\fP * state)\fC [static]\fP"
Returns the depth buffer write enabled state\&. 
.SS "SoDepthBufferElement::DepthWriteFunction SoDepthBufferElement::getFunction (\fBSoState\fP * state)\fC [static]\fP"
Returns the set depth buffer write function\&. 
.SS "\fBSbVec2f\fP SoDepthBufferElement::getRange (\fBSoState\fP * state)\fC [static]\fP"
Returns the depth buffer value range used\&. 
.SS "void SoDepthBufferElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.PP
Reimplemented in \fBSoGLDepthBufferElement\fP\&.
.SS "void SoDepthBufferElement::push (\fBSoState\fP * state)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.PP
Reimplemented in \fBSoGLDepthBufferElement\fP\&.
.SS "void SoDepthBufferElement::pop (\fBSoState\fP * state, const \fBSoElement\fP * prevTopElement)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.PP
Reimplemented in \fBSoGLDepthBufferElement\fP\&.
.SS "SbBool SoDepthBufferElement::matches (const \fBSoElement\fP * element) const\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "\fBSoElement\fP * SoDepthBufferElement::copyMatchInfo (void) const\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "void SoDepthBufferElement::setElt (SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)\fC [protected]\fP, \fC [virtual]\fP"
Virtual method to set the state to get derived elements updated\&. 
.PP
Reimplemented in \fBSoGLDepthBufferElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
