.TH "SoDragger" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoDragger \- The \fBSoDragger\fP class is the base class for all draggers\&.
.PP
Draggers is a mechanism used for letting the end-users of your application code interact with elements in 3D, by scaling, rotating or translating geometry or other instances in the scene (like cameras or lightsources)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/draggers/SoDragger\&.h>\fP
.PP
Inherits \fBSoInteractionKit\fP\&.
.PP
Inherited by \fBSoCenterballDragger\fP, \fBSoDirectionalLightDragger\fP, \fBSoDragPointDragger\fP, \fBSoHandleBoxDragger\fP, \fBSoJackDragger\fP, \fBSoPointLightDragger\fP, \fBSoRotateCylindricalDragger\fP, \fBSoRotateDiscDragger\fP, \fBSoRotateSphericalDragger\fP, \fBSoScale1Dragger\fP, \fBSoScale2Dragger\fP, \fBSoScale2UniformDragger\fP, \fBSoScaleUniformDragger\fP, \fBSoSpotLightDragger\fP, \fBSoTabBoxDragger\fP, \fBSoTabPlaneDragger\fP, \fBSoTrackballDragger\fP, \fBSoTransformBoxDragger\fP, \fBSoTransformerDragger\fP, \fBSoTranslate1Dragger\fP, and \fBSoTranslate2Dragger\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBProjectorFrontSetting\fP { \fBFRONT\fP, \fBBACK\fP, \fBUSE_PICK\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "virtual const \fBSoNodekitCatalog\fP * \fBgetNodekitCatalog\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcallback\fP (\fBSoCallbackAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBGLRender\fP (\fBSoGLRenderAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBgetMatrix\fP (\fBSoGetMatrixAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBrayPick\fP (\fBSoRayPickAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBsearch\fP (\fBSoSearchAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBSoWriteAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBgetPrimitiveCount\fP (\fBSoGetPrimitiveCountAction\fP *action)"
.br
.ti -1c
.RI "void \fBsetProjectorEpsilon\fP (const float epsilon)"
.br
.ti -1c
.RI "float \fBgetProjectorEpsilon\fP (void) const"
.br
.ti -1c
.RI "void \fBaddStartCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBremoveStartCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBaddMotionCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBremoveMotionCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBaddFinishCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBremoveFinishCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBaddValueChangedCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBremoveValueChangedCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBsetMinGesture\fP (\fBint\fP pixels)"
.br
.ti -1c
.RI "\fBint\fP \fBgetMinGesture\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBenableValueChangedCallbacks\fP (SbBool newval)"
.br
.ti -1c
.RI "const \fBSbMatrix\fP & \fBgetMotionMatrix\fP (void)"
.br
.ti -1c
.RI "void \fBaddOtherEventCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBremoveOtherEventCallback\fP (\fBSoDraggerCB\fP *func, void *data=NULL)"
.br
.ti -1c
.RI "void \fBregisterChildDragger\fP (\fBSoDragger\fP *child)"
.br
.ti -1c
.RI "void \fBunregisterChildDragger\fP (\fBSoDragger\fP *child)"
.br
.ti -1c
.RI "void \fBregisterChildDraggerMovingIndependently\fP (\fBSoDragger\fP *child)"
.br
.ti -1c
.RI "void \fBunregisterChildDraggerMovingIndependently\fP (\fBSoDragger\fP *child)"
.br
.ti -1c
.RI "\fBSbMatrix\fP \fBgetLocalToWorldMatrix\fP (void)"
.br
.ti -1c
.RI "\fBSbMatrix\fP \fBgetWorldToLocalMatrix\fP (void)"
.br
.ti -1c
.RI "\fBSbVec3f\fP \fBgetLocalStartingPoint\fP (void)"
.br
.ti -1c
.RI "\fBSbVec3f\fP \fBgetWorldStartingPoint\fP (void)"
.br
.ti -1c
.RI "void \fBgetPartToLocalMatrix\fP (const \fBSbName\fP &partname, \fBSbMatrix\fP &parttolocalmatrix, \fBSbMatrix\fP &localtopartmatrix)"
.br
.ti -1c
.RI "void \fBtransformMatrixLocalToWorld\fP (const \fBSbMatrix\fP &frommatrix, \fBSbMatrix\fP &tomatrix)"
.br
.ti -1c
.RI "void \fBtransformMatrixWorldToLocal\fP (const \fBSbMatrix\fP &frommatrix, \fBSbMatrix\fP &tomatrix)"
.br
.ti -1c
.RI "void \fBtransformMatrixToLocalSpace\fP (const \fBSbMatrix\fP &frommatrix, \fBSbMatrix\fP &tomatrix, const \fBSbName\fP &fromspacepartname)"
.br
.ti -1c
.RI "virtual void \fBsetMotionMatrix\fP (const \fBSbMatrix\fP &newmatrix)"
.br
.ti -1c
.RI "void \fBvalueChanged\fP (void)"
.br
.ti -1c
.RI "const \fBSbMatrix\fP & \fBgetStartMotionMatrix\fP (void)"
.br
.ti -1c
.RI "virtual void \fBsaveStartParameters\fP (void)"
.br
.ti -1c
.RI "const \fBSoPath\fP * \fBgetPickPath\fP (void) const"
.br
.ti -1c
.RI "const \fBSoEvent\fP * \fBgetEvent\fP (void) const"
.br
.ti -1c
.RI "\fBSoPath\fP * \fBcreatePathToThis\fP (void)"
.br
.ti -1c
.RI "const \fBSoPath\fP * \fBgetSurrogatePartPickedOwner\fP (void) const"
.br
.ti -1c
.RI "const \fBSbName\fP & \fBgetSurrogatePartPickedName\fP (void) const"
.br
.ti -1c
.RI "const \fBSoPath\fP * \fBgetSurrogatePartPickedPath\fP (void) const"
.br
.ti -1c
.RI "void \fBsetStartingPoint\fP (const \fBSoPickedPoint\fP *newpoint)"
.br
.ti -1c
.RI "void \fBsetStartingPoint\fP (const \fBSbVec3f\fP &newpoint)"
.br
.ti -1c
.RI "const \fBSbViewVolume\fP & \fBgetViewVolume\fP (void)"
.br
.ti -1c
.RI "void \fBsetViewVolume\fP (const \fBSbViewVolume\fP &vol)"
.br
.ti -1c
.RI "const \fBSbViewportRegion\fP & \fBgetViewportRegion\fP (void)"
.br
.ti -1c
.RI "void \fBsetViewportRegion\fP (const \fBSbViewportRegion\fP &reg)"
.br
.ti -1c
.RI "\fBSoHandleEventAction\fP * \fBgetHandleEventAction\fP (void) const"
.br
.ti -1c
.RI "void \fBsetHandleEventAction\fP (\fBSoHandleEventAction\fP *newAction)"
.br
.ti -1c
.RI "void \fBsetTempPathToThis\fP (const \fBSoPath\fP *somethingclose)"
.br
.ti -1c
.RI "virtual void \fBgrabEventsSetup\fP (void)"
.br
.ti -1c
.RI "virtual void \fBgrabEventsCleanup\fP (void)"
.br
.ti -1c
.RI "void \fBworkFieldsIntoTransform\fP (\fBSbMatrix\fP &mtx)"
.br
.ti -1c
.RI "void \fBsetFrontOnProjector\fP (\fBProjectorFrontSetting\fP newval)"
.br
.ti -1c
.RI "\fBProjectorFrontSetting\fP \fBgetFrontOnProjector\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static const \fBSoNodekitCatalog\fP * \fBgetClassNodekitCatalog\fP (void)"
.br
.ti -1c
.RI "static void \fBsetMinScale\fP (float newminscale)"
.br
.ti -1c
.RI "static float \fBgetMinScale\fP (void)"
.br
.ti -1c
.RI "static void \fBworkValuesIntoTransform\fP (\fBSbMatrix\fP &mtx, const \fBSbVec3f\fP *translationptr, const \fBSbRotation\fP *rotationptr, const \fBSbVec3f\fP *scalefactorptr, const \fBSbRotation\fP *scaleorientationptr, const \fBSbVec3f\fP *centerptr)"
.br
.ti -1c
.RI "static void \fBgetTransformFast\fP (\fBSbMatrix\fP &mtx, \fBSbVec3f\fP &translation, \fBSbRotation\fP &rotation, \fBSbVec3f\fP &scalefactor, \fBSbRotation\fP &scaleorientation, const \fBSbVec3f\fP &center)"
.br
.ti -1c
.RI "static void \fBgetTransformFast\fP (\fBSbMatrix\fP &mtx, \fBSbVec3f\fP &translation, \fBSbRotation\fP &rotation, \fBSbVec3f\fP &scalefactor, \fBSbRotation\fP &scaleorientation)"
.br
.ti -1c
.RI "static \fBSbMatrix\fP \fBappendTranslation\fP (const \fBSbMatrix\fP &mtx, const \fBSbVec3f\fP &translation, const \fBSbMatrix\fP *conversion=NULL)"
.br
.ti -1c
.RI "static \fBSbMatrix\fP \fBappendScale\fP (const \fBSbMatrix\fP &mtx, const \fBSbVec3f\fP &scale, const \fBSbVec3f\fP &scalecenter, const \fBSbMatrix\fP *conversion=NULL)"
.br
.ti -1c
.RI "static \fBSbMatrix\fP \fBappendRotation\fP (const \fBSbMatrix\fP &mtx, const \fBSbRotation\fP &rot, const \fBSbVec3f\fP &rotcenter, const \fBSbMatrix\fP *conversion=NULL)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClasses\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoSFBool\fP \fBisActive\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBSoFieldData\fP * \fBgetFieldData\fP (void) const"
.br
.ti -1c
.RI "\fBSoDragger\fP (void)"
.br
.ti -1c
.RI "virtual \fB~SoDragger\fP (void)"
.br
.ti -1c
.RI "\fBSbVec2f\fP \fBgetNormalizedLocaterPosition\fP (void)"
.br
.ti -1c
.RI "\fBSbVec2s\fP \fBgetLocaterPosition\fP (void)"
.br
.ti -1c
.RI "\fBSbVec2s\fP \fBgetStartLocaterPosition\fP (void) const"
.br
.ti -1c
.RI "void \fBsetStartLocaterPosition\fP (\fBSbVec2s\fP p)"
.br
.ti -1c
.RI "SbBool \fBisAdequateConstraintMotion\fP (void)"
.br
.ti -1c
.RI "virtual SbBool \fBshouldGrabBasedOnSurrogate\fP (const \fBSoPath\fP *pickpath, const \fBSoPath\fP *surrogatepath)"
.br
.ti -1c
.RI "void \fBsetCameraInfo\fP (\fBSoAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBhandleEvent\fP (\fBSoHandleEventAction\fP *ha)"
.br
.ti -1c
.RI "void \fBtransferMotion\fP (\fBSoDragger\fP *child)"
.br
.ti -1c
.RI "void \fBsetIgnoreInBbox\fP (SbBool newval)"
.br
.ti -1c
.RI "SbBool \fBisIgnoreInBbox\fP (void)"
.br
.ti -1c
.RI "virtual void \fBgetBoundingBox\fP (\fBSoGetBoundingBoxAction\fP *action)"
.br
.ti -1c
.RI "void \fBsetActiveChildDragger\fP (\fBSoDragger\fP *newchilddragger)"
.br
.ti -1c
.RI "\fBSoDragger\fP * \fBgetActiveChildDragger\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetDefaultOnNonWritingFields\fP (void)"
.br
.ti -1c
.RI "void \fBupdateDraggerCache\fP (const \fBSoPath\fP *path)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static const \fBSoFieldData\fP ** \fBgetFieldDataPtr\fP (void)"
.br
.ti -1c
.RI "static const \fBSoNodekitCatalog\fP ** \fBgetClassNodekitCatalogPtr\fP (void)"
.br
.ti -1c
.RI "static void \fBchildTransferMotionAndValueChangedCB\fP (void *, \fBSoDragger\fP *)"
.br
.ti -1c
.RI "static void \fBchildValueChangedCB\fP (void *, \fBSoDragger\fP *)"
.br
.ti -1c
.RI "static void \fBchildStartCB\fP (void *, \fBSoDragger\fP *)"
.br
.ti -1c
.RI "static void \fBchildMotionCB\fP (void *, \fBSoDragger\fP *)"
.br
.ti -1c
.RI "static void \fBchildFinishCB\fP (void *, \fBSoDragger\fP *)"
.br
.ti -1c
.RI "static void \fBchildOtherEventCB\fP (void *, \fBSoDragger\fP *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSoSFNode\fP \fBmotionMatrix\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoDragger\fP class is the base class for all draggers\&.
.PP
Draggers is a mechanism used for letting the end-users of your application code interact with elements in 3D, by scaling, rotating or translating geometry or other instances in the scene (like cameras or lightsources)\&. 

For a very thorough introduction and tutorial to the dragger classes and general concepts, we advise you to consult «The Inventor Mentor», ISBN 0-201-62495-8, chapter 15\&.
.PP
This is the common superclass for all dragger classes\&.
.PP
It holds the current motion matrix, and offers lots of convenience methods to build from for it's subclasses -- that is, the non-abstract dragger classes to use as nodes in your scenegraph\&.
.PP
The motion matrix is used to modify the model matrix during traversal, and this is a common dragger mechanism -- all draggers should update this during dragging\&.
.PP
A number of the Coin dragger classes have built-in convenience wrapper classes, called \fImanipulators\fP\&. See for instance the \fBSoTrackballDragger\fP / \fBSoTrackballManip\fP pair\&.
.PP
The matching manipulator class for any dragger class has basically two convenient additions to the functionality of the stand-alone dragger: 1) it makes swapping the dragger in and out of the scenegraph very straightforward (something which is often done for draggers in 3D user interfaces), 2) it wraps up the dragger with \fBSoSurroundScale\fP and \fBSoAntiSquish\fP nodes where applicable, so the dragger geometry automatically scales up or down to match the geometry it influences\&.
.PP
This last functionality can also be duplicated in a rather straightforward manner outside of the context of a manipulator, as can be seen from the usage example in the \fBSoSurroundScale\fP class documentation\&.
.PP
The appearance of draggers can be modified by either using the \fBSoDragger::setPart()\fP method (see usage example below) or by setting up external Inventor-format files which the geometry parts are read from\&. The latter method can be done by setting the environment variable \fCSO_DRAGGER_DIR\fP to point to a directory with replacement geometry files\&. The name of the new files and the name of the nodes / sub-graphs with the replacement geometries must follow a rigid scheme\&. We advise you to look at the Coin sourcecode directory Coin/data/draggerDefaults/ to see how the replacement geometry files should be named\&. Setting \fCSO_DRAGGER_DIR\fP to this directory and modifying the files there provides a convenient way to play around with new dragger geometry arrangements\&.
.PP
As mentioned above, \fBSoDragger::setPart()\fP can be used to modify the appearance of a dragger by changing it's default geometry\&. One common technique is for instance to take advantage of this to use only \fIparts\fP of a dragger, by replacing / disabling the geometry that you don't want the end-user to interact with\&. The following code example shows how to remove the translation functionality of the \fBSoTransformBoxDragger\fP:
.PP
.PP
.nf
#include <Inventor/Qt/SoQt\&.h>
#include <Inventor/Qt/viewers/SoQtExaminerViewer\&.h>
#include <Inventor/draggers/SoTransformBoxDragger\&.h>
#include <Inventor/nodes/SoSeparator\&.h>


int
main(int argc, char ** argv)
{
  QWidget * window = SoQt::init(argv[0]);

  SoTransformBoxDragger * dragger = new SoTransformBoxDragger;

  SbString str;
  for (int i = 1; i <= 6; i++) {
    str\&.sprintf("translator%d\&.translator", i);
    dragger->setPart(str\&.getString(), new SoSeparator);
  }

  SoQtExaminerViewer * viewer = new SoQtExaminerViewer(window);
  viewer->setSceneGraph(dragger);
  viewer->show();
  SoQt::show(window);

  SoQt::mainLoop();

  delete viewer;
  return 0;
}
.fi
.PP
.PP
Draggers are also node kits, and below is the catalog structure for this top-level dragger class\&.
.PP
Node kit structure (new entries versus parent class marked with arrow prefix):
.PP
.PP
.nf
CLASS SoDragger
-->"this"
      "callbackList"
      "topSeparator"
-->      "motionMatrix"
         "geomSeparator"
.fi
.PP
.PP
(See \fBSoBaseKit::printDiagram()\fP for information about the output formatting\&.)
.PP
Detailed information on catalog parts:
.PP
.PP
.nf
CLASS SoDragger
PVT   "this",  SoDragger  ---
      "callbackList",  SoNodeKitListPart [ SoCallback, SoEventCallback ]
PVT   "topSeparator",  SoSeparator  ---
PVT   "motionMatrix",  SoMatrixTransform  ---
PVT   "geomSeparator",  SoSeparator  ---
.fi
.PP
.PP
(See \fBSoBaseKit::printTable()\fP for information about the output formatting\&.) 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSoDragger::ProjectorFrontSetting\fP"
Holds various settings for projectors, which might affect cylindrical and spherical based draggers\&. Specifies whether dragging should be based on the front or back of the sphere / cylinder, or if the picked point should be used to decide this\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFRONT \fP\fP
Always use front of projector\&. 
.TP
\fB\fIBACK \fP\fP
Always use back of projector\&. 
.TP
\fB\fIUSE_PICK \fP\fP
Use picked point to decide front or back of projector\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoDragger::SoDragger (void)\fC [protected]\fP"
A protected constructor for this abstract superclass for all Coin draggers\&. 
.SS "SoDragger::~SoDragger (void)\fC [protected]\fP, \fC [virtual]\fP"
Virtual protected destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoDragger::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. Usage example:
.PP
.PP
.nf
void foo(SoNode * node)
{
  if (node->getTypeId() == SoFile::getClassTypeId()) {
    SoFile * filenode = (SoFile *)node;  // safe downward cast, knows the type
  }
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new nodes, engines, nodekits, draggers or others: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through for instance \fBInventor/nodes/SoSubNode\&.h\fP (SO_NODE_INIT_CLASS and SO_NODE_CONSTRUCTOR for node classes), \fBInventor/engines/SoSubEngine\&.h\fP (for engine classes) and so on\&.
.PP
For more information on writing Coin extensions, see the class documentation of the toplevel superclasses for the various class groups\&. 
.PP
Reimplemented from \fBSoInteractionKit\fP\&.
.PP
Reimplemented in \fBSoTrackballDragger\fP, \fBSoTransformerDragger\fP, \fBSoSpotLightDragger\fP, \fBSoRotateSphericalDragger\fP, \fBSoScale2UniformDragger\fP, \fBSoTabPlaneDragger\fP, \fBSoTranslate1Dragger\fP, \fBSoTranslate2Dragger\fP, \fBSoHandleBoxDragger\fP, \fBSoScale2Dragger\fP, \fBSoRotateCylindricalDragger\fP, \fBSoScale1Dragger\fP, \fBSoScaleUniformDragger\fP, \fBSoDirectionalLightDragger\fP, \fBSoJackDragger\fP, \fBSoRotateDiscDragger\fP, \fBSoCenterballDragger\fP, \fBSoTransformBoxDragger\fP, \fBSoPointLightDragger\fP, \fBSoDragPointDragger\fP, and \fBSoTabBoxDragger\fP\&.
.SS "const \fBSoFieldData\fP * SoDragger::getFieldData (void) const\fC [protected]\fP, \fC [virtual]\fP"
Returns a pointer to the class-wide field data storage object for this instance\&. If no fields are present, returns \fCNULL\fP\&. 
.PP
Reimplemented from \fBSoInteractionKit\fP\&.
.PP
Reimplemented in \fBSoTrackballDragger\fP, \fBSoTransformerDragger\fP, \fBSoSpotLightDragger\fP, \fBSoRotateSphericalDragger\fP, \fBSoScale2UniformDragger\fP, \fBSoTabPlaneDragger\fP, \fBSoTranslate1Dragger\fP, \fBSoTranslate2Dragger\fP, \fBSoHandleBoxDragger\fP, \fBSoScale2Dragger\fP, \fBSoRotateCylindricalDragger\fP, \fBSoScale1Dragger\fP, \fBSoScaleUniformDragger\fP, \fBSoDirectionalLightDragger\fP, \fBSoJackDragger\fP, \fBSoRotateDiscDragger\fP, \fBSoCenterballDragger\fP, \fBSoTransformBoxDragger\fP, \fBSoPointLightDragger\fP, \fBSoDragPointDragger\fP, and \fBSoTabBoxDragger\fP\&.
.SS "const \fBSoNodekitCatalog\fP * SoDragger::getNodekitCatalog (void) const\fC [virtual]\fP"
Returns the nodekit catalog which defines the layout of this class' kit\&. 
.PP
Reimplemented from \fBSoInteractionKit\fP\&.
.PP
Reimplemented in \fBSoTrackballDragger\fP, \fBSoTransformerDragger\fP, \fBSoSpotLightDragger\fP, \fBSoRotateSphericalDragger\fP, \fBSoScale2UniformDragger\fP, \fBSoTabPlaneDragger\fP, \fBSoTranslate1Dragger\fP, \fBSoTranslate2Dragger\fP, \fBSoHandleBoxDragger\fP, \fBSoScale2Dragger\fP, \fBSoRotateCylindricalDragger\fP, \fBSoScale1Dragger\fP, \fBSoScaleUniformDragger\fP, \fBSoDirectionalLightDragger\fP, \fBSoJackDragger\fP, \fBSoRotateDiscDragger\fP, \fBSoCenterballDragger\fP, \fBSoTransformBoxDragger\fP, \fBSoPointLightDragger\fP, \fBSoDragPointDragger\fP, and \fBSoTabBoxDragger\fP\&.
.SS "void SoDragger::callback (\fBSoCallbackAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoCallbackAction\fP\&.
.PP
Simply updates the state according to how the node behaves for the render action, so the application programmer can use the \fBSoCallbackAction\fP for extracting information about the scene graph\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::GLRender (\fBSoGLRenderAction\fP * action)\fC [virtual]\fP"
Action method for the \fBSoGLRenderAction\fP\&.
.PP
This is called during rendering traversals\&. Nodes influencing the rendering state in any way or who wants to throw geometry primitives at OpenGL overrides this method\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.PP
Reimplemented in \fBSoTabPlaneDragger\fP\&.
.SS "void SoDragger::getMatrix (\fBSoGetMatrixAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoGetMatrixAction\fP\&.
.PP
Updates \fIaction\fP by accumulating with the transformation matrix of this node (if any)\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.PP
Reimplemented in \fBSoCenterballDragger\fP\&.
.SS "void SoDragger::rayPick (\fBSoRayPickAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoRayPickAction\fP\&.
.PP
Checks the ray specification of the \fIaction\fP and tests for intersection with the data of the node\&.
.PP
Nodes influencing relevant state variables for how picking is done also overrides this method\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::search (\fBSoSearchAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoSearchAction\fP\&.
.PP
Compares the search criteria from the \fIaction\fP to see if this node is a match\&. Searching is done by matching up \fIall\fP criteria set up in the \fBSoSearchAction\fP -- if \fIany\fP of the requested criteria is a miss, the search is not deemed successful for the node\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoSearchAction\fP 
.RE
.PP

.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::write (\fBSoWriteAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoWriteAction\fP\&.
.PP
Writes out a node object, and any connected nodes, engines etc, if necessary\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::getPrimitiveCount (\fBSoGetPrimitiveCountAction\fP * action)\fC [virtual]\fP"
Action method for the \fBSoGetPrimitiveCountAction\fP\&.
.PP
Calculates the number of triangle, line segment and point primitives for the node and adds these to the counters of the \fIaction\fP\&.
.PP
Nodes influencing how geometry nodes calculates their primitive count also overrides this method to change the relevant state variables\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::setProjectorEpsilon (const float epsilon)"
Sets the epsilon used for restricting the draggers when the intersection line is almost parallel with the projector direction\&.
.PP
For line projectors this is based on the dot product between the picking ray and the projector line\&. For plane projector, the dot product between the plane normal and the picking ray is used\&.
.PP
Default value is 0\&.0\&.
.PP
\fBSince:\fP
.RS 4
Coin 3\&.0 
.RE
.PP

.SS "void SoDragger::addStartCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Adds a callback which is called at the start of a drag, after the mouse button 1 is pressed, and dragger is picked\&. 
.SS "void SoDragger::removeStartCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Removes a previously registered start callback\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddStartCallback()\fP 
.RE
.PP

.SS "void SoDragger::addMotionCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Adds a callback which is called for each mouse movement during dragging\&. 
.SS "void SoDragger::removeMotionCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Removes a previously registered motion callback\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddMotionCallback()\fP 
.RE
.PP

.SS "void SoDragger::addFinishCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Adds a callback which is called after dragging is finished\&. 
.SS "void SoDragger::removeFinishCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Removes a finish callback\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddFinishCallback()\fP 
.RE
.PP

.SS "void SoDragger::addValueChangedCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Adds a callback which is called after a dragger has changed a field\&. It is not called if the \fBSoDragger::isActive\fP field is changed\&.
.PP
\fBSee also:\fP
.RS 4
enableValueChangedCallback() 
.RE
.PP

.SS "void SoDragger::removeValueChangedCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Removes a value changed callback\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddValueChangedCallback()\fP 
.RE
.PP

.SS "void SoDragger::setMinGesture (\fBint\fP pixels)"
Sets the number of pixel movement needed to trigger a constraint gesture\&. Default is 8 pixels\&. 
.SS "\fBint\fP SoDragger::getMinGesture (void) const"
Returns the gesture pixels threshold value\&.
.PP
\fBSee also:\fP
.RS 4
\fBsetMinGesture()\fP 
.RE
.PP

.SS "SbBool SoDragger::enableValueChangedCallbacks (SbBool val)"
Enable or disable 'value changed' callbacks\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddValueChangedCallback()\fP 
.RE
.PP

.SS "const \fBSbMatrix\fP & SoDragger::getMotionMatrix (void)"
Returns the motion matrix for this dragger\&. 
.SS "void SoDragger::addOtherEventCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Adds an event callback for events other then drag events\&. As soon as dragging starts, the dragger grabs all events (until mouse button is released)\&. This method can be used to handle other events during dragging\&. 
.SS "void SoDragger::removeOtherEventCallback (\fBSoDraggerCB\fP * func, void * data = \fCNULL\fP)"
Removes a other event callback\&.
.PP
\fBSee also:\fP
.RS 4
\fBaddOtherEventCallback()\fP 
.RE
.PP

.SS "void SoDragger::registerChildDragger (\fBSoDragger\fP * child)"
Should be called by compound draggers to register child draggers\&. 
.SS "void SoDragger::unregisterChildDragger (\fBSoDragger\fP * child)"
Should be called by compound draggers to unregister child draggers\&. 
.SS "void SoDragger::registerChildDraggerMovingIndependently (\fBSoDragger\fP * child)"
Should be called by compund draggers to register child draggers that should move independently of their parent\&. 
.SS "void SoDragger::unregisterChildDraggerMovingIndependently (\fBSoDragger\fP * child)"
Should be called by compund draggers to unregister child draggers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBregisterChildDraggerMovingIndependently()\fP 
.RE
.PP

.SS "\fBSbMatrix\fP SoDragger::getLocalToWorldMatrix (void)"
Returns a matrix that converts from local to world space\&. 
.SS "\fBSbMatrix\fP SoDragger::getWorldToLocalMatrix (void)"
Returns a matrix that converts from world to local space\&. 
.SS "\fBSbVec3f\fP SoDragger::getLocalStartingPoint (void)"
Returns the drag starting point in the local coordinate system\&. 
.SS "\fBSbVec3f\fP SoDragger::getWorldStartingPoint (void)"
Returns the drag starting point in the world coordinate system\&. 
.SS "void SoDragger::getPartToLocalMatrix (const \fBSbName\fP & partname, \fBSbMatrix\fP & parttolocalmatrix, \fBSbMatrix\fP & localtopartmatrix)"
Returns matrices that will convert between local space and the space in which \fIpartname\fP lies in\&. 
.SS "void SoDragger::transformMatrixLocalToWorld (const \fBSbMatrix\fP & frommatrix, \fBSbMatrix\fP & tomatrix)"
Convenience method that transforms the local \fIfrommatrix\fP to a world coordinate systems matrix\&. 
.SS "void SoDragger::transformMatrixWorldToLocal (const \fBSbMatrix\fP & frommatrix, \fBSbMatrix\fP & tomatrix)"
Convenience method that transforms the world \fIfrommatrix\fP to a local coordinate systems matrix\&. 
.SS "void SoDragger::transformMatrixToLocalSpace (const \fBSbMatrix\fP & frommatrix, \fBSbMatrix\fP & tomatrix, const \fBSbName\fP & fromspacepartname)"
Transforms a matrix that lies in the \fIfrompartname\fP coordinate system into the local coordinate system\&. 
.SS "void SoDragger::setMotionMatrix (const \fBSbMatrix\fP & matrix)\fC [virtual]\fP"
Sets a new current motion matrix for the dragger geometry\&.
.PP
Triggers value changed callbacks if \fImatrix\fP is unequal to the previous motion matrix\&. 
.PP
Reimplemented in \fBSoTranslate2Dragger\fP, and \fBSoTranslate1Dragger\fP\&.
.SS "void SoDragger::valueChanged (void)"
Can be called by subclasses to trigger value changed callbacks\&. This might be needed if a field is changed without changing the motion matrix\&. 
.SS "const \fBSbMatrix\fP & SoDragger::getStartMotionMatrix (void)"
Returns the motion matrix as it was when \fBsaveStartParameters()\fP was called\&. 
.SS "void SoDragger::saveStartParameters (void)\fC [virtual]\fP"
This is invoked to save start parameters, to enable draggers to calculate relative motion\&.
.PP
Default method in superclass \fBSoDragger\fP just saves the motion matrix, but subclasses should overload this method if other data needs to be saved\&. 
.PP
Reimplemented in \fBSoCenterballDragger\fP\&.
.SS "const \fBSoPath\fP * SoDragger::getPickPath (void) const"
Returns the picked path\&. 
.SS "const \fBSoEvent\fP * SoDragger::getEvent (void) const"
Returns the current event\&. 
.SS "\fBSoPath\fP * SoDragger::createPathToThis (void)"
Creates a new path to this dragger\&. Don't forget to \fBref()\fP and \fBunref()\fP since this method creates a fresh copy for you\&. 
.SS "const \fBSoPath\fP * SoDragger::getSurrogatePartPickedOwner (void) const"
Returns the path to the \fBSoInteractionKit\fP that holds the current surrogate path\&. 
.SS "const \fBSbName\fP & SoDragger::getSurrogatePartPickedName (void) const"
Returns the name of the path in the \fBSoInteractionKit\fP that holds the current surrogate path\&. 
.SS "const \fBSoPath\fP * SoDragger::getSurrogatePartPickedPath (void) const"
Returns the current surrogate path\&. 
.SS "void SoDragger::setStartingPoint (const \fBSoPickedPoint\fP * point)"
Sets the staring point for the drag\&. \fIpoint\fP is usually a picked point from a \fBSoRayPickAction\fP\&. 
.SS "void SoDragger::setStartingPoint (const \fBSbVec3f\fP & point)"
Sets the starting point for a drag\&. 
.SS "const \fBSbViewVolume\fP & SoDragger::getViewVolume (void)"
Return the current view volume\&. 
.SS "void SoDragger::setViewVolume (const \fBSbViewVolume\fP & vv)"
Sets the current view volume\&. 
.SS "const \fBSbViewportRegion\fP & SoDragger::getViewportRegion (void)"
Returns the current viewport region\&. 
.SS "void SoDragger::setViewportRegion (const \fBSbViewportRegion\fP & vp)"
Sets the current viewport region\&. 
.SS "\fBSoHandleEventAction\fP * SoDragger::getHandleEventAction (void) const"
Return the current (most recent) \fBSoHandleEventAction\fP\&. 
.SS "void SoDragger::setHandleEventAction (\fBSoHandleEventAction\fP * action)"
Stores a handle event action\&. 
.SS "void SoDragger::setTempPathToThis (const \fBSoPath\fP * somethingclose)"
This function is part of the original SGI Inventor 2\&.1 API, but has not been implemented in Coin as it looks like a function which should probably have been private in Open Inventor\&. 
.SS "void SoDragger::grabEventsSetup (void)\fC [virtual]\fP"
Called when dragger starts grabbing events (mouse button down)\&. Overload if you need to do something extra in your dragger\&. 
.PP
\fBSee also:\fP
.RS 4
grabEventCleanup() 
.RE
.PP

.PP
Reimplemented from \fBSoNode\fP\&.
.SS "void SoDragger::grabEventsCleanup (void)\fC [virtual]\fP"
Called when dragger stops grabbing events (mouse button up)\&. 
.PP
\fBSee also:\fP
.RS 4
grabEventSetup() 
.RE
.PP

.PP
Reimplemented from \fBSoNode\fP\&.
.SS "void SoDragger::workFieldsIntoTransform (\fBSbMatrix\fP & matrix)"
Examines the fields of the dragger, changes the matrix according to those fields and leaves the rest of the matrix as it was\&. The following field names are supported: translation, scaleFactor, rotation and scaleOrientation\&. 
.SS "void SoDragger::setFrontOnProjector (\fBProjectorFrontSetting\fP val)"
Controls the behaviour of the \fBSbProjector\fP\&. 
.SS "\fBSoDragger::ProjectorFrontSetting\fP SoDragger::getFrontOnProjector (void) const"
Returns the behaviour of the \fBSbProjector\fP\&. 
.SS "void SoDragger::setMinScale (float minscalearg)\fC [static]\fP"
Sets the minimum scale value all scale factors are clamped against\&. This is used in \fBworkFieldsIntoTransform()\fP\&. The default value is 0\&.01 
.SS "float SoDragger::getMinScale (void)\fC [static]\fP"
Returns the minimum scale value\&. 
.PP
\fBSee also:\fP
.RS 4
\fBsetMinScale()\fP 
.RE
.PP

.SS "void SoDragger::workValuesIntoTransform (\fBSbMatrix\fP & matrix, const \fBSbVec3f\fP * translationptr, const \fBSbRotation\fP * rotationptr, const \fBSbVec3f\fP * scalefactorptr, const \fBSbRotation\fP * scaleorientationptr, const \fBSbVec3f\fP * centerptr)\fC [static]\fP"
Same as above, but pointers to values are supplied\&. If a pointer is \fCNULL\fP, the matrix value for that argument is used when reconstructing the matrix\&. 
.SS "void SoDragger::getTransformFast (\fBSbMatrix\fP & matrix, \fBSbVec3f\fP & translation, \fBSbRotation\fP & rotation, \fBSbVec3f\fP & scalefactor, \fBSbRotation\fP & scaleorientation, const \fBSbVec3f\fP & center)\fC [static]\fP"
Can be used when there is no scaleorientation\&. Faster than \fBSoDragger::workValuesIntoTransform()\fP\&. 
.SS "void SoDragger::getTransformFast (\fBSbMatrix\fP & matrix, \fBSbVec3f\fP & translation, \fBSbRotation\fP & rotation, \fBSbVec3f\fP & scalefactor, \fBSbRotation\fP & scaleorientation)\fC [static]\fP"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. 
.SS "\fBSbMatrix\fP SoDragger::appendTranslation (const \fBSbMatrix\fP & matrix, const \fBSbVec3f\fP & translation, const \fBSbMatrix\fP * conversion = \fCNULL\fP)\fC [static]\fP"
Returns \fImatrix\fP after \fItranslation\fP has been appended\&. If \fIconversion\fP != \fCNULL\fP it is used to transform \fItranslation\fP into the space \fImatrix\fP is defined\&. 
.SS "\fBSbMatrix\fP SoDragger::appendScale (const \fBSbMatrix\fP & matrix, const \fBSbVec3f\fP & scale, const \fBSbVec3f\fP & scalecenter, const \fBSbMatrix\fP * conversion = \fCNULL\fP)\fC [static]\fP"
Returns \fImatrix\fP after \fIscale\fP and \fIscalecenter\fP has been appended\&. If \fIconversion\fP != \fCNULL\fP it is used to transform scale into the space \fImatrix\fP is defined\&. 
.SS "\fBSbMatrix\fP SoDragger::appendRotation (const \fBSbMatrix\fP & matrix, const \fBSbRotation\fP & rot, const \fBSbVec3f\fP & rotcenter, const \fBSbMatrix\fP * conversion = \fCNULL\fP)\fC [static]\fP"
Appends \fIrot\fP, around \fIrotcenter\fP, to \fImatrix\fP\&. If \fIconversion\fP is != \fCNULL\fP, this is used to move the rotation into that coordinate systems before appending the rotation\&. 
.SS "void SoDragger::initClass (void)\fC [static]\fP"
Initializes type system for this dragger class\&.
.PP
Application programmers should usually not have to invoke this method, see documentation of \fBSoInteraction::init()\fP\&. 
.SS "void SoDragger::initClasses (void)\fC [static]\fP"
Initializes all built-in draggers\&. 
.SS "\fBSbVec2f\fP SoDragger::getNormalizedLocaterPosition (void)\fC [protected]\fP"
Returns the position of the locater\&. 
.SS "\fBSbVec2s\fP SoDragger::getLocaterPosition (void)\fC [protected]\fP"
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. 
.SS "\fBSbVec2s\fP SoDragger::getStartLocaterPosition (void) const\fC [protected]\fP"
Returns the position when mouse button 1 was pressed\&. 
.SS "void SoDragger::setStartLocaterPosition (\fBSbVec2s\fP pos)\fC [protected]\fP"
The start locater position is automatically set when mouse button 1 goes down, but subclasses can use this method to reset the value\&. 
.SS "SbBool SoDragger::isAdequateConstraintMotion (void)\fC [protected]\fP"
Checks if the mouse pointer has been moved enough after the end-user hit a constraint mode key (which is typically \fCSHIFT\fP, sometimes also \fCCTRL\fP for the built-in draggers) that we should act upon and decide which direction the constraint should be set to\&. 
.SS "SbBool SoDragger::shouldGrabBasedOnSurrogate (const \fBSoPath\fP * pickpath, const \fBSoPath\fP * surrogatepath)\fC [protected]\fP, \fC [virtual]\fP"
Checks if \fIpickpath\fP contains \fIsurrogatepath\fP and returns \fCTRUE\fP if the tail of \fIsurrogatepath\fP is before any dragger in \fIpickpath\fP\&. 
.SS "void SoDragger::setCameraInfo (\fBSoAction\fP * action)\fC [protected]\fP"
Store data about the current camera in the given action\&. 
.SS "void SoDragger::handleEvent (\fBSoHandleEventAction\fP * action)\fC [protected]\fP, \fC [virtual]\fP"
Action method for \fBSoHandleEventAction\fP\&.
.PP
Inspects the event data from \fIaction\fP, and processes it if it is something which this node should react to\&.
.PP
Nodes influencing relevant state variables for how event handling is done also overrides this method\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.SS "void SoDragger::transferMotion (\fBSoDragger\fP * child)\fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::setIgnoreInBbox (SbBool val)\fC [protected]\fP"
Sets whether dragger geometry should be ignored when calculating bbox\&. 
.SS "SbBool SoDragger::isIgnoreInBbox (void)\fC [protected]\fP"
Returns whether dragger geometry should be ignored when calculating bbox\&. 
.SS "void SoDragger::getBoundingBox (\fBSoGetBoundingBoxAction\fP * action)\fC [protected]\fP, \fC [virtual]\fP"
Action method for the \fBSoGetBoundingBoxAction\fP\&.
.PP
Calculates bounding box and center coordinates for node and modifies the values of the \fIaction\fP to encompass the bounding box for this node and to shift the center point for the scene more towards the one for this node\&.
.PP
Nodes influencing how geometry nodes calculates their bounding box also overrides this method to change the relevant state variables\&. 
.PP
Reimplemented from \fBSoBaseKit\fP\&.
.PP
Reimplemented in \fBSoCenterballDragger\fP\&.
.SS "void SoDragger::setActiveChildDragger (\fBSoDragger\fP * childdragger)\fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "\fBSoDragger\fP * SoDragger::getActiveChildDragger (void) const\fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::setDefaultOnNonWritingFields (void)\fC [protected]\fP, \fC [virtual]\fP"
(Be aware that this method is unlikely to be of interest to the application programmer who does not want to extend the library with new custom nodekits or draggers\&. If you indeed \fIare\fP writing extensions, see the information in the \fBSoBaseKit\fP class documentation\&.)
.PP
This is a virtual method, and the code in it should call \fBSoField::setDefault()\fP with argument \fCTRUE\fP on part fields that should not be written upon scenegraph export operations\&.
.PP
This is typically done when:
.PP
.PD 0
.IP "1." 4
field value is \fCNULL\fP and part is \fCNULL\fP by default 
.PP

.IP "2." 4
it is a leaf \fBSoGroup\fP or \fBSoSeparator\fP node with no children 
.PP

.IP "3." 4
it is a leaf listpart with no children and an \fBSoGroup\fP or \fBSoSeparator\fP container 
.PP

.IP "4." 4
it is a non-leaf part and it's of \fBSoGroup\fP type and all fields are at their default values 
.PP

.PP
.PP
Subclasses should usually override this to do additional settings for new member fields\&. From the subclass, do remember to call 'upwards' to your superclass' \fBsetDefaultOnNonWritingFields()\fP method\&. 
.PP
Reimplemented from \fBSoInteractionKit\fP\&.
.PP
Reimplemented in \fBSoTransformerDragger\fP, \fBSoHandleBoxDragger\fP, \fBSoDragPointDragger\fP, \fBSoTransformBoxDragger\fP, \fBSoTrackballDragger\fP, \fBSoCenterballDragger\fP, \fBSoTabPlaneDragger\fP, \fBSoTabBoxDragger\fP, \fBSoSpotLightDragger\fP, \fBSoDirectionalLightDragger\fP, \fBSoJackDragger\fP, and \fBSoPointLightDragger\fP\&.
.SS "void SoDragger::childTransferMotionAndValueChangedCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::childValueChangedCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::childStartCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::childMotionCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::childFinishCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::childOtherEventCB (void * data, \fBSoDragger\fP * child)\fC [static]\fP, \fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoDragger::updateDraggerCache (const \fBSoPath\fP * path)\fC [protected]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SH "Member Data Documentation"
.PP 
.SS "\fBSoSFBool\fP SoDragger::isActive"
Is \fCTRUE\fP whenever the user is interacting with the dragger\&. For compound draggers (draggers consisting of one or more subdraggers), the isActive field is updated only for the active subdragger, not for the compound dragger\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
