.TH "SoEngineList" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoEngineList \- The \fBSoEngineList\fP class is a container for \fBSoEngine\fP objects\&.
.PP
As this class inherits \fBSoBaseList\fP, referencing and dereferencing will default be done on the objects at \fBappend()\fP, \fBremove()\fP, \fBinsert()\fP etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/lists/SoEngineList\&.h>\fP
.PP
Inherits \fBSoBaseList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoEngineList\fP (void)"
.br
.ti -1c
.RI "\fBSoEngineList\fP (const \fBint\fP size)"
.br
.ti -1c
.RI "\fBSoEngineList\fP (const \fBSoEngineList\fP &el)"
.br
.ti -1c
.RI "\fB~SoEngineList\fP ()"
.br
.ti -1c
.RI "void \fBappend\fP (\fBSoEngine\fP *const ptr)"
.br
.ti -1c
.RI "\fBSoEngine\fP * \fBoperator[]\fP (const \fBint\fP i) const"
.br
.ti -1c
.RI "\fBSoEngineList\fP & \fBoperator=\fP (const \fBSoEngineList\fP &el)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoEngineList\fP class is a container for \fBSoEngine\fP objects\&.
.PP
As this class inherits \fBSoBaseList\fP, referencing and dereferencing will default be done on the objects at \fBappend()\fP, \fBremove()\fP, \fBinsert()\fP etc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoEngineList::SoEngineList (void)"
Default constructor\&. 
.SS "SoEngineList::SoEngineList (const \fBint\fP size)"
Constructor with a hint about the number of elements the list will hold\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::SoBaseList(const int)\fP 
.RE
.PP

.SS "SoEngineList::SoEngineList (const \fBSoEngineList\fP & el)"
Copy constructor\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::SoBaseList(const SoBaseList &)\fP 
.RE
.PP

.SS "SoEngineList::~SoEngineList ()"
Destructor\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::~SoBaseList()\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void SoEngineList::append (\fBSoEngine\fP *const ptr)"
Append \fIptr\fP to the list\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::append()\fP 
.RE
.PP

.SS "\fBSoEngine\fP * SoEngineList::operator[] (const \fBint\fP i) const"
Return engine pointer at index \fIi\fP\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::operator[]()\fP 
.RE
.PP

.SS "\fBSoEngineList\fP & SoEngineList::operator= (const \fBSoEngineList\fP & el)"
Copy contents of list \fIel\fP to this list\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoBaseList::operator=()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
