.TH "SoExtSelection.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoExtSelection.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoSubNode\&.h>\fP
.br
\fC#include <Inventor/nodes/SoSelection\&.h>\fP
.br
\fC#include <Inventor/fields/SoSFEnum\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <Inventor/actions/SoCallbackAction\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoExtSelection\fP"
.br
.RI "The \fBSoExtSelection\fP class can be used for extended selection functionality\&.
.PP
This class enables you to select geometry by specifying a lasso (a polygon) or a rectangle on screen\&. When objects are selected, you'll receive the same callbacks as for the \fBSoSelection\fP node\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef SbBool \fBSoExtSelectionTriangleCB\fP(void *userdata, \fBSoCallbackAction\fP *action, const \fBSoPrimitiveVertex\fP *v1, const \fBSoPrimitiveVertex\fP *v2, const \fBSoPrimitiveVertex\fP *v3)"
.br
.ti -1c
.RI "typedef SbBool \fBSoExtSelectionLineSegmentCB\fP(void *userdata, \fBSoCallbackAction\fP *action, const \fBSoPrimitiveVertex\fP *v1, const \fBSoPrimitiveVertex\fP *v2)"
.br
.ti -1c
.RI "typedef SbBool \fBSoExtSelectionPointCB\fP(void *userdata, \fBSoCallbackAction\fP *action, const \fBSoPrimitiveVertex\fP *v1)"
.br
.ti -1c
.RI "typedef \fBSoPath\fP * \fBSoLassoSelectionFilterCB\fP(void *userdata, const \fBSoPath\fP *path)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
