.TH "SoFloatElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoFloatElement \- \fBSoFloatElement\fP is an abstract base class for elements that consists of a single float value\&.
.PP
This is the superclass of elements where the new element data \fIreplaces\fP the old data, and where the data the element stores is a simple single precision floating point value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoFloatElement\&.h>\fP
.PP
Inherits \fBSoElement\fP\&.
.PP
Inherited by \fBSoComplexityElement\fP, \fBSoCreaseAngleElement\fP, \fBSoDecimationPercentageElement\fP, \fBSoFocalDistanceElement\fP, \fBSoFontSizeElement\fP, \fBSoLineWidthElement\fP, \fBSoListenerGainElement\fP, \fBSoPointSizeElement\fP, and \fBSoTextureQualityElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual SbBool \fBmatches\fP (const \fBSoElement\fP *element) const"
.br
.ti -1c
.RI "virtual \fBSoElement\fP * \fBcopyMatchInfo\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (FILE *file) const"
.br
.ti -1c
.RI "virtual void \fBsetElt\fP (float value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (const \fBint\fP \fBstackIndex\fP, \fBSoState\fP *const state, \fBSoNode\fP *const node, const float value)"
.br
.ti -1c
.RI "static void \fBset\fP (const \fBint\fP \fBstackIndex\fP, \fBSoState\fP *const state, const float value)"
.br
.ti -1c
.RI "static float \fBget\fP (const \fBint\fP \fBstackIndex\fP, \fBSoState\fP *const state)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoFloatElement\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBdata\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSoFloatElement\fP is an abstract base class for elements that consists of a single float value\&.
.PP
This is the superclass of elements where the new element data \fIreplaces\fP the old data, and where the data the element stores is a simple single precision floating point value\&. 

This element is like a convenient light-weight version of the \fBSoReplacedElement\fP\&. It differs from the \fBSoReplacedElement\fP in that the \fBset()\fP and \fBget()\fP methods are already implemented, since it is known that subclasses will still contain just a single float value\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoReplacedElement\fP, \fBSoInt32Element\fP, \fBSoAccumulatedElement\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoFloatElement::~SoFloatElement (void)\fC [protected]\fP, \fC [virtual]\fP"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SoFloatElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
This function initializes the element type in the given \fBSoState\fP\&. It is called for the first element of each enabled element type in \fBSoState\fP objects\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.PP
Reimplemented in \fBSoGLPointSizeElement\fP, \fBSoFontSizeElement\fP, \fBSoGLLineWidthElement\fP, \fBSoDecimationPercentageElement\fP, \fBSoLineWidthElement\fP, \fBSoPointSizeElement\fP, \fBSoComplexityElement\fP, \fBSoFocalDistanceElement\fP, \fBSoCreaseAngleElement\fP, \fBSoTextureQualityElement\fP, and \fBSoListenerGainElement\fP\&.
.SS "SbBool SoFloatElement::matches (const \fBSoElement\fP * element) const\fC [virtual]\fP"
This function returns \fCTRUE\fP is the element matches another element (of the same class), with respect to cache validity\&.
.PP
If the application programmer's extension element has a \fBmatches()\fP function, it should also have a \fBcopyMatchInfo()\fP function\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "\fBSoElement\fP * SoFloatElement::copyMatchInfo (void) const\fC [virtual]\fP"
This function creates a copy of the element that contains enough information to enable the \fBmatches()\fP function to work\&.
.PP
Used to help with scenegraph traversal caching operations\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "void SoFloatElement::print (FILE * file) const\fC [virtual]\fP"
This function is for printing element information, and is used mostly for debugging purposes\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.SS "void SoFloatElement::set (const \fBint\fP index, \fBSoState\fP *const state, \fBSoNode\fP *const node, const float value)\fC [static]\fP"
Static method for setting the \fIvalue\fP of an element in the given \fIstate\fP at the given stack \fIindex\fP\&. 
.SS "void SoFloatElement::set (const \fBint\fP stackIndex, \fBSoState\fP *const state, const float value)\fC [static]\fP"
Static method for setting the \fIvalue\fP of an element in the given \fIstate\fP at the given \fIstackIndex\fP\&. 
.SS "float SoFloatElement::get (const \fBint\fP index, \fBSoState\fP *const state)\fC [static]\fP"
Static method to fetch the value of the element of this type from the given \fIstate\fP at the given stack \fIindex\fP\&. 
.SS "void SoFloatElement::setElt (float value)\fC [virtual]\fP"
Set element value\&. 
.PP
Reimplemented in \fBSoGLPointSizeElement\fP, and \fBSoGLLineWidthElement\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SoFloatElement::data\fC [protected]\fP"
The element's value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
