.TH "SoGeo" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGeo \- The \fBSoGeo\fP class is used to initialize the geo nodes in Coin, and has some utility geo coordinate functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/misc/SoGeo\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinit\fP (void)"
.br
.ti -1c
.RI "static \fBSbVec3d\fP \fBtoGD\fP (const \fBSbString\fP *originsystem, const \fBint\fP numoriginsys, const \fBSbVec3d\fP &origincoords)"
.br
.ti -1c
.RI "static \fBSbVec3d\fP \fBfromGD\fP (const \fBSbVec3d\fP &gd, const \fBSbString\fP *tosystem, const \fBint\fP numtosys)"
.br
.ti -1c
.RI "static \fBSbDPMatrix\fP \fBcalculateDPTransform\fP (const \fBSbString\fP *originsystem, const \fBint\fP numoriginsys, const \fBSbVec3d\fP &origincoords, const \fBSbString\fP *localsystem, const \fBint\fP numlocalsys, const \fBSbVec3d\fP &localcoords)"
.br
.ti -1c
.RI "static \fBSbMatrix\fP \fBcalculateTransform\fP (const \fBSbString\fP *originsystem, const \fBint\fP numoriginsys, const \fBSbVec3d\fP &origincoords, const \fBSbString\fP *localsystem, const \fBint\fP numlocalsys, const \fBSbVec3d\fP &localcoords)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSoGeo\fP class is used to initialize the geo nodes in Coin, and has some utility geo coordinate functions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
