.TH "SoGLDepthBufferElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLDepthBufferElement \- The \fBSoGLDepthBufferElement\fP controls the OpenGL depth buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoGLDepthBufferElement\&.h>\fP
.PP
Inherits \fBSoDepthBufferElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpush\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpop\fP (\fBSoState\fP *state, const \fBSoElement\fP *prevTopElement)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoGLDepthBufferElement\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetElt\fP (SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoGLDepthBufferElement\fP controls the OpenGL depth buffer\&. 

Be aware that this class is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&. 
.PP
\fBSince:\fP
.RS 4
Coin 3\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoGLDepthBufferElement::~SoGLDepthBufferElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoGLDepthBufferElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoGLDepthBufferElement::initClass (void)\fC [static]\fP"
Initializes the \fBSoGLDepthBufferElement\fP class type\&. 
.SS "void SoGLDepthBufferElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoDepthBufferElement\fP\&.
.SS "void SoGLDepthBufferElement::push (\fBSoState\fP * state)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoDepthBufferElement\fP\&.
.SS "void SoGLDepthBufferElement::pop (\fBSoState\fP * state, const \fBSoElement\fP * prevTopElement)\fC [virtual]\fP"
Internal Coin method\&. 
.PP
Reimplemented from \fBSoDepthBufferElement\fP\&.
.SS "void SoGLDepthBufferElement::setElt (SbBool test, SbBool write, DepthWriteFunction function, \fBSbVec2f\fP range)\fC [protected]\fP, \fC [virtual]\fP"
Set this element's values\&. 
.PP
Reimplemented from \fBSoDepthBufferElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
