.TH "SoGLVBOElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLVBOElement \- The \fBSoGLVBOElement\fP class is used to store VBO state\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoGLVBOElement\&.h>\fP
.PP
Inherits \fBSoElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpush\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBpop\fP (\fBSoState\fP *state, const \fBSoElement\fP *prevtopelement)"
.br
.ti -1c
.RI "virtual SbBool \fBmatches\fP (const \fBSoElement\fP *elt) const"
.br
.ti -1c
.RI "virtual \fBSoElement\fP * \fBcopyMatchInfo\fP (void) const"
.br
.ti -1c
.RI "SoVBO * \fBgetVertexVBO\fP (void) const"
.br
.ti -1c
.RI "SoVBO * \fBgetNormalVBO\fP (void) const"
.br
.ti -1c
.RI "SoVBO * \fBgetColorVBO\fP (void) const"
.br
.ti -1c
.RI "\fBint\fP \fBgetNumTexCoordVBO\fP (void) const"
.br
.ti -1c
.RI "SoVBO * \fBgetTexCoordVBO\fP (const \fBint\fP idx) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static SbBool \fBshouldCreateVBO\fP (\fBSoState\fP *state, const \fBint\fP numdata)"
.br
.ti -1c
.RI "static void \fBsetVertexVBO\fP (\fBSoState\fP *state, SoVBO *vbo)"
.br
.ti -1c
.RI "static void \fBsetNormalVBO\fP (\fBSoState\fP *state, SoVBO *vbo)"
.br
.ti -1c
.RI "static void \fBsetColorVBO\fP (\fBSoState\fP *state, SoVBO *vbo)"
.br
.ti -1c
.RI "static void \fBsetTexCoordVBO\fP (\fBSoState\fP *state, const \fBint\fP unit, SoVBO *vbo)"
.br
.ti -1c
.RI "static const \fBSoGLVBOElement\fP * \fBgetInstance\fP (\fBSoState\fP *state)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSoGLVBOElement\fP (void)"
.br
.ti -1c
.RI "virtual \fB~SoGLVBOElement\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoGLVBOElement\fP * \fBgetElement\fP (\fBSoState\fP *state)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoGLVBOElement\fP class is used to store VBO state\&.
.PP
FIXME: write doc\&. 

Be aware that this class is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoGLVBOElement::SoGLVBOElement (void)\fC [protected]\fP"
The constructor\&. 
.SS "SoGLVBOElement::~SoGLVBOElement ()\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoGLVBOElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoGLVBOElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoMultiTextureCoordinateElement\fP class\&. 
.SS "SbBool SoGLVBOElement::shouldCreateVBO (\fBSoState\fP * state, const \fBint\fP numdata)\fC [static]\fP"
Returns \fITRUE\fP if VBO is supported for the current context, and if numdata is between the limits set for VBO rendering\&. 
.SS "void SoGLVBOElement::setVertexVBO (\fBSoState\fP * state, SoVBO * vbo)\fC [static]\fP"
Sets the vertex VBO\&. 
.SS "void SoGLVBOElement::setNormalVBO (\fBSoState\fP * state, SoVBO * vbo)\fC [static]\fP"
Sets the normal VBO\&. 
.SS "void SoGLVBOElement::setColorVBO (\fBSoState\fP * state, SoVBO * vbo)\fC [static]\fP"
Sets the color VBO\&. 
.SS "void SoGLVBOElement::setTexCoordVBO (\fBSoState\fP * state, const \fBint\fP unit, SoVBO * vbo)\fC [static]\fP"
Sets the texture coordinate VBO\&. 
.SS "const \fBSoGLVBOElement\fP * SoGLVBOElement::getInstance (\fBSoState\fP * state)\fC [static]\fP"
Returns a read-only element instance\&. 
.SS "void SoGLVBOElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
This function initializes the element type in the given \fBSoState\fP\&. It is called for the first element of each enabled element type in \fBSoState\fP objects\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.SS "void SoGLVBOElement::push (\fBSoState\fP * state)\fC [virtual]\fP"
This method is called every time a new element is required in one of the stacks\&. This happens when a writable element is requested, using \fBSoState::getElement()\fP or indirectly \fBSoElement::getElement()\fP, and the depth of the current element is less than the state depth\&.
.PP
Override this method if your element needs to copy data from the previous top of stack\&. The \fBpush()\fP method is called on the new element, and the previous element can be found using \fBSoElement::getNextInStack()\fP\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.SS "void SoGLVBOElement::pop (\fBSoState\fP * state, const \fBSoElement\fP * prevTopElement)\fC [virtual]\fP"
This method is callled when the state is popped, and the depth of the element is bigger than the current state depth\&. \fBpop()\fP is called on the new top of stack, and a pointer to the previous top of stack is passed in \fIprevTopElement\fP\&.
.PP
Override this method if you need to copy some state information from the previous top of stack\&. 
.PP
Reimplemented from \fBSoElement\fP\&.
.SS "SbBool SoGLVBOElement::matches (const \fBSoElement\fP * element) const\fC [virtual]\fP"
This function returns \fCTRUE\fP is the element matches another element (of the same class), with respect to cache validity\&.
.PP
If the application programmer's extension element has a \fBmatches()\fP function, it should also have a \fBcopyMatchInfo()\fP function\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "\fBSoElement\fP * SoGLVBOElement::copyMatchInfo (void) const\fC [virtual]\fP"
This function creates a copy of the element that contains enough information to enable the \fBmatches()\fP function to work\&.
.PP
Used to help with scenegraph traversal caching operations\&. 
.PP
Implements \fBSoElement\fP\&.
.SS "\fBSoGLVBOElement\fP * SoGLVBOElement::getElement (\fBSoState\fP * state)\fC [static]\fP, \fC [protected]\fP"
Returns a writable element instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
