.TH "SoGLProjectionMatrixElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLProjectionMatrixElement \- The \fBSoGLProjectionMatrixElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoGLProjectionMatrixElement\&.h>\fP
.PP
Inherits \fBSoProjectionMatrixElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpop\fP (\fBSoState\fP *state, const \fBSoElement\fP *prevTopElement)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoGLProjectionMatrixElement\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetElt\fP (const \fBSbMatrix\fP &matrix)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoGLProjectionMatrixElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoGLProjectionMatrixElement::~SoGLProjectionMatrixElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoGLProjectionMatrixElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoGLProjectionMatrixElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoGLProjectionMatrixElement\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
