.TH "SoGLCoordinateElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLCoordinateElement \- The \fBSoGLCoordinateElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoGLCoordinateElement\&.h>\fP
.PP
Inherits \fBSoCoordinateElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBSbVec3f\fP * \fBgetPtr3\fP () const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec4f\fP * \fBgetPtr4\fP () const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "void \fBsend\fP (const \fBint\fP index) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoGLCoordinateElement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoGLCoordinateElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoGLCoordinateElement::~SoGLCoordinateElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoGLCoordinateElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoGLCoordinateElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoGLCoordinateElement\fP class\&. 
.SS "void SoGLCoordinateElement::send (const \fBint\fP index) const"
Send coordinates \fIindex\fP to GL\&. Handles both 3D and 4D coordinates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
