.TH "SoGLMultiTextureCoordinateElement::GLUnitData" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLMultiTextureCoordinateElement::GLUnitData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLUnitData\fP (const \fBGLUnitData\fP &org)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SoTexCoordTexgenCB * \fBtexgenCB\fP"
.br
.ti -1c
.RI "void * \fBtexgenData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
