.TH "SoGLLazyElement::GLState" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLLazyElement::GLState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBcachebitmask\fP"
.br
.ti -1c
.RI "uint32_t \fBdiffuse\fP"
.br
.ti -1c
.RI "\fBSbColor\fP \fBambient\fP"
.br
.ti -1c
.RI "\fBSbColor\fP \fBemissive\fP"
.br
.ti -1c
.RI "\fBSbColor\fP \fBspecular\fP"
.br
.ti -1c
.RI "float \fBshininess\fP"
.br
.ti -1c
.RI "int32_t \fBlightmodel\fP"
.br
.ti -1c
.RI "int32_t \fBblending\fP"
.br
.ti -1c
.RI "int32_t \fBblend_sfactor\fP"
.br
.ti -1c
.RI "int32_t \fBblend_dfactor\fP"
.br
.ti -1c
.RI "int32_t \fBalpha_blend_sfactor\fP"
.br
.ti -1c
.RI "int32_t \fBalpha_blend_dfactor\fP"
.br
.ti -1c
.RI "int32_t \fBstipplenum\fP"
.br
.ti -1c
.RI "int32_t \fBvertexordering\fP"
.br
.ti -1c
.RI "int32_t \fBculling\fP"
.br
.ti -1c
.RI "int32_t \fBtwoside\fP"
.br
.ti -1c
.RI "int32_t \fBflatshading\fP"
.br
.ti -1c
.RI "int32_t \fBalphatestfunc\fP"
.br
.ti -1c
.RI "float \fBalphatestvalue\fP"
.br
.ti -1c
.RI "uint32_t \fBdiffusenodeid\fP"
.br
.ti -1c
.RI "uint32_t \fBtranspnodeid\fP"
.br
.ti -1c
.RI "uint32_t \fBreserved\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
