.TH "SoGLDriverDatabase" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoGLDriverDatabase \- The \fBSoGLDriverDatabase\fP class is used for looking up broken/slow features in OpenGL drivers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/misc/SoGLDriverDatabase\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static SbBool \fBisSupported\fP (const cc_glglue *context, const \fBSbName\fP &feature)"
.br
.ti -1c
.RI "static SbBool \fBisBroken\fP (const cc_glglue *context, const \fBSbName\fP &feature)"
.br
.ti -1c
.RI "static SbBool \fBisSlow\fP (const cc_glglue *context, const \fBSbName\fP &feature)"
.br
.ti -1c
.RI "static SbBool \fBisFast\fP (const cc_glglue *context, const \fBSbName\fP &feature)"
.br
.ti -1c
.RI "static \fBSbName\fP \fBgetComment\fP (const cc_glglue *context, const \fBSbName\fP &feature)"
.br
.ti -1c
.RI "static void \fBloadFromBuffer\fP (const char *buffer)"
.br
.ti -1c
.RI "static void \fBloadFromFile\fP (const \fBSbName\fP &filename)"
.br
.ti -1c
.RI "static void \fBaddBuffer\fP (const char *buffer)"
.br
.ti -1c
.RI "static void \fBaddFile\fP (const \fBSbName\fP &filename)"
.br
.ti -1c
.RI "static void \fBaddFeature\fP (const \fBSbName\fP &feature, const \fBSbName\fP &comment)"
.br
.ti -1c
.RI "static void \fBinit\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSoGLDriverDatabase\fP class is used for looking up broken/slow features in OpenGL drivers\&. 

Coin will maintain a database of drivers where we have found problems with certain features, even if the OpenGL driver claims to support it\&. This is an effort to avoid application or operating system crashes when Coin attempts to use a specific feature\&. Using this database we can either disable this feature, or find another way to handle it for broken drivers\&. 
.SH "Member Function Documentation"
.PP 
.SS "SbBool SoGLDriverDatabase::isSupported (const cc_glglue * context, const \fBSbName\fP & feature)\fC [static]\fP"
Convenience function which checks whether \fIfeature\fP is suppported for \fIcontext\fP\&. If \fIfeature\fP is an OpenGL extension, it checks if it's actually supported by the driver, and then calls \fBSoGLDriverDatabase::isBroken()\fP to check if the feature is broken for \fIcontext\fP\&. 
.SS "SbBool SoGLDriverDatabase::isBroken (const cc_glglue * context, const \fBSbName\fP & feature)\fC [static]\fP"
Checks the driver database to see if \fIfeature\fP is tagged as broken\&. 
.SS "SbBool SoGLDriverDatabase::isSlow (const cc_glglue * context, const \fBSbName\fP & feature)\fC [static]\fP"
Checks the driver database to see if \fIfeature\fP is tagged as being slow\&. 
.SS "SbBool SoGLDriverDatabase::isFast (const cc_glglue * context, const \fBSbName\fP & feature)\fC [static]\fP"
Checks the driver database to see if \fIfeature\fP is tagged as fast\&. 
.SS "\fBSbName\fP SoGLDriverDatabase::getComment (const cc_glglue * context, const \fBSbName\fP & feature)\fC [static]\fP"
Get the comment for \fIfeature\fP in \fIcontext\fP, returns 'undefined' if the feature has no entry\&. Provides extensibility to the database\&. 
.SS "void SoGLDriverDatabase::loadFromBuffer (const char * buffer)\fC [static]\fP"
Load the driver database from \fIbuffer\fP 
.SS "void SoGLDriverDatabase::loadFromFile (const \fBSbName\fP & filename)\fC [static]\fP"
Load the driver database from the file specified in \fIfilename\fP 
.SS "void SoGLDriverDatabase::addBuffer (const char * buffer)\fC [static]\fP"
Add the XML data in \fIbuffer\fP to the driver database 
.SS "void SoGLDriverDatabase::addFile (const \fBSbName\fP & filename)\fC [static]\fP"
Add the XML data in \fIfilename\fP to the driver database 
.SS "void SoGLDriverDatabase::addFeature (const \fBSbName\fP & feature, const \fBSbName\fP & comment)\fC [static]\fP"
Add a feature to the driver database 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
