.TH "SoIntersectingPrimitive" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoIntersectingPrimitive \- Struct with collision information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/collision/SoIntersectionDetectionAction\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPrimitiveType\fP { \fBSEGMENT\fP = 2, \fBLINE_SEGMENT\fP = 2, \fBTRIANGLE\fP = 3 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoPath\fP * \fBpath\fP"
.br
.ti -1c
.RI "enum SoIntersectingPrimitive::PrimitiveType \fBtype\fP"
.br
.ti -1c
.RI "\fBSbVec3f\fP \fBvertex\fP [3]"
.br
.ti -1c
.RI "\fBSbVec3f\fP \fBxf_vertex\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct with collision information\&. 

This struct is passed to the collision callback registered by the application programmer\&. It contains information about which primitives are intersecting each other\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
