.TH "SoIntersectionDetectionAction.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoIntersectionDetectionAction.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/tools/SbPimplPtr\&.h>\fP
.br
\fC#include <Inventor/actions/SoSubAction\&.h>\fP
.br
\fC#include <Inventor/actions/SoAction\&.h>\fP
.br
\fC#include <Inventor/actions/SoCallbackAction\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSoIntersectingPrimitive\fP"
.br
.RI "Struct with collision information\&. "
.ti -1c
.RI "class \fBSoIntersectionDetectionAction\fP"
.br
.RI "The \fBSoIntersectionDetectionAction\fP class is for detecting intersecting primitives in a scene\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
