.TH "SoLazyElement::CoinState" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoLazyElement::CoinState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSbColor\fP \fBambient\fP"
.br
.ti -1c
.RI "\fBSbColor\fP \fBspecular\fP"
.br
.ti -1c
.RI "\fBSbColor\fP \fBemissive\fP"
.br
.ti -1c
.RI "float \fBshininess\fP"
.br
.ti -1c
.RI "SbBool \fBblending\fP"
.br
.ti -1c
.RI "\fBint\fP \fBblend_sfactor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBblend_dfactor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBalpha_blend_sfactor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBalpha_blend_dfactor\fP"
.br
.ti -1c
.RI "int32_t \fBlightmodel\fP"
.br
.ti -1c
.RI "SbBool \fBpackeddiffuse\fP"
.br
.ti -1c
.RI "int32_t \fBnumdiffuse\fP"
.br
.ti -1c
.RI "int32_t \fBnumtransp\fP"
.br
.ti -1c
.RI "const \fBSbColor\fP * \fBdiffusearray\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpackedarray\fP"
.br
.ti -1c
.RI "const float * \fBtransparray\fP"
.br
.ti -1c
.RI "const int32_t * \fBcolorindexarray\fP"
.br
.ti -1c
.RI "int32_t \fBtransptype\fP"
.br
.ti -1c
.RI "SbBool \fBistransparent\fP"
.br
.ti -1c
.RI "uint32_t \fBdiffusenodeid\fP"
.br
.ti -1c
.RI "uint32_t \fBtranspnodeid\fP"
.br
.ti -1c
.RI "int32_t \fBstipplenum\fP"
.br
.ti -1c
.RI "VertexOrdering \fBvertexordering\fP"
.br
.ti -1c
.RI "SbBool \fBtwoside\fP"
.br
.ti -1c
.RI "SbBool \fBculling\fP"
.br
.ti -1c
.RI "SbBool \fBflatshading\fP"
.br
.ti -1c
.RI "\fBint\fP \fBalphatestfunc\fP"
.br
.ti -1c
.RI "float \fBalphatestvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
