.TH "SoListenerDopplerElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoListenerDopplerElement \- The \fBSoListenerDopplerElement\fP holds the doppler velocity and factor of the current listener\&.
.PP
The dopplerVelocity and dopplerFactor is set by \fBSoListener\fP nodes during audio rendering\&. The \fBSoListenerDopplerElement\fP is used when the \fBSoVRMLSound\fP nodes render themselves\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoListenerDopplerElement\&.h>\fP
.PP
Inherits \fBSoReplacedElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.ti -1c
.RI "virtual void \fBprint\fP (FILE *file) const"
.br
.RI "Prints the contents of the element (unimplemented) "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBsetDopplerVelocity\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const \fBSbVec3f\fP &velocity)"
.br
.ti -1c
.RI "static void \fBsetDopplerFactor\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, float factor)"
.br
.ti -1c
.RI "static const \fBSbVec3f\fP & \fBgetDopplerVelocity\fP (\fBSoState\fP *const state)"
.br
.RI "Returns the current listener's doppler velocity\&. "
.ti -1c
.RI "static float \fBgetDopplerFactor\fP (\fBSoState\fP *const state)"
.br
.RI "Returns the current listener's doppler factor\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoListenerDopplerElement\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbVec3f\fP \fBdopplerVelocity\fP"
.br
.ti -1c
.RI "float \fBdopplerFactor\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoListenerDopplerElement\fP holds the doppler velocity and factor of the current listener\&.
.PP
The dopplerVelocity and dopplerFactor is set by \fBSoListener\fP nodes during audio rendering\&. The \fBSoListenerDopplerElement\fP is used when the \fBSoVRMLSound\fP nodes render themselves\&. 

Be aware that this class is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoListenerDopplerElement::~SoListenerDopplerElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoListenerDopplerElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoListenerDopplerElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoListenerDopplerElement\fP class\&. 
.SS "void SoListenerDopplerElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
Initializes the element to it's default value\&. The default value for the velocity is (0\&.0f, 0\&.0f, 0\&.0f), in other words, the listener is not moving\&. The default value for the dopplerFactor is 0\&.0f, in other words, doppler effect is disabled\&. 
.PP
Reimplemented from \fBSoReplacedElement\fP\&.
.SS "void SoListenerDopplerElement::setDopplerVelocity (\fBSoState\fP *const state, \fBSoNode\fP *const node, const \fBSbVec3f\fP & velocity)\fC [static]\fP"
Sets the current listener's doppler velocity\&. 
.SS "void SoListenerDopplerElement::setDopplerFactor (\fBSoState\fP *const state, \fBSoNode\fP *const node, float factor)\fC [static]\fP"
Sets the current listener's doppler factor\&. 
.SH "Member Data Documentation"
.PP 
.SS "SoListenerDopplerElement::dopplerVelocity\fC [protected]\fP"
The doppler velocity of the listener\&. It is the application programmer's responsibility to set this value\&. Coin does not update this value automatically based on changes in a listener's position\&. 
.SS "SoListenerDopplerElement::dopplerFactor\fC [protected]\fP"
The amount of doppler effect applied to the listener\&. The normal range would be [0\&.0f to 1\&.0f], where 0\&.0f is default and disable all doppler effects\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
