.TH "SoLineWidthElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoLineWidthElement \- The \fBSoLineWidthElement\fP class changes the linewidth setting of the render state\&.
.PP
Requests from the scenegraph to change the linewidth when rendering line primitives will be made through this element, which forwards it to the appropriate native call in the underlying rendering library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoLineWidthElement\&.h>\fP
.PP
Inherits \fBSoFloatElement\fP\&.
.PP
Inherited by \fBSoGLLineWidthElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const float lineWidth)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, const float lineWidth)"
.br
.ti -1c
.RI "static float \fBget\fP (\fBSoState\fP *const state)"
.br
.ti -1c
.RI "static float \fBgetDefault\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoLineWidthElement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoLineWidthElement\fP class changes the linewidth setting of the render state\&.
.PP
Requests from the scenegraph to change the linewidth when rendering line primitives will be made through this element, which forwards it to the appropriate native call in the underlying rendering library\&. 

Subsequent nodes rendering line primitives will use the width setting (for instance \fBSoLineSet\fP nodes)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoLineWidthElement::~SoLineWidthElement ()\fC [protected]\fP, \fC [virtual]\fP"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoLineWidthElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoLineWidthElement::init (\fBSoState\fP * state)\fC [virtual]\fP"
This function initializes the element type in the given \fBSoState\fP\&. It is called for the first element of each enabled element type in \fBSoState\fP objects\&. 
.PP
Reimplemented from \fBSoFloatElement\fP\&.
.PP
Reimplemented in \fBSoGLLineWidthElement\fP\&.
.SS "void SoLineWidthElement::set (\fBSoState\fP *const state, \fBSoNode\fP *const node, const float lineWidth)\fC [static]\fP"
Set up the current state's \fIlineWidth\fP value\&. 
.SS "void SoLineWidthElement::set (\fBSoState\fP *const state, const float lineWidth)\fC [static]\fP"
Set up the current state's \fIlineWidth\fP value\&. 
.SS "float SoLineWidthElement::get (\fBSoState\fP *const state)\fC [static]\fP"
Returns the current line width value\&. 
.SS "float SoLineWidthElement::getDefault (void)\fC [static]\fP"
Returns the default linewidth value if no value has been set explicitly\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
