.TH "SoMFColor" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoMFColor \- The \fBSoMFColor\fP class is a container for \fBSbColor\fP values\&.
.PP
This field is used where nodes, engines or other field containers needs to store multiple color values (i\&.e\&. 'Red Green Blue' triplets)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/fields/SoMFColor\&.h>\fP
.PP
Inherits \fBSoMField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcopyFrom\fP (const \fBSoField\fP &field)"
.br
.ti -1c
.RI "const \fBSoMFColor\fP & \fBoperator=\fP (const \fBSoMFColor\fP &field)"
.br
.ti -1c
.RI "virtual SbBool \fBisSame\fP (const \fBSoField\fP &field) const"
.br
.ti -1c
.RI "const \fBSbColor\fP & \fBoperator[]\fP (const \fBint\fP idx) const"
.br
.ti -1c
.RI "const \fBSbColor\fP * \fBgetValues\fP (const \fBint\fP start) const"
.br
.ti -1c
.RI "\fBint\fP \fBfind\fP (const \fBSbColor\fP &value, SbBool addifnotfound=FALSE)"
.br
.ti -1c
.RI "void \fBsetValues\fP (const \fBint\fP start, const \fBint\fP \fBnum\fP, const \fBSbColor\fP *newvals)"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, const \fBSbColor\fP &value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbColor\fP &value)"
.br
.ti -1c
.RI "const \fBSbColor\fP & \fBoperator=\fP (const \fBSbColor\fP &val)"
.br
.ti -1c
.RI "SbBool \fBoperator==\fP (const \fBSoMFColor\fP &field) const"
.br
.ti -1c
.RI "SbBool \fBoperator!=\fP (const \fBSoMFColor\fP &field) const"
.br
.ti -1c
.RI "\fBSbColor\fP * \fBstartEditing\fP (void)"
.br
.ti -1c
.RI "void \fBfinishEditing\fP (void)"
.br
.ti -1c
.RI "void \fBsetValuesPointer\fP (const \fBint\fP \fBnum\fP, const float *userdata)"
.br
.ti -1c
.RI "void \fBsetValuesPointer\fP (const \fBint\fP \fBnum\fP, float *userdata)"
.br
.ti -1c
.RI "void \fBsetValuesPointer\fP (const \fBint\fP \fBnum\fP, const \fBSbColor\fP *userdata)"
.br
.ti -1c
.RI "void \fBsetValuesPointer\fP (const \fBint\fP \fBnum\fP, \fBSbColor\fP *userdata)"
.br
.ti -1c
.RI "void \fBsetValues\fP (\fBint\fP start, \fBint\fP \fBnum\fP, const float rgb[][3])"
.br
.ti -1c
.RI "void \fBsetHSVValues\fP (\fBint\fP start, \fBint\fP \fBnum\fP, const float hsv[][3])"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbVec3f\fP &vec)"
.br
.ti -1c
.RI "void \fBsetValue\fP (float r, float g, float b)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const float rgb[3])"
.br
.ti -1c
.RI "void \fBsetHSVValue\fP (float h, float s, float v)"
.br
.ti -1c
.RI "void \fBsetHSVValue\fP (const float hsv[3])"
.br
.ti -1c
.RI "void \fBset1Value\fP (\fBint\fP idx, const \fBSbVec3f\fP &vec)"
.br
.ti -1c
.RI "void \fBset1Value\fP (\fBint\fP idx, float r, float g, float b)"
.br
.ti -1c
.RI "void \fBset1Value\fP (\fBint\fP idx, const float rgb[3])"
.br
.ti -1c
.RI "void \fBset1HSVValue\fP (\fBint\fP idx, float h, float s, float v)"
.br
.ti -1c
.RI "void \fBset1HSVValue\fP (\fBint\fP idx, const float hsv[3])"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdeleteAllValues\fP (void)"
.br
.ti -1c
.RI "virtual void \fBcopyValue\fP (\fBint\fP to, \fBint\fP from)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBfieldSizeof\fP (void) const"
.br
.ti -1c
.RI "virtual void * \fBvaluesPtr\fP (void)"
.br
.ti -1c
.RI "virtual void \fBsetValuesPtr\fP (void *ptr)"
.br
.ti -1c
.RI "virtual void \fBallocValues\fP (\fBint\fP \fBnum\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbColor\fP * \fBvalues\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoMFColor\fP class is a container for \fBSbColor\fP values\&.
.PP
This field is used where nodes, engines or other field containers needs to store multiple color values (i\&.e\&. 'Red Green Blue' triplets)\&. 

This field supports application data sharing through a setValuesPointer() method\&. See \fBSoMField\fP documentation for information on how to use this function\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbColor\fP, \fBSoSFColor\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoMFColor::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification instance which uniquely identifies the Coin field class the object belongs to\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId(), \fBSoType\fP 
.RE
.PP

.PP
Implements \fBSoField\fP\&.
.SS "void SoMFColor::copyFrom (const \fBSoField\fP & f)\fC [virtual]\fP"
Copy value(s) from \fIf\fP into this field\&. \fIf\fP must be of the same type as this field\&. 
.PP
Implements \fBSoField\fP\&.
.SS "SbBool SoMFColor::isSame (const \fBSoField\fP & f) const\fC [virtual]\fP"
Check for equal type and value(s)\&. 
.PP
Implements \fBSoField\fP\&.
.SS "void SoMFColor::deleteAllValues (void)\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.PP
Implements \fBSoMField\fP\&.
.SS "void SoMFColor::copyValue (\fBint\fP to, \fBint\fP from)\fC [protected]\fP, \fC [virtual]\fP"
This method is used for moving values around internally within a multivalue field\&. It needs to be overridden in each field so it automatically takes care of running copy contructors where necessary\&. 
.PP
Implements \fBSoMField\fP\&.
.SS "const \fBSbColor\fP* SoMFColor::getValues (const \fBint\fP start) const\fC [inline]\fP"
\\ Returns a pointer to the values array\&. \\ 
.SS "void SoMFColor::setValues (\fBint\fP start, \fBint\fP numarg, const float rgb[][3])"
Set \fInum\fP RGB color values, starting at index \fIstart\fP\&. 
.SS "void SoMFColor::setHSVValues (\fBint\fP start, \fBint\fP numarg, const float hsv[][3])"
Set \fInum\fP HSV color values, starting at index \fIstart\fP\&. 
.SS "void SoMFColor::setValue (const \fBSbVec3f\fP & vec)"
Set the color array to a single value\&. \fIvec\fP is interpreted as a three element vector with the red, green and blue components, respectively\&. 
.SS "void SoMFColor::setValue (float r, float g, float b)"
Set the color array to a single value\&. \fIr\fP, \fIg\fP and \fIb\fP are the red, green and blue components, respectively\&. 
.SS "void SoMFColor::setValue (const float rgb[3])"
Set the color array to a single value\&. \fIrgb\fP is a three element vector with the red, green and blue components, respectively\&. 
.SS "void SoMFColor::setHSVValue (float h, float s, float v)"
Set the color array to a single value\&. \fIh\fP, \fIs\fP and \fIv\fP are the hue, saturation and value components, respectively\&. 
.SS "void SoMFColor::setHSVValue (const float hsv[3])"
Set the color array to a single value\&. \fIhsv\fP is a three element vector with the hue, saturation and value components, respectively\&. 
.SS "void SoMFColor::set1Value (\fBint\fP idx, const \fBSbVec3f\fP & vec)"
Set the color at \fIidx\fP\&. \fIvec\fP is interpreted as a three element vector with the red, green and blue components, respectively\&. 
.SS "void SoMFColor::set1Value (\fBint\fP idx, float r, float g, float b)"
Set the color at \fIidx\fP\&. \fIr\fP, \fIg\fP and \fIb\fP is the red, green and blue components, respectively\&. 
.SS "void SoMFColor::set1Value (\fBint\fP idx, const float rgb[3])"
Set the color at \fIidx\fP\&. \fIrgb\fP is interpreted as a three element vector with the red, green and blue components, respectively\&. 
.SS "void SoMFColor::set1HSVValue (\fBint\fP idx, float h, float s, float v)"
Set the color at \fIidx\fP\&. \fIh\fP, \fIs\fP and \fIv\fP is the hue, saturation and value components, respectively\&. 
.SS "void SoMFColor::set1HSVValue (\fBint\fP idx, const float hsv[3])"
Set the color at \fIidx\fP\&. \fIhsv\fP is a three element vector with the hue, saturation and value components, respectively\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
