.TH "SoMFRotation" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoMFRotation \- The \fBSoMFRotation\fP class is a container for \fBSbRotation\fP values\&.
.PP
This field is used where nodes, engines or other field containers needs to store multiple rotation definitions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/fields/SoMFRotation\&.h>\fP
.PP
Inherits \fBSoMField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcopyFrom\fP (const \fBSoField\fP &field)"
.br
.ti -1c
.RI "const \fBSoMFRotation\fP & \fBoperator=\fP (const \fBSoMFRotation\fP &field)"
.br
.ti -1c
.RI "virtual SbBool \fBisSame\fP (const \fBSoField\fP &field) const"
.br
.ti -1c
.RI "const \fBSbRotation\fP & \fBoperator[]\fP (const \fBint\fP idx) const"
.br
.ti -1c
.RI "const \fBSbRotation\fP * \fBgetValues\fP (const \fBint\fP start) const"
.br
.ti -1c
.RI "\fBint\fP \fBfind\fP (const \fBSbRotation\fP &value, SbBool addifnotfound=FALSE)"
.br
.ti -1c
.RI "void \fBsetValues\fP (const \fBint\fP start, const \fBint\fP \fBnum\fP, const \fBSbRotation\fP *newvals)"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, const \fBSbRotation\fP &value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbRotation\fP &value)"
.br
.ti -1c
.RI "const \fBSbRotation\fP & \fBoperator=\fP (const \fBSbRotation\fP &val)"
.br
.ti -1c
.RI "SbBool \fBoperator==\fP (const \fBSoMFRotation\fP &field) const"
.br
.ti -1c
.RI "SbBool \fBoperator!=\fP (const \fBSoMFRotation\fP &field) const"
.br
.ti -1c
.RI "\fBSbRotation\fP * \fBstartEditing\fP (void)"
.br
.ti -1c
.RI "void \fBfinishEditing\fP (void)"
.br
.ti -1c
.RI "void \fBsetValues\fP (const \fBint\fP start, const \fBint\fP \fBnum\fP, const float q[][4])"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, const float q0, const float q1, const float q2, const float q3)"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, const float q[4])"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, const \fBSbVec3f\fP &axis, const float angle)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const float q0, const float q1, const float q2, const float q3)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const float q[4])"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbVec3f\fP &axis, const float angle)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdeleteAllValues\fP (void)"
.br
.ti -1c
.RI "virtual void \fBcopyValue\fP (\fBint\fP to, \fBint\fP from)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBfieldSizeof\fP (void) const"
.br
.ti -1c
.RI "virtual void * \fBvaluesPtr\fP (void)"
.br
.ti -1c
.RI "virtual void \fBsetValuesPtr\fP (void *ptr)"
.br
.ti -1c
.RI "virtual void \fBallocValues\fP (\fBint\fP \fBnum\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbRotation\fP * \fBvalues\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoMFRotation\fP class is a container for \fBSbRotation\fP values\&.
.PP
This field is used where nodes, engines or other field containers needs to store multiple rotation definitions\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSoSFRotation\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoMFRotation::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification instance which uniquely identifies the Coin field class the object belongs to\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId(), \fBSoType\fP 
.RE
.PP

.PP
Implements \fBSoField\fP\&.
.SS "void SoMFRotation::copyFrom (const \fBSoField\fP & f)\fC [virtual]\fP"
Copy value(s) from \fIf\fP into this field\&. \fIf\fP must be of the same type as this field\&. 
.PP
Implements \fBSoField\fP\&.
.SS "SbBool SoMFRotation::isSame (const \fBSoField\fP & f) const\fC [virtual]\fP"
Check for equal type and value(s)\&. 
.PP
Implements \fBSoField\fP\&.
.SS "void SoMFRotation::deleteAllValues (void)\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.PP
Implements \fBSoMField\fP\&.
.SS "void SoMFRotation::copyValue (\fBint\fP to, \fBint\fP from)\fC [protected]\fP, \fC [virtual]\fP"
This method is used for moving values around internally within a multivalue field\&. It needs to be overridden in each field so it automatically takes care of running copy contructors where necessary\&. 
.PP
Implements \fBSoMField\fP\&.
.SS "const \fBSbRotation\fP* SoMFRotation::getValues (const \fBint\fP start) const\fC [inline]\fP"
\\ Returns a pointer to the values array\&. \\ 
.SS "void SoMFRotation::setValues (const \fBint\fP start, const \fBint\fP numarg, const float q[][4])"
Set the values of \fInum\fP rotations, starting from index \fIstart\fP, using the quaternion quadruples from \fIq\fP\&. 
.SS "void SoMFRotation::set1Value (const \fBint\fP idx, const float q0, const float q1, const float q2, const float q3)"
Set the rotation at \fIidx\fP from the quaternion values\&. 
.SS "void SoMFRotation::set1Value (const \fBint\fP idx, const float q[4])"
Set the rotation at \fIidx\fP from the quaternion quadruple \fIq\fP\&. 
.SS "void SoMFRotation::set1Value (const \fBint\fP idx, const \fBSbVec3f\fP & axis, const float angle)"
Set the rotation at \fIidx\fP from the rotation \fIaxis\fP and \fIangle\fP\&. 
.SS "void SoMFRotation::setValue (const float q0, const float q1, const float q2, const float q3)"
Set the field to a single rotation from the quaternion values\&. 
.SS "void SoMFRotation::setValue (const float q[4])"
Set the field to a single rotation from the quaternion quadruple \fIq\fP\&. 
.SS "void SoMFRotation::setValue (const \fBSbVec3f\fP & axis, const float angle)"
Set the field to a single rotation from the \fIaxis\fP and \fIangle\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
