.TH "SoMFPath" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoMFPath \- The \fBSoMFPath\fP class is a container for paths\&.
.PP
This field container stores an array of pointers to paths\&. It takes care of the necessary functionality for handling copy, import and export operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/fields/SoMFPath\&.h>\fP
.PP
Inherits \fBSoMField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcopyFrom\fP (const \fBSoField\fP &field)"
.br
.ti -1c
.RI "const \fBSoMFPath\fP & \fBoperator=\fP (const \fBSoMFPath\fP &field)"
.br
.ti -1c
.RI "virtual SbBool \fBisSame\fP (const \fBSoField\fP &field) const"
.br
.ti -1c
.RI "\fBSoPath\fP * \fBoperator[]\fP (const \fBint\fP idx) const"
.br
.ti -1c
.RI "const \fBSoPath\fP ** \fBgetValues\fP (const \fBint\fP start) const"
.br
.ti -1c
.RI "\fBint\fP \fBfind\fP (\fBSoPath\fP *value, SbBool addifnotfound=FALSE)"
.br
.ti -1c
.RI "void \fBsetValues\fP (const \fBint\fP start, const \fBint\fP \fBnum\fP, const \fBSoPath\fP **newvals)"
.br
.ti -1c
.RI "void \fBset1Value\fP (const \fBint\fP idx, \fBSoPath\fP *value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (\fBSoPath\fP *value)"
.br
.ti -1c
.RI "\fBSoPath\fP * \fBoperator=\fP (\fBSoPath\fP *val)"
.br
.ti -1c
.RI "SbBool \fBoperator==\fP (const \fBSoMFPath\fP &field) const"
.br
.ti -1c
.RI "SbBool \fBoperator!=\fP (const \fBSoMFPath\fP &field) const"
.br
.ti -1c
.RI "\fBSoPath\fP ** \fBstartEditing\fP (void)"
.br
.ti -1c
.RI "void \fBfinishEditing\fP (void)"
.br
.ti -1c
.RI "virtual void \fBnotify\fP (\fBSoNotList\fP *l)"
.br
.ti -1c
.RI "virtual void \fBfixCopy\fP (SbBool copyconnections)"
.br
.ti -1c
.RI "virtual SbBool \fBreferencesCopy\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBdeleteValues\fP (\fBint\fP start, \fBint\fP \fBnum\fP=\-1)"
.br
.ti -1c
.RI "virtual void \fBinsertSpace\fP (\fBint\fP start, \fBint\fP \fBnum\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdeleteAllValues\fP (void)"
.br
.ti -1c
.RI "virtual void \fBcopyValue\fP (\fBint\fP to, \fBint\fP from)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBfieldSizeof\fP (void) const"
.br
.ti -1c
.RI "virtual void * \fBvaluesPtr\fP (void)"
.br
.ti -1c
.RI "virtual void \fBsetValuesPtr\fP (void *ptr)"
.br
.ti -1c
.RI "virtual void \fBallocValues\fP (\fBint\fP \fBnum\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSoPath\fP ** \fBvalues\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoMFPath\fP class is a container for paths\&.
.PP
This field container stores an array of pointers to paths\&. It takes care of the necessary functionality for handling copy, import and export operations\&. 

Note that path pointers stored in field instances of this type may be \fCNULL\fP pointers\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoPath\fP, \fBSoSFPath\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoMFPath::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification instance which uniquely identifies the Coin field class the object belongs to\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId(), \fBSoType\fP 
.RE
.PP

.PP
Implements \fBSoField\fP\&.
.SS "void SoMFPath::copyFrom (const \fBSoField\fP & f)\fC [virtual]\fP"
Copy value(s) from \fIf\fP into this field\&. \fIf\fP must be of the same type as this field\&. 
.PP
Implements \fBSoField\fP\&.
.SS "SbBool SoMFPath::isSame (const \fBSoField\fP & f) const\fC [virtual]\fP"
Check for equal type and value(s)\&. 
.PP
Implements \fBSoField\fP\&.
.SS "const \fBSoPath\fP* * SoMFPath::getValues (const \fBint\fP start) const\fC [inline]\fP"
\\ Returns a pointer to the values array\&. \\ 
.SS "void SoMFPath::notify (\fBSoNotList\fP * nlist)\fC [virtual]\fP"
Notify auditors that this field has changed\&. 
.PP
Reimplemented from \fBSoField\fP\&.
.SS "void SoMFPath::fixCopy (SbBool copyconnections)\fC [virtual]\fP"
This method is internally called after \fBSoField::copyFrom()\fP during scene graph copies, and should do the operations necessary for fixing up the field instance after it has gotten a new value\&.
.PP
The default method in the \fBSoField\fP superclass does nothing\&.
.PP
The application programmer should normally not need to consider this method, unless he constructs a complex field type which contains new references to container instances (i\&.e\&. nodes or engines)\&. Overriding this method is then necessary to update the reference pointers, as they could have been duplicated during the copy operation\&. 
.PP
Reimplemented from \fBSoField\fP\&.
.SS "SbBool SoMFPath::referencesCopy (void) const\fC [virtual]\fP"
Returns \fCTRUE\fP if this field has references to any containers in the scene graph which are also duplicated during the copy operation\&.
.PP
Note that this method \fIonly\fP is valid to call during copy operations\&.
.PP
See also the note about the relevance of the \fBfixCopy()\fP method for application programmers, as it is applicable on this method aswell\&. 
.PP
Reimplemented from \fBSoField\fP\&.
.SS "virtual void SoMFPath::deleteValues (\fBint\fP start, \fBint\fP numarg = \fC\-1\fP)\fC [virtual]\fP"
Remove value elements from index \fIstart\fP up to and including index \fIstart\fP + \fInum\fP - 1\&.
.PP
Elements with indices larger than the last deleted element will be moved downwards in the value array\&.
.PP
If \fInum\fP equals -1, delete from index \fIstart\fP and to the end of the array\&. 
.PP
Reimplemented from \fBSoMField\fP\&.
.SS "virtual void SoMFPath::insertSpace (\fBint\fP start, \fBint\fP numarg)\fC [virtual]\fP"
Insert \fInum\fP 'slots' for new value elements from \fIstart\fP\&. The elements already present from \fIstart\fP will be moved 'upward' in the extended array\&. 
.PP
Reimplemented from \fBSoMField\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
