.TH "SoMultiTextureCoordinateElement::UnitData" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoMultiTextureCoordinateElement::UnitData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitData\fP (const \fBUnitData\fP &org)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnodeid\fP"
.br
.ti -1c
.RI "CoordType \fBwhatKind\fP"
.br
.ti -1c
.RI "SoTextureCoordinateFunctionCB * \fBfuncCB\fP"
.br
.ti -1c
.RI "void * \fBfuncCBData\fP"
.br
.ti -1c
.RI "int32_t \fBnumCoords\fP"
.br
.ti -1c
.RI "const \fBSbVec2f\fP * \fBcoords2\fP"
.br
.ti -1c
.RI "const \fBSbVec3f\fP * \fBcoords3\fP"
.br
.ti -1c
.RI "const \fBSbVec4f\fP * \fBcoords4\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcoordsDimension\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
