.TH "SoMultiTextureMatrixElement::UnitData" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoMultiTextureMatrixElement::UnitData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitData\fP (const \fBUnitData\fP &org)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSbMatrix\fP \fBtextureMatrix\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
