.TH "SoNotList" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoNotList \- The \fBSoNotList\fP class is a list of \fBSoNotRec\fP notification records\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/misc/SoNotification\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoNotList\fP (void)"
.br
.ti -1c
.RI "\fBSoNotList\fP (const \fBSoNotList\fP *nl)"
.br
.ti -1c
.RI "void \fBappend\fP (\fBSoNotRec\fP *const rec)"
.br
.ti -1c
.RI "void \fBappend\fP (\fBSoNotRec\fP *const rec, \fBSoField\fP *const field)"
.br
.ti -1c
.RI "void \fBappend\fP (\fBSoNotRec\fP *const rec, \fBSoEngineOutput\fP *const engineout)"
.br
.ti -1c
.RI "void \fBsetLastType\fP (const \fBSoNotRec::Type\fP type)"
.br
.ti -1c
.RI "\fBSoNotRec\fP * \fBgetFirstRec\fP (void) const"
.br
.ti -1c
.RI "\fBSoNotRec\fP * \fBgetLastRec\fP (void) const"
.br
.ti -1c
.RI "\fBSoNotRec\fP * \fBgetFirstRecAtNode\fP (void) const"
.br
.ti -1c
.RI "\fBSoField\fP * \fBgetLastField\fP (void) const"
.br
.ti -1c
.RI "\fBSoEngineOutput\fP * \fBgetLastEngineOutput\fP (void) const"
.br
.ti -1c
.RI "uint32_t \fBgetTimeStamp\fP (void) const"
.br
.ti -1c
.RI "void \fBprint\fP (FILE *const file=stdout) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSoNotList\fP class is a list of \fBSoNotRec\fP notification records\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoNotList::SoNotList (void)"
Initialize list\&. 
.SS "SoNotList::SoNotList (const \fBSoNotList\fP * nl)"
Copy constructor\&. Does a bitwise copy of the \fInl\fP object (no duplication of list elements)\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SoNotList::append (\fBSoNotRec\fP *const rec)"
Append \fIrec\fP notification source to the list\&. 
.SS "void SoNotList::append (\fBSoNotRec\fP *const rec, \fBSoField\fP *const field)"
Append \fIrec\fP notification source to the list, setting \fIfield\fP as the last field having been influenced by the notification process\&. 
.SS "void SoNotList::append (\fBSoNotRec\fP *const rec, \fBSoEngineOutput\fP *const engineout)"
Append \fIrec\fP notification source to the list, setting \fIengineout\fP as the last engine output field having been influenced by the notification process\&. 
.SS "void SoNotList::setLastType (const \fBSoNotRec::Type\fP type)"
Set the \fItype\fP of the last notification record in the list\&. 
.SS "\fBSoNotRec\fP * SoNotList::getFirstRec (void) const"
Returns the first record in the list\&. 
.SS "\fBSoNotRec\fP * SoNotList::getLastRec (void) const"
Returns the last record in the list\&. 
.SS "\fBSoNotRec\fP * SoNotList::getFirstRecAtNode (void) const"
Returns the first record in the list which is derived from \fBSoBase\fP\&. 
.SS "\fBSoField\fP * SoNotList::getLastField (void) const"
Returns the last field touched by notification\&. 
.SS "\fBSoEngineOutput\fP * SoNotList::getLastEngineOutput (void) const"
Returns the last engine output field touched by notification\&. 
.SS "uint32_t SoNotList::getTimeStamp (void) const"
Returns the time stamp when the notification started\&. 
.SS "void SoNotList::print (FILE *const file = \fCstdout\fP) const"
Dump contents of list from tail record and backwards\&. Only available if compiled with debug information on\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
