.TH "SoNormalElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoNormalElement \- The \fBSoNormalElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoNormalElement\&.h>\fP
.PP
Inherits \fBSoReplacedElement\fP\&.
.PP
Inherited by \fBSoGLNormalElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "int32_t \fBgetNum\fP (void) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec3f\fP & \fBget\fP (const \fBint\fP index) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "const \fBSbVec3f\fP * \fBgetArrayPtr\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBareNormalsUnitLength\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const int32_t \fBnumNormals\fP, const \fBSbVec3f\fP *const \fBnormals\fP, const SbBool normalsAreUnitLength=FALSE)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static const \fBSoNormalElement\fP * \fBgetInstance\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoNormalElement\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBnumNormals\fP"
.br
.ti -1c
.RI "const \fBSbVec3f\fP * \fBnormals\fP"
.br
.ti -1c
.RI "SbBool \fBunitLength\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoNormalElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoNormalElement::~SoNormalElement ()\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoNormalElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoNormalElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoNormalElement\fP class\&. 
.SS "const \fBSbVec3f\fP * SoNormalElement::getArrayPtr (void) const"
Returns a pointer to the normal array\&. This method is not part of the OIV API\&. 
.SH "Member Data Documentation"
.PP 
.SS "SoNormalElement::numNormals\fC [protected]\fP"
FIXME: write doc\&. 
.SS "SoNormalElement::normals\fC [protected]\fP"
FIXME: write doc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
