.TH "SoOnOff" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoOnOff \- The \fBSoOnOff\fP engine is a simple on/off switch\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/engines/SoOnOff\&.h>\fP
.PP
Inherits \fBSoEngine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "virtual const \fBSoFieldData\fP * \fBgetFieldData\fP (void) const"
.br
.ti -1c
.RI "virtual const \fBSoEngineOutputData\fP * \fBgetOutputData\fP (void) const"
.br
.ti -1c
.RI "\fBSoOnOff\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoSFTrigger\fP \fBon\fP"
.br
.ti -1c
.RI "\fBSoSFTrigger\fP \fBoff\fP"
.br
.ti -1c
.RI "\fBSoSFTrigger\fP \fBtoggle\fP"
.br
.ti -1c
.RI "\fBSoEngineOutput\fP \fBisOn\fP"
.br
.ti -1c
.RI "\fBSoEngineOutput\fP \fBisOff\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoOnOff\fP (void)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static const \fBSoFieldData\fP ** \fBgetInputDataPtr\fP (void)"
.br
.ti -1c
.RI "static const \fBSoEngineOutputData\fP ** \fBgetOutputDataPtr\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoOnOff\fP engine is a simple on/off switch\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoOnOff::SoOnOff (void)"
Default constructor\&. 
.SS "SoOnOff::~SoOnOff (void)\fC [protected]\fP, \fC [virtual]\fP"
Destructor is protected because engines are reference counted\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoOnOff::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. Usage example:
.PP
.PP
.nf
void foo(SoNode * node)
{
  if (node->getTypeId() == SoFile::getClassTypeId()) {
    SoFile * filenode = (SoFile *)node;  // safe downward cast, knows the type
  }
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new nodes, engines, nodekits, draggers or others: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through for instance \fBInventor/nodes/SoSubNode\&.h\fP (SO_NODE_INIT_CLASS and SO_NODE_CONSTRUCTOR for node classes), \fBInventor/engines/SoSubEngine\&.h\fP (for engine classes) and so on\&.
.PP
For more information on writing Coin extensions, see the class documentation of the toplevel superclasses for the various class groups\&. 
.PP
Implements \fBSoBase\fP\&.
.SS "const \fBSoFieldData\fP * SoOnOff::getFieldData (void) const\fC [virtual]\fP"
Returns a pointer to the class-wide field data storage object for this instance\&. If no fields are present, returns \fCNULL\fP\&. 
.PP
Reimplemented from \fBSoFieldContainer\fP\&.
.SS "const \fBSoEngineOutputData\fP * SoOnOff::getOutputData (void) const\fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.PP
Implements \fBSoEngine\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSoSFTrigger\fP SoOnOff::on"
An input signal on this trigger makes the \fBSoOnOff::isOn\fP output become \fCTRUE\fP\&. 
.SS "\fBSoSFTrigger\fP SoOnOff::off"
An input signal on this trigger makes the \fBSoOnOff::isOn\fP output become \fCFALSE\fP\&. 
.SS "\fBSoSFTrigger\fP SoOnOff::toggle"
An input signal on this trigger toggles the \fCTRUE\fP or \fCFALSE\fP value of the \fBSoOnOff::isOn\fP output\&. 
.SS "\fBSoEngineOutput\fP SoOnOff::isOn"
(\fBSoSFBool\fP) Whether the engine is 'on' or not\&. 
.SS "\fBSoEngineOutput\fP SoOnOff::isOff"
(\fBSoSFBool\fP) Always the opposite value of \fBSoOnOff::isOn\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
