.TH "SoProto.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoProto.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoNode\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoProto\fP"
.br
.RI "The \fBSoProto\fP class handles PROTO definitions\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSoProto\fP * \fBSoFetchExternProtoCB\fP(\fBSoInput\fP *in, const \fBSbString\fP *urls, const \fBint\fP numurls, void *closure)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
