.TH "SoProjectionMatrixElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoProjectionMatrixElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSoReplacedElement\fP\&.
.PP
Inherited by \fBSoGLProjectionMatrixElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const \fBSbMatrix\fP &matrix)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static const \fBSbMatrix\fP & \fBget\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoProjectionMatrixElement\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetElt\fP (\fBSbMatrix\fP const &matrix)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbMatrix\fP \fBprojectionMatrix\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoProjectionMatrixElement::~SoProjectionMatrixElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoProjectionMatrixElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoProjectionMatrixElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoProjectionMatrixElement\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
