.TH "SoProfilingReportGenerator" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoProfilingReportGenerator \- Convenience report generator functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Profiler/tools/SoProfilingReportGenerator\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumn\fP { \fBNAME\fP, \fBTYPE\fP, \fBCOUNT\fP, \fBTIME_SECS\fP, \fBTIME_SECS_MAX\fP, \fBTIME_SECS_AVG\fP, \fBTIME_MSECS\fP, \fBTIME_MSECS_MAX\fP, \fBTIME_MSECS_AVG\fP, \fBTIME_PERCENT\fP, \fBTIME_PERCENT_MAX\fP, \fBTIME_PERCENT_AVG\fP, \fBMEM_BYTES\fP, \fBMEM_KILOBYTES\fP, \fBGFX_MEM_BYTES\fP, \fBGFX_MEM_KILOBYTES\fP }"
.br
.ti -1c
.RI "enum \fBSortOrder\fP { \fBTIME_ASC\fP, \fBTIME_DES\fP, \fBTIME_MAX_ASC\fP, \fBTIME_MAX_DES\fP, \fBTIME_AVG_ASC\fP, \fBTIME_AVG_DES\fP, \fBCOUNT_ASC\fP, \fBCOUNT_DES\fP, \fBALPHANUMERIC_ASC\fP, \fBALPHANUMERIC_DES\fP, \fBMEM_ASC\fP, \fBMEM_DES\fP, \fBGFX_MEM_ASC\fP, \fBGFX_MEM_DES\fP }"
.br
.ti -1c
.RI "enum \fBDataCategorization\fP { \fBTYPES\fP, \fBNAMES\fP, \fBNODES\fP }"
.br
.ti -1c
.RI "enum \fBCallbackResponse\fP { \fBCONTINUE\fP, \fBSTOP\fP }"
.br
.ti -1c
.RI "typedef CallbackResponse \fBReportCB\fP(void *userdata, \fBint\fP entrynum, const char *text)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinit\fP (void)"
.br
.ti -1c
.RI "static SbProfilingReportSortCriteria * \fBgetReportSortCriteria\fP (const \fBSbList\fP< SortOrder > &order)"
.br
.ti -1c
.RI "static SbProfilingReportSortCriteria * \fBgetDefaultReportSortCriteria\fP (DataCategorization category)"
.br
.ti -1c
.RI "static SbProfilingReportPrintCriteria * \fBgetReportPrintCriteria\fP (const \fBSbList\fP< Column > &order)"
.br
.ti -1c
.RI "static SbProfilingReportPrintCriteria * \fBgetDefaultReportPrintCriteria\fP (DataCategorization category)"
.br
.ti -1c
.RI "static void \fBfreeCriteria\fP (SbProfilingReportSortCriteria *criteria)"
.br
.ti -1c
.RI "static void \fBfreeCriteria\fP (SbProfilingReportPrintCriteria *criteria)"
.br
.ti -1c
.RI "static void \fBgenerate\fP (const \fBSbProfilingData\fP &data, DataCategorization categorization, SbProfilingReportSortCriteria *sort, SbProfilingReportPrintCriteria *print, \fBint\fP count, SbBool addheader, ReportCB *reportcallback, void *userdata)"
.br
.ti -1c
.RI "static CallbackResponse \fBstdoutCB\fP (void *userdata, \fBint\fP entrynum, const char *text)"
.br
.ti -1c
.RI "static CallbackResponse \fBstderrCB\fP (void *userdata, \fBint\fP entrynum, const char *text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience report generator functionality\&. 

With this static class, you can conveniently produce a profiling data report from an \fBSbProfilingData\fP object\&.
.PP
\fBSince:\fP
.RS 4
Coin 3\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void SoProfilingReportGenerator::init (void)\fC [static]\fP"
Allocate mutexes and other such infrastructure constructs needed by the report generator\&. 
.SS "SbProfilingReportSortCriteria * SoProfilingReportGenerator::getReportSortCriteria (const \fBSbList\fP< SortOrder > & order)\fC [static]\fP"
Returns a sorting criteria setting object that will make \fBgenerate()\fP sort the results based on the given argument list in that left-to-right priority order\&.
.PP
Always end the argument list with TERMINATE_ARGLIST\&.
.PP
\fBSee also:\fP
.RS 4
freeCriteria 
.RE
.PP

.SS "SbProfilingReportSortCriteria * SoProfilingReportGenerator::getDefaultReportSortCriteria (DataCategorization category)\fC [static]\fP"
Returns a sensible default that can be used for a given profiling data categorization\&. 
.SS "SbProfilingReportPrintCriteria * SoProfilingReportGenerator::getReportPrintCriteria (const \fBSbList\fP< Column > & order)\fC [static]\fP"
Returns a printing criteria setting object that will make \fBgenerate()\fP send a formatted string as the text argument based on the given argument list\&. If you force TERMINATE_ARGLIST into the first argument, the text string will be empty\&.
.PP
Always end the argument list with TERMINATE_ARGLIST\&.
.PP
\fBSee also:\fP
.RS 4
freeCriteria 
.RE
.PP

.SS "SbProfilingReportPrintCriteria * SoProfilingReportGenerator::getDefaultReportPrintCriteria (DataCategorization category)\fC [static]\fP"
Returns a default printing criteria object that can be used sensibly with the given profiling data categorization\&. 
.SS "void SoProfilingReportGenerator::generate (const \fBSbProfilingData\fP & data, DataCategorization categorization, SbProfilingReportSortCriteria * sort, SbProfilingReportPrintCriteria * print, \fBint\fP count, SbBool addheader, ReportCB * reportcallback, void * userdata)\fC [static]\fP"
Generate a sorted, formatted report, by calling a callback until the number of entries are exhausted or the callback returns STOP\&. 
.SS "SoProfilingReportGenerator::CallbackResponse SoProfilingReportGenerator::stdoutCB (void * userdata, \fBint\fP entryidx, const char * text)\fC [static]\fP"
Ready-made callback that can be used with \fBgenerate()\fP to print to stdout\&.
.PP
\fBSee also:\fP
.RS 4
\fBgenerate\fP 
.RE
.PP

.SS "SoProfilingReportGenerator::CallbackResponse SoProfilingReportGenerator::stderrCB (void * userdata, \fBint\fP entryidx, const char * text)\fC [static]\fP"
Ready-made callback that can be used with \fBgenerate()\fP to print to stderr\&.
.PP
\fBSee also:\fP
.RS 4
\fBgenerate\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
