.TH "SoPSVectorOutput" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoPSVectorOutput \- The \fBSoPSVectorOutput\fP class is used for writing Postscript\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/Annex/HardCopy/SoPSVectorOutput\&.h>\fP
.PP
Inherits \fBSoVectorOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoPSVectorOutput\fP ()"
.br
.ti -1c
.RI "virtual \fB~SoPSVectorOutput\fP ()"
.br
.ti -1c
.RI "void \fBsetColored\fP (SbBool flag=TRUE)"
.br
.ti -1c
.RI "SbBool \fBgetColored\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSoPSVectorOutput\fP class is used for writing Postscript\&. 


.PP
\fBSince:\fP
.RS 4
Coin 2\&.1 
.PP
TGS provides HardCopy support as a separate extension for TGS Inventor\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoPSVectorOutput::SoPSVectorOutput ()"
Constructor\&. 
.SS "SoPSVectorOutput::~SoPSVectorOutput ()\fC [virtual]\fP"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SoPSVectorOutput::setColored (SbBool flag = \fCTRUE\fP)"
Sets whether the geometry should be colored\&. 
.SS "SbBool SoPSVectorOutput::getColored (void) const"
Returns whether geometry is colored\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
