.TH "SoRenderManager.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoRenderManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/SbColor4f\&.h>\fP
.br
\fC#include <Inventor/SbVec2s\&.h>\fP
.br
\fC#include <Inventor/actions/SoGLRenderAction\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoRenderManager\fP"
.br
.RI "The \fBSoRenderManager\fP class is used for controlling the rendering of a scene graph\&. "
.ti -1c
.RI "class \fBSoRenderManager::Superimposition\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBSoRenderManagerRenderCB\fP(void *userdata, class \fBSoRenderManager\fP *mgr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
