.TH "SoReadError" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoReadError \- The \fBSoReadError\fP class is used during model import operations\&.
.PP
During model file import, this class will be used to output any error or warning messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/errors/SoReadError\&.h>\fP
.PP
Inherits \fBSoError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetHandlerCallback\fP (SoErrorCB *const function, void *const data)"
.br
.ti -1c
.RI "static SoErrorCB * \fBgetHandlerCallback\fP (void)"
.br
.ti -1c
.RI "static void * \fBgetHandlerData\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBpost\fP (const \fBSoInput\fP *const input, const char *const format,\&.\&.\&.)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual SoErrorCBPtr \fBgetHandler\fP (void *&data) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoReadError\fP class is used during model import operations\&.
.PP
During model file import, this class will be used to output any error or warning messages\&. 

Depending on your application, setting up your own error handler callbacks for \fBSoReadError\fP might be a good idea\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoReadError::getTypeId (void) const\fC [virtual]\fP"
This method returns the \fBSoType\fP of a particular object instance\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId() 
.RE
.PP

.PP
Reimplemented from \fBSoError\fP\&.
.SS "void SoReadError::post (const \fBSoInput\fP *const in, const char *const format,  \&.\&.\&.)\fC [static]\fP"
Method used from import code to post error or warning messages for model files which are not 100% compliant to the format specification\&.
.PP
The messages will be wrapped within information on line number, file offset etc\&. 
.SS "SoErrorCB * SoReadError::getHandler (void *& data) const\fC [protected]\fP, \fC [virtual]\fP"
This is just a convenience wrapper around the getHandlerCallback() and getHandlerData() methods\&. 
.PP
Reimplemented from \fBSoError\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
