.TH "SoScXMLMotionTarget" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoScXMLMotionTarget \- to be used in parallel with other non-moving targets when parallel states are implemented\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/navigation/SoScXMLMotionTarget\&.h>\fP
.PP
Inherits \fBSoScXMLNavigationTarget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanClass\fP (void)"
.br
.ti -1c
.RI "static \fBSoScXMLMotionTarget\fP * \fBconstructSingleton\fP (void)"
.br
.ti -1c
.RI "static void \fBdestructSingleton\fP (void)"
.br
.ti -1c
.RI "static \fBSoScXMLMotionTarget\fP * \fBsingleton\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual SbBool \fBprocessOneEvent\fP (const \fBScXMLEvent\fP *event)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
to be used in parallel with other non-moving targets when parallel states are implemented\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoScXMLMotionTarget::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSoBase::getTypeId() const\fP 
.RE
.PP

.PP
Implements \fBSoScXMLNavigationTarget\fP\&.
.SS "SbBool SoScXMLMotionTarget::processOneEvent (const \fBScXMLEvent\fP * event)\fC [protected]\fP, \fC [virtual]\fP"
This function processes one event\&. The base class implementation does nothing\&. 
.PP
Reimplemented from \fBScXMLEventTarget\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
