.TH "soscxml" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soscxml \- This set of classes implement a coin-specific mode of scxml\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScXMLCoinEvaluator\fP"
.br
.RI "implements the evaluator for the custom profile named 'x-coin'\&. "
.ti -1c
.RI "class \fBSoScXMLEvent\fP"
.br
.RI "Adds an \fBSoEvent\fP holder to the \fBScXMLEvent\fP base\&. "
.ti -1c
.RI "class \fBSoScXMLStateMachine\fP"
.br
.RI "Integration level for using Coin events with SCXML-based state machines\&. "
.in -1c
.SH "Detailed Description"
.PP 
This set of classes implement a coin-specific mode of scxml\&. 


.PP
\fBSee also:\fP
.RS 4
\fBNavigation Classes\fP 
.PP
\fBState Chart XML Classes\fP
.RE
.PP
\fBSince:\fP
.RS 4
Coin 4\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
