.TH "SoSFVec4s" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoSFVec4s \- The \fBSoSFVec4s\fP class is a container for an \fBSbVec4s\fP vector\&.
.PP
This field is used where nodes, engines or other field containers needs to store a single vector with four elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/fields/SoSFVec4s\&.h>\fP
.PP
Inherits \fBSoSField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcopyFrom\fP (const \fBSoField\fP &field)"
.br
.ti -1c
.RI "const \fBSoSFVec4s\fP & \fBoperator=\fP (const \fBSoSFVec4s\fP &field)"
.br
.ti -1c
.RI "virtual SbBool \fBisSame\fP (const \fBSoField\fP &field) const"
.br
.ti -1c
.RI "const \fBSbVec4s\fP & \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbVec4s\fP &newvalue)"
.br
.ti -1c
.RI "const \fBSbVec4s\fP & \fBoperator=\fP (const \fBSbVec4s\fP &newvalue)"
.br
.ti -1c
.RI "\fBint\fP \fBoperator==\fP (const \fBSoSFVec4s\fP &field) const"
.br
.ti -1c
.RI "\fBint\fP \fBoperator!=\fP (const \fBSoSFVec4s\fP &field) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (short x, short y, short z, short w)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const short xyzw[4])"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbVec4s\fP \fBvalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoSFVec4s\fP class is a container for an \fBSbVec4s\fP vector\&.
.PP
This field is used where nodes, engines or other field containers needs to store a single vector with four elements\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSbVec4s\fP, \fBSoMFVec4s\fP Be aware that this class is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&. 
.RE
.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoSFVec4s::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification instance which uniquely identifies the Coin field class the object belongs to\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId(), \fBSoType\fP 
.RE
.PP

.PP
Implements \fBSoField\fP\&.
.SS "void SoSFVec4s::copyFrom (const \fBSoField\fP & f)\fC [virtual]\fP"
Copy value(s) from \fIf\fP into this field\&. \fIf\fP must be of the same type as this field\&. 
.PP
Implements \fBSoField\fP\&.
.SS "SbBool SoSFVec4s::isSame (const \fBSoField\fP & f) const\fC [virtual]\fP"
Check for equal type and value(s)\&. 
.PP
Implements \fBSoField\fP\&.
.SS "void SoSFVec4s::setValue (short x, short y, short z, short w)"
Set value of vector\&. 
.SS "void SoSFVec4s::setValue (const short xyzw[4])"
Set value of vector\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
