.TH "SoSFVec2f" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoSFVec2f \- The \fBSoSFVec2f\fP class is a container for an \fBSbVec2f\fP vector\&.
.PP
This field is used where nodes, engines or other field containers needs to store a single vector with two elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/fields/SoSFVec2f\&.h>\fP
.PP
Inherits \fBSoSField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBcopyFrom\fP (const \fBSoField\fP &field)"
.br
.ti -1c
.RI "const \fBSoSFVec2f\fP & \fBoperator=\fP (const \fBSoSFVec2f\fP &field)"
.br
.ti -1c
.RI "virtual SbBool \fBisSame\fP (const \fBSoField\fP &field) const"
.br
.ti -1c
.RI "const \fBSbVec2f\fP & \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSbVec2f\fP &newvalue)"
.br
.ti -1c
.RI "const \fBSbVec2f\fP & \fBoperator=\fP (const \fBSbVec2f\fP &newvalue)"
.br
.ti -1c
.RI "\fBint\fP \fBoperator==\fP (const \fBSoSFVec2f\fP &field) const"
.br
.ti -1c
.RI "\fBint\fP \fBoperator!=\fP (const \fBSoSFVec2f\fP &field) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const float xy[2])"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSbVec2f\fP \fBvalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoSFVec2f\fP class is a container for an \fBSbVec2f\fP vector\&.
.PP
This field is used where nodes, engines or other field containers needs to store a single vector with two elements\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSoMFVec2f\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoSFVec2f::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification instance which uniquely identifies the Coin field class the object belongs to\&.
.PP
\fBSee also:\fP
.RS 4
getClassTypeId(), \fBSoType\fP 
.RE
.PP

.PP
Implements \fBSoField\fP\&.
.SS "void SoSFVec2f::copyFrom (const \fBSoField\fP & f)\fC [virtual]\fP"
Copy value(s) from \fIf\fP into this field\&. \fIf\fP must be of the same type as this field\&. 
.PP
Implements \fBSoField\fP\&.
.SS "SbBool SoSFVec2f::isSame (const \fBSoField\fP & f) const\fC [virtual]\fP"
Check for equal type and value(s)\&. 
.PP
Implements \fBSoField\fP\&.
.SS "void SoSFVec2f::setValue (float x, float y)"
Set value of vector\&. 
.SS "void SoSFVec2f::setValue (const float xy[2])"
Set value of vector\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
