.TH "SoShapeStyleElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoShapeStyleElement \- The \fBSoShapeStyleElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoShapeStyleElement\&.h>\fP
.PP
Inherits \fBSoElement\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlags\fP { \fBLIGHTING\fP = 0x00000100, \fBTEXENABLED\fP = 0x00000200, \fBTEXFUNC\fP = 0x00000400, \fBBBOXCMPLX\fP = 0x00000800, \fBINVISIBLE\fP = 0x00001000, \fBABORTCB\fP = 0x00002000, \fBOVERRIDE\fP = 0x00004000, \fBTEX3ENABLED\fP = 0x00008000, \fBBIGIMAGE\fP = 0x00010000, \fBBUMPMAP\fP = 0x00020000, \fBVERTEXARRAY\fP = 0x00040000, \fBTRANSP_TEXTURE\fP = 0x00080000, \fBTRANSP_MATERIAL\fP = 0x00100000, \fBTRANSP_SORTED_TRIANGLES\fP = 0x00200000, \fBSHADOWMAP\fP = 0x00400000, \fBSHADOWS\fP = 0x00800000 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "virtual void \fBpush\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "virtual void \fBpop\fP (\fBSoState\fP *state, const \fBSoElement\fP *prevTopElement)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "virtual SbBool \fBmatches\fP (const \fBSoElement\fP *element) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "virtual \fBSoElement\fP * \fBcopyMatchInfo\fP (void) const"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "unsigned \fBint\fP \fBgetFlags\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBmightNotRender\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBneedNormals\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBneedTexCoords\fP (void) const"
.br
.ti -1c
.RI "\fBint\fP \fBgetRenderCaseMask\fP (void) const"
.br
.ti -1c
.RI "SbBool \fBisTextureFunction\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static const \fBSoShapeStyleElement\fP * \fBget\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetDrawStyle\fP (\fBSoState\fP *const state, const int32_t value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetComplexityType\fP (\fBSoState\fP *const state, const int32_t value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetTransparencyType\fP (\fBSoState\fP *const state, const int32_t value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetTextureEnabled\fP (\fBSoState\fP *const state, const SbBool value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetTexture3Enabled\fP (\fBSoState\fP *const state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetTextureFunction\fP (\fBSoState\fP *const state, const SbBool value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetLightModel\fP (\fBSoState\fP *const state, const int32_t value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBsetOverrides\fP (\fBSoState\fP *const state, const SbBool value)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static SbBool \fBisScreenDoor\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static \fBint\fP \fBgetTransparencyType\fP (\fBSoState\fP *const state)"
.br
.ti -1c
.RI "static void \fBsetBumpmapEnabled\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetBigImageEnabled\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetVertexArrayRendering\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetTransparentMaterial\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetTransparentTexture\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetShadowMapRendering\fP (\fBSoState\fP *state, const SbBool value)"
.br
.ti -1c
.RI "static void \fBsetShadowsRendering\fP (\fBSoState\fP *state, const SbBool value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoShapeStyleElement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoShapeStyleElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoShapeStyleElement::~SoShapeStyleElement ()\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoShapeStyleElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoShapeStyleElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoShapeStyleElement\fP class\&. 
.SS "unsigned \fBint\fP SoShapeStyleElement::getFlags (void) const"
Returns the state flags\&. Used internally to optimize rendering\&.
.PP
\\ since Coin 2\&.4 
.SS "SbBool SoShapeStyleElement::mightNotRender (void) const"
FIXME: write doc\&. 
.SS "SbBool SoShapeStyleElement::needNormals (void) const"
FIXME: write doc\&. 
.SS "SbBool SoShapeStyleElement::needTexCoords (void) const"
FIXME: write doc\&. 
.SS "\fBint\fP SoShapeStyleElement::getRenderCaseMask (void) const"
Not implemented in Coin\&. It is used by \fBSoVertexProperty\fP in SGI OIV\&. 
.SS "void SoShapeStyleElement::setTexture3Enabled (\fBSoState\fP *const state, const SbBool value)\fC [static]\fP"
FIXME: write doc\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SS "\fBint\fP SoShapeStyleElement::getTransparencyType (\fBSoState\fP *const state)\fC [static]\fP"
Returns the current transparency type\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SS "SbBool SoShapeStyleElement::isTextureFunction (void) const"
Returns if texture function is currently enabled\&. 
.SS "void SoShapeStyleElement::setBumpmapEnabled (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets bumpmap enabled\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.4 
.RE
.PP

.SS "void SoShapeStyleElement::setBigImageEnabled (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets bigimage enabled\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.4 
.RE
.PP

.SS "void SoShapeStyleElement::setVertexArrayRendering (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets if vertex array rendering might be used\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.4 
.RE
.PP

.SS "void SoShapeStyleElement::setTransparentMaterial (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets material transparency\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.4 
.RE
.PP

.SS "void SoShapeStyleElement::setTransparentTexture (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets texture transparency\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.4 
.RE
.PP

.SS "void SoShapeStyleElement::setShadowMapRendering (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets whether we are rendering to a shadow (depth) map or not\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP

.SS "void SoShapeStyleElement::setShadowsRendering (\fBSoState\fP * state, const SbBool value)\fC [static]\fP"
Sets whether we are rendering with shadows or not\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.5 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
