.TH "SoShaderProgram.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoShaderProgram.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoNode\&.h>\fP
.br
\fC#include <Inventor/nodes/SoSubNode\&.h>\fP
.br
\fC#include <Inventor/fields/SoMFNode\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoShaderProgram\fP"
.br
.RI "The \fBSoShaderProgram\fP class is used to specify a set of vertex/geometry/fragment objects\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBSoShaderProgramEnableCB\fP(void *closure, \fBSoState\fP *state, const SbBool enable)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
