.TH "SoTextureCombineElement::UnitData" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoTextureCombineElement::UnitData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitData\fP (const \fBUnitData\fP &org)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnodeid\fP"
.br
.ti -1c
.RI "Source \fBrgbsource\fP [3]"
.br
.ti -1c
.RI "Source \fBalphasource\fP [3]"
.br
.ti -1c
.RI "Operand \fBrgboperand\fP [3]"
.br
.ti -1c
.RI "Operand \fBalphaoperand\fP [3]"
.br
.ti -1c
.RI "Operation \fBrgboperation\fP"
.br
.ti -1c
.RI "Operation \fBalphaoperation\fP"
.br
.ti -1c
.RI "\fBSbColor4f\fP \fBconstantcolor\fP"
.br
.ti -1c
.RI "float \fBrgbscale\fP"
.br
.ti -1c
.RI "float \fBalphascale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
