.TH "SoTextDetail" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoTextDetail \- The \fBSoTextDetail\fP stores information about a character in a string\&.
.PP
Instances of this class are used for storing information about hit points on textual 2D or 3D geometry after pick operations, and for storing information returned to tessellation callbacks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/details/SoTextDetail\&.h>\fP
.PP
Inherits \fBSoDetail\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "\fBSoTextDetail\fP (void)"
.br
.ti -1c
.RI "virtual \fB~SoTextDetail\fP ()"
.br
.ti -1c
.RI "virtual \fBSoDetail\fP * \fBcopy\fP (void) const"
.br
.ti -1c
.RI "\fBint\fP \fBgetStringIndex\fP (void) const"
.br
.ti -1c
.RI "\fBint\fP \fBgetCharacterIndex\fP (void) const"
.br
.ti -1c
.RI "\fBint\fP \fBgetPart\fP (void) const"
.br
.ti -1c
.RI "void \fBsetStringIndex\fP (const \fBint\fP idx)"
.br
.ti -1c
.RI "void \fBsetCharacterIndex\fP (const \fBint\fP idx)"
.br
.ti -1c
.RI "void \fBsetPart\fP (const \fBint\fP idx)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBcleanupClass\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoTextDetail\fP stores information about a character in a string\&.
.PP
Instances of this class are used for storing information about hit points on textual 2D or 3D geometry after pick operations, and for storing information returned to tessellation callbacks\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSoRayPickAction\fP, \fBSoCallbackAction\fP 
.PP
\fBSoText3\fP, \fBSoText2\fP, \fBSoAsciiText\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoTextDetail::SoTextDetail (void)"
Constructor sets up an 'empty' detail; all indices are set to -1 to indicate this\&. 
.SS "SoTextDetail::~SoTextDetail ()\fC [virtual]\fP"
Destructor\&. This class does not allocate any extra resources, so no actions are taken\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoTextDetail::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification of a detail derived from a class inheriting \fBSoDetail\fP\&. This is used for run-time type checking and 'downward' casting\&.
.PP
Usage example:
.PP
.PP
.nf
void fuhbear(SoDetail * detail)
{
  if (detail->getTypeId() == SoFaceDetail::getClassTypeId()) {
    // safe downward cast, know the type
    SoFaceDetail * facedetail = (SoFaceDetail *)detail;
  }
  return; // ignore if not a SoFaceDetail
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new detail classes: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through Inventor/nodes/SoSubDetail\&.h: SO_DETAIL_SOURCE and SO_DETAIL_INIT_CLASS\&. 
.PP
Implements \fBSoDetail\fP\&.
.SS "\fBSoDetail\fP * SoTextDetail::copy (void) const\fC [virtual]\fP"
Return a deep copy of ourself\&.
.PP
\fBNote that if the Coin library has been built as a DLL under Microsoft Windows and you use this method from application code, you \fImust\fP make sure that both the Coin DLL and the application executable is using the same instance of a C Run-Time (CRT) library\&. Otherwise, you \fIwill\fP get memory heap corruption upon deallocating the returned instances, eventually leading to mysterious crashes\&.\fP 
.PP
Implements \fBSoDetail\fP\&.
.SS "\fBint\fP SoTextDetail::getStringIndex (void) const"
Returns the index of the string where a character was hit / generated, from a set of multiple strings\&.
.PP
\fBSee also:\fP
.RS 4
\fBSoMFString\fP 
.RE
.PP

.SS "\fBint\fP SoTextDetail::getCharacterIndex (void) const"
Returns the index of the character in the string which was hit\&.
.PP
\fBSee also:\fP
.RS 4
\fBgetStringIndex()\fP 
.RE
.PP

.SS "\fBint\fP SoTextDetail::getPart (void) const"
For \fBSoText3\fP, returns the part id of the text geometry\&. The id numbers matches those specified in the \fBSoText3::Part\fP enumeration\&. 
.SS "void SoTextDetail::setStringIndex (const \fBint\fP idx)"
Internal method for 'client' shape nodes to initialize this \fBSoTextDetail\fP instance\&. 
.SS "void SoTextDetail::setCharacterIndex (const \fBint\fP idx)"
Internal method for 'client' shape nodes to initialize this \fBSoTextDetail\fP instance\&. 
.SS "void SoTextDetail::setPart (const \fBint\fP partarg)"
Internal method for 'client' shape nodes to initialize this \fBSoTextDetail\fP instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
