.TH "SoTranSender" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoTranSender
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoTranSender\fP (\fBSoOutput\fP *output)"
.br
.ti -1c
.RI "\fBSoOutput\fP * \fBgetOutput\fP (void) const"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBSoNode\fP *node)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBSoNode\fP *node, \fBSoNode\fP *parent, \fBint\fP n)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBSoNode\fP *parent, \fBint\fP n)"
.br
.ti -1c
.RI "void \fBreplace\fP (\fBSoNode\fP *parent, \fBint\fP n, \fBSoNode\fP *newnode)"
.br
.ti -1c
.RI "void \fBmodify\fP (\fBSoNode\fP *node)"
.br
.ti -1c
.RI "void \fBprepareToSend\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
