.TH "SoTypeList" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoTypeList \- The \fBSoTypeList\fP class is a container class for arrays of \fBSoType\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/lists/SoTypeList\&.h>\fP
.PP
Inherits \fBSbPList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoTypeList\fP (void)"
.br
.ti -1c
.RI "\fBSoTypeList\fP (const \fBint\fP sizehint)"
.br
.ti -1c
.RI "\fBSoTypeList\fP (const \fBSoTypeList\fP &l)"
.br
.ti -1c
.RI "void \fBappend\fP (const \fBSoType\fP type)"
.br
.ti -1c
.RI "\fBint\fP \fBfind\fP (const \fBSoType\fP type) const"
.br
.ti -1c
.RI "void \fBinsert\fP (const \fBSoType\fP type, const \fBint\fP insertbefore)"
.br
.ti -1c
.RI "\fBSoType\fP \fBoperator[]\fP (const \fBint\fP idx) const"
.br
.ti -1c
.RI "void \fBset\fP (const \fBint\fP index, const \fBSoType\fP item)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoTypeList\fP class is a container class for arrays of \fBSoType\fP objects\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSbList\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoTypeList::SoTypeList (void)\fC [inline]\fP"
Default constructor\&. 
.SS "SoTypeList::SoTypeList (const \fBint\fP sizehint)\fC [inline]\fP"
This constructor initializes the internal allocated size for the list to \fIsizehint\fP\&. Note that the list will still initially contain zero items\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbList::SbList(const int sizehint)\fP 
.RE
.PP

.SS "SoTypeList::SoTypeList (const \fBSoTypeList\fP & l)\fC [inline]\fP"
Copy constructor\&.
.PP
\fBSee also:\fP
.RS 4
\fBSbList::SbList(const SbList<Type> & l)\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void SoTypeList::append (const \fBSoType\fP type)"
Overridden from parent to accept an \fBSoType\fP argument\&. 
.SS "\fBint\fP SoTypeList::find (const \fBSoType\fP type) const"
Overridden from parent to accept an \fBSoType\fP argument\&. 
.SS "void SoTypeList::insert (const \fBSoType\fP type, const \fBint\fP insertbefore)"
Overridden from parent to accept an \fBSoType\fP argument\&. 
.SS "\fBSoType\fP SoTypeList::operator[] (const \fBint\fP idx) const"
Overridden from parent to return an \fBSoType\fP instance\&.\&. 
.SS "void SoTypeList::set (const \fBint\fP index, const \fBSoType\fP item)"
This method sets the element at \fIindex\fP to \fIitem\fP\&. Overridden to accept an \fBSoType\fP argument\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
