.TH "SoUnitsElement" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoUnitsElement \- The \fBSoUnitsElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/elements/SoUnitsElement\&.h>\fP
.PP
Inherits \fBSoInt32Element\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBUnits\fP { \fBMETERS\fP = 0, \fBCENTIMETERS\fP, \fBMILLIMETERS\fP, \fBMICROMETERS\fP, \fBMICRONS\fP, \fBNANOMETERS\fP, \fBANGSTROMS\fP, \fBKILOMETERS\fP, \fBFEET\fP, \fBINCHES\fP, \fBPOINTS\fP, \fBYARDS\fP, \fBMILES\fP, \fBNAUTICAL_MILES\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBSoState\fP *state)"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static \fBint\fP \fBgetClassStackIndex\fP (void)"
.br
.ti -1c
.RI "static void * \fBcreateInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, \fBSoNode\fP *const node, const \fBUnits\fP units)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static void \fBset\fP (\fBSoState\fP *const state, const \fBUnits\fP units)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static \fBUnits\fP \fBget\fP (\fBSoState\fP *const state)"
.br
.RI "FIXME: write doc\&. "
.ti -1c
.RI "static \fBUnits\fP \fBgetDefault\fP ()"
.br
.RI "FIXME: write doc\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SoUnitsElement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoUnitsElement\fP class is yet to be documented\&.
.PP
FIXME: write doc\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSoUnitsElement::Units\fP"
FIXME: write doc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoUnitsElement::~SoUnitsElement (void)\fC [protected]\fP, \fC [virtual]\fP"
The destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void * SoUnitsElement::createInstance (void)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoUnitsElement::initClass (void)\fC [static]\fP"
This static method initializes static data for the \fBSoUnitsElement\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
