.TH "SoVectorizePSAction" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoVectorizePSAction \- The \fBSoVectorizePSAction\fP class is used for rendering to a Postscript file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/annex/HardCopy/SoVectorizePSAction\&.h>\fP
.PP
Inherits \fBSoVectorizeAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.ti -1c
.RI "\fBSoVectorizePSAction\fP (void)"
.br
.ti -1c
.RI "virtual \fB~SoVectorizePSAction\fP ()"
.br
.ti -1c
.RI "void \fBsetDefault2DFont\fP (const \fBSbString\fP &fontname)"
.br
.ti -1c
.RI "const \fBSbString\fP & \fBgetDefault2DFont\fP (void) const"
.br
.ti -1c
.RI "void \fBsetGouraudThreshold\fP (const double eps)"
.br
.ti -1c
.RI "\fBSoPSVectorOutput\fP * \fBgetOutput\fP (void) const"
.br
.ti -1c
.RI "\fBSoPSVectorOutput\fP * \fBgetPSOutput\fP (void) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBaddMethod\fP (const \fBSoType\fP type, \fBSoActionMethod\fP method)"
.br
.ti -1c
.RI "static void \fBenableElement\fP (const \fBSoType\fP type, const \fBint\fP stackindex)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBSoEnabledElementsList\fP & \fBgetEnabledElements\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprintHeader\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprintFooter\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprintBackground\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprintItem\fP (const SoVectorizeItem *item) const"
.br
.ti -1c
.RI "virtual void \fBprintViewport\fP (void) const"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoEnabledElementsList\fP * \fBgetClassEnabledElements\fP (void)"
.br
.ti -1c
.RI "static \fBSoActionMethodList\fP * \fBgetClassActionMethods\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoVectorizePSAction\fP class is used for rendering to a Postscript file\&. 


.PP
\fBSince:\fP
.RS 4
Coin 2\&.1 
.PP
TGS provides HardCopy support as a separate extension for TGS Inventor\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoVectorizePSAction::SoVectorizePSAction (void)"
Default constructor\&. 
.SS "SoVectorizePSAction::~SoVectorizePSAction ()\fC [virtual]\fP"
Default destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoVectorizePSAction::getTypeId (void) const\fC [virtual]\fP"
Returns the type identification of an action derived from a class inheriting \fBSoAction\fP\&. This is used for run-time type checking and 'downward' casting\&.
.PP
Usage example:
.PP
.PP
.nf
void bar(SoAction * action)
{
  if (action->getTypeId() == SoGLRenderAction::getClassTypeId()) {
    // safe downward cast, know the type
    SoGLRenderAction * glrender = (SoGLRenderAction *)action;
  }
  return; // ignore if not renderaction
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new actions: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through Inventor/nodes/SoSubAction\&.h: SO_ACTION_SOURCE, SO_ACTION_INIT_CLASS and SO_ACTION_CONSTRUCTOR\&.
.PP
For more information on writing Coin extensions, see the \fBSoAction\fP class documentation\&.
.PP
Returns the actual type id of an object derived from a class inheriting \fBSoAction\fP\&. Needs to be overridden in \fIall\fP subclasses\&. 
.PP
Reimplemented from \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::addMethod (const \fBSoType\fP type, \fBSoActionMethod\fP method)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "void SoVectorizePSAction::enableElement (const \fBSoType\fP type, const \fBint\fP stackindex)\fC [static]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.SS "const \fBSoEnabledElementsList\fP & SoVectorizePSAction::getEnabledElements (void) const\fC [protected]\fP, \fC [virtual]\fP"
Returns a list of the elements used by action instances of this class upon traversal operations\&. 
.PP
Reimplemented from \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::setDefault2DFont (const \fBSbString\fP & fontname)"
Sets the default font name\&. This font will be used for rendering Text2-nodes which have no Font-nodes preceding them\&. The default value is 'Courier'\&. 
.SS "const \fBSbString\fP & SoVectorizePSAction::getDefault2DFont (void) const"
Returns the default font name\&.
.PP
\fBSee also:\fP
.RS 4
\fBsetDefault2DFont()\fP 
.RE
.PP

.SS "void SoVectorizePSAction::setGouraudThreshold (const double eps)"
Sets the Gouraud shading threshold\&. A threshold of 0\&.0 will disable Gouraud shading\&. A smaller value will yield more accurate Gouraud shading\&. Default is 0\&.1\&.
.PP
Since the postscript language has no support for Gouraud shaded triangles, each triangle will be split into subtriangles approximately of size \fIeps\fP postscript units\&. One postscript unit is approximately 1/72 inch\&. 
.SS "\fBSoPSVectorOutput\fP * SoVectorizePSAction::getOutput (void) const"
Returns the \fBSoPSVectorOutput\fP used by this instance\&. 
.SS "\fBSoPSVectorOutput\fP * SoVectorizePSAction::getPSOutput (void) const"
Returns the \fBSoPSVectorOutput\fP used by this instance\&. Provided for API compatibility with TGS HardCopy support\&. 
.SS "void SoVectorizePSAction::printHeader (void) const\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.PP
Implements \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::printFooter (void) const\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Should be overridden by subclasses to print file footer data\&. 
.PP
Reimplemented from \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::printBackground (void) const\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Should be overridden by subclasses to print background data\&. 
.PP
Reimplemented from \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::printItem (const SoVectorizeItem * item) const\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Should be overridden by subclasses to print an item\&. 
.PP
Implements \fBSoVectorizeAction\fP\&.
.SS "void SoVectorizePSAction::printViewport (void) const\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Should be overridden by subclasses to set up the current page viewport\&. 
.PP
Reimplemented from \fBSoVectorizeAction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
