.TH "SoVRMLVertexShape" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoVRMLVertexShape \- The \fBSoVRMLVertexShape\fP class is a superclass for vertex based shapes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/VRMLnodes/SoVRMLVertexShape\&.h>\fP
.PP
Inherits \fBSoVRMLGeometry\fP\&.
.PP
Inherited by \fBSoVRMLIndexedShape\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBinding\fP { \fBOVERALL\fP = SoMaterialBindingElement::OVERALL, \fBPER_PART\fP = SoMaterialBindingElement::PER_PART, \fBPER_PART_INDEXED\fP = SoMaterialBindingElement::PER_PART_INDEXED, \fBPER_FACE\fP = SoMaterialBindingElement::PER_FACE, \fBPER_FACE_INDEXED\fP = SoMaterialBindingElement::PER_FACE_INDEXED, \fBPER_VERTEX\fP = SoMaterialBindingElement::PER_VERTEX, \fBPER_VERTEX_INDEXED\fP = SoMaterialBindingElement::PER_VERTEX_INDEXED }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "virtual SbBool \fBgenerateDefaultNormals\fP (\fBSoState\fP *s, \fBSoNormalBundle\fP *nb)"
.br
.ti -1c
.RI "virtual SbBool \fBgenerateDefaultNormals\fP (\fBSoState\fP *s, \fBSoNormalCache\fP *nc)"
.br
.ti -1c
.RI "virtual void \fBdoAction\fP (\fBSoAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBGLRender\fP (\fBSoGLRenderAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBgetBoundingBox\fP (\fBSoGetBoundingBoxAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBcallback\fP (\fBSoCallbackAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBpick\fP (\fBSoPickAction\fP *action)"
.br
.ti -1c
.RI "virtual void \fBnotify\fP (\fBSoNotList\fP *list)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoSFNode\fP \fBcoord\fP"
.br
.ti -1c
.RI "\fBSoSFNode\fP \fBtexCoord\fP"
.br
.ti -1c
.RI "\fBSoSFNode\fP \fBnormal\fP"
.br
.ti -1c
.RI "\fBSoSFNode\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBSoSFBool\fP \fBcolorPerVertex\fP"
.br
.ti -1c
.RI "\fBSoSFBool\fP \fBnormalPerVertex\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBSoFieldData\fP * \fBgetFieldData\fP (void) const"
.br
.ti -1c
.RI "\fBSoVRMLVertexShape\fP (void)"
.br
.ti -1c
.RI "virtual \fB~SoVRMLVertexShape\fP ()"
.br
.ti -1c
.RI "virtual SbBool \fBshouldGLRender\fP (\fBSoGLRenderAction\fP *action)"
.br
.ti -1c
.RI "void \fBsetNormalCache\fP (\fBSoState\fP *s, \fBint\fP numNormals, \fBSbVec3f\fP *normals)"
.br
.ti -1c
.RI "\fBSoNormalCache\fP * \fBgetNormalCache\fP (void) const"
.br
.ti -1c
.RI "\fBSoNormalCache\fP * \fBgenerateAndReadLockNormalCache\fP (\fBSoState\fP *const state)"
.br
.ti -1c
.RI "void \fBgetVertexData\fP (\fBSoState\fP *state, const \fBSoCoordinateElement\fP *&coords, const \fBSbVec3f\fP *&normals, const SbBool neednormals)"
.br
.ti -1c
.RI "void \fBreadLockNormalCache\fP (void)"
.br
.ti -1c
.RI "void \fBreadUnlockNormalCache\fP (void)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static const \fBSoFieldData\fP ** \fBgetFieldDataPtr\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoVRMLVertexShape\fP class is a superclass for vertex based shapes\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoVRMLVertexShape::SoVRMLVertexShape (void)\fC [protected]\fP"
Constructor\&. 
.SS "SoVRMLVertexShape::~SoVRMLVertexShape ()\fC [protected]\fP, \fC [virtual]\fP"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoVRMLVertexShape::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. Usage example:
.PP
.PP
.nf
void foo(SoNode * node)
{
  if (node->getTypeId() == SoFile::getClassTypeId()) {
    SoFile * filenode = (SoFile *)node;  // safe downward cast, knows the type
  }
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new nodes, engines, nodekits, draggers or others: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through for instance \fBInventor/nodes/SoSubNode\&.h\fP (SO_NODE_INIT_CLASS and SO_NODE_CONSTRUCTOR for node classes), \fBInventor/engines/SoSubEngine\&.h\fP (for engine classes) and so on\&.
.PP
For more information on writing Coin extensions, see the class documentation of the toplevel superclasses for the various class groups\&. 
.PP
Reimplemented from \fBSoVRMLGeometry\fP\&.
.PP
Reimplemented in \fBSoVRMLIndexedFaceSet\fP, and \fBSoVRMLIndexedShape\fP\&.
.SS "const \fBSoFieldData\fP * SoVRMLVertexShape::getFieldData (void) const\fC [protected]\fP, \fC [virtual]\fP"
Returns a pointer to the class-wide field data storage object for this instance\&. If no fields are present, returns \fCNULL\fP\&. 
.PP
Reimplemented from \fBSoVRMLGeometry\fP\&.
.PP
Reimplemented in \fBSoVRMLIndexedFaceSet\fP, and \fBSoVRMLIndexedShape\fP\&.
.SS "SbBool SoVRMLVertexShape::generateDefaultNormals (\fBSoState\fP * s, \fBSoNormalBundle\fP * nb)\fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Subclasses should override this method to generate default normals using the \fBSoNormalBundle\fP class\&. \fCTRUE\fP should be returned if normals were generated, \fCFALSE\fP otherwise\&.
.PP
Default method returns \fCFALSE\fP\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&. 
.PP
Reimplemented in \fBSoVRMLIndexedFaceSet\fP\&.
.SS "SbBool SoVRMLVertexShape::generateDefaultNormals (\fBSoState\fP * s, \fBSoNormalCache\fP * nc)\fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP
.PP
Subclasses should override this method to generate default normals using the \fBSoNormalCache\fP class\&. This is more effective than using \fBSoNormalGenerator\fP\&. Return \fCTRUE\fP if normals were generated, \fCFALSE\fP otherwise\&.
.PP
Default method just returns \fCFALSE\fP\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&. 
.PP
Reimplemented in \fBSoVRMLIndexedFaceSet\fP\&.
.SS "void SoVRMLVertexShape::doAction (\fBSoAction\fP * action)\fC [virtual]\fP"
This function performs the typical operation of a node for any action\&. 
.PP
Reimplemented from \fBSoNode\fP\&.
.SS "void SoVRMLVertexShape::GLRender (\fBSoGLRenderAction\fP * action)\fC [virtual]\fP"
Action method for the \fBSoGLRenderAction\fP\&.
.PP
This is called during rendering traversals\&. Nodes influencing the rendering state in any way or who wants to throw geometry primitives at OpenGL overrides this method\&. 
.PP
Reimplemented from \fBSoShape\fP\&.
.PP
Reimplemented in \fBSoVRMLIndexedFaceSet\fP\&.
.SS "void SoVRMLVertexShape::getBoundingBox (\fBSoGetBoundingBoxAction\fP * action)\fC [virtual]\fP"
Action method for the \fBSoGetBoundingBoxAction\fP\&.
.PP
Calculates bounding box and center coordinates for node and modifies the values of the \fIaction\fP to encompass the bounding box for this node and to shift the center point for the scene more towards the one for this node\&.
.PP
Nodes influencing how geometry nodes calculates their bounding box also overrides this method to change the relevant state variables\&. 
.PP
Reimplemented from \fBSoShape\fP\&.
.SS "void SoVRMLVertexShape::callback (\fBSoCallbackAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoCallbackAction\fP\&.
.PP
Simply updates the state according to how the node behaves for the render action, so the application programmer can use the \fBSoCallbackAction\fP for extracting information about the scene graph\&. 
.PP
Reimplemented from \fBSoShape\fP\&.
.SS "void SoVRMLVertexShape::pick (\fBSoPickAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoPickAction\fP\&.
.PP
Does common processing for \fBSoPickAction\fP \fIaction\fP instances\&. 
.PP
Reimplemented from \fBSoNode\fP\&.
.SS "void SoVRMLVertexShape::notify (\fBSoNotList\fP * l)\fC [virtual]\fP"
Notifies all auditors for this instance when changes are made\&. 
.PP
Reimplemented from \fBSoVRMLGeometry\fP\&.
.PP
Reimplemented in \fBSoVRMLIndexedShape\fP\&.
.SS "SbBool SoVRMLVertexShape::shouldGLRender (\fBSoGLRenderAction\fP * action)\fC [protected]\fP, \fC [virtual]\fP"
\fIThis API member is considered internal to the library, as it is not likely to be of interest to the application programmer\&.\fP 
.PP
Reimplemented from \fBSoVRMLGeometry\fP\&.
.SS "\fBSoNormalCache\fP * SoVRMLVertexShape::generateAndReadLockNormalCache (\fBSoState\fP *const state)\fC [protected]\fP"
Convenience method that can be used by subclasses to return or create a normal cache\&. If the current cache is not valid, it takes care of unrefing the old cache and pushing and popping the state to create element dependencies when creating the new cache\&.
.PP
When returning from this method, the normal cache will be read locked, and the caller should call \fBreadUnlockNormalCache()\fP when the normals in the cache is no longer needed\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SS "void SoVRMLVertexShape::getVertexData (\fBSoState\fP * state, const \fBSoCoordinateElement\fP *& coords, const \fBSbVec3f\fP *& normals, const SbBool neednormals)\fC [protected]\fP"
Convenience method that returns the current coordinate and normal element\&. This method is not part of the OIV API\&. 
.SS "void SoVRMLVertexShape::readLockNormalCache (void)\fC [protected]\fP"
Read lock the normal cache\&. This method should be called before fetching the normal cache (using getNormalCache())\&. When the cached normals are no longer needed, \fBreadUnlockNormalCache()\fP must be called\&.
.PP
It is also possible to use \fBgenerateAndReadLockNormalCache()\fP\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSee also:\fP
.RS 4
\fBreadUnlockNormalCache()\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SS "void SoVRMLVertexShape::readUnlockNormalCache (void)\fC [protected]\fP"
Read unlock the normal cache\&. Should be called when the read-locked cached normals are no longer needed\&.
.PP
This function is an extension for Coin, and it is not available in the original SGI Open Inventor v2\&.1 API\&.
.PP
\fBSee also:\fP
.RS 4
\fBreadLockNormalCache()\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Coin 2\&.0 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBSoSFNode\fP SoVRMLVertexShape::coord"
Should contain an \fBSoVRMLCoordinate\fP node\&. 
.SS "\fBSoSFNode\fP SoVRMLVertexShape::texCoord"
Can contain an \fBSoVRMLTextureCoordinate\fP node\&. 
.SS "\fBSoSFNode\fP SoVRMLVertexShape::normal"
Can contain an \fBSoVRMLNormal\fP node\&. 
.SS "\fBSoSFNode\fP SoVRMLVertexShape::color"
Can contain an \fBSoVRMLColor\fP node\&. 
.SS "\fBSoSFBool\fP SoVRMLVertexShape::colorPerVertex"
When TRUE, colors are applied per vertex\&. Default value is TRUE\&. 
.SS "\fBSoSFBool\fP SoVRMLVertexShape::normalPerVertex"
When TRUE, normals are applied per vertex\&. Default value is TRUE\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
