.TH "SoVRMLSound" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoVRMLSound \- The \fBSoVRMLSound\fP class is used to represent a sound source\&.
.PP
\fBThe detailed class documentation is taken verbatim from the VRML97 standard (ISO/IEC 14772-1:1997)\&. It is copyright The Web3D Consortium, and is used by permission of the Consortium:\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inventor/VRMLnodes/SoVRMLSound\&.h>\fP
.PP
Inherits \fBSoNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSoType\fP \fBgetTypeId\fP (void) const"
.br
.RI "Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. "
.ti -1c
.RI "\fBSoVRMLSound\fP (void)"
.br
.ti -1c
.RI "void \fBsetDopplerVelocity\fP (float velocity)"
.br
.ti -1c
.RI "float \fBgetDopplerVelocity\fP (void) const"
.br
.ti -1c
.RI "void \fBsetDopplerFactor\fP (float factor)"
.br
.ti -1c
.RI "float \fBgetDopplerFactor\fP (void) const"
.br
.ti -1c
.RI "void \fBstartPlaying\fP (\fBSoPath\fP *path, void *userdataptr)"
.br
.ti -1c
.RI "void \fBstopPlaying\fP (\fBSoPath\fP *path, void *userdataptr)"
.br
.ti -1c
.RI "void \fBsetBufferingProperties\fP (\fBint\fP bufferLength, \fBint\fP numBuffers, \fBSbTime\fP sleepTime)"
.br
.ti -1c
.RI "void \fBgetBufferingProperties\fP (\fBint\fP &bufferLength, \fBint\fP &numBuffers, \fBSbTime\fP &sleepTime)"
.br
.ti -1c
.RI "virtual void \fBaudioRender\fP (\fBSoAudioRenderAction\fP *action)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSoType\fP \fBgetClassTypeId\fP (void)"
.br
.ti -1c
.RI "static void \fBinitClass\fP (void)"
.br
.ti -1c
.RI "static void \fBsetDefaultBufferingProperties\fP (\fBint\fP bufferLength, \fBint\fP numBuffers, \fBSbTime\fP sleepTime)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoSFNode\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBintensity\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBpriority\fP"
.br
.ti -1c
.RI "\fBSoSFVec3f\fP \fBlocation\fP"
.br
.ti -1c
.RI "\fBSoSFVec3f\fP \fBdirection\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBminFront\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBmaxFront\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBminBack\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBmaxBack\fP"
.br
.ti -1c
.RI "\fBSoSFBool\fP \fBspatialize\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBdopplerFactor\fP"
.br
.ti -1c
.RI "\fBSoSFFloat\fP \fBdopplerVelocity\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBSoFieldData\fP * \fBgetFieldData\fP (void) const"
.br
.ti -1c
.RI "virtual \fB~SoVRMLSound\fP (void)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static const \fBSoFieldData\fP ** \fBgetFieldDataPtr\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBSoVRMLSound\fP class is used to represent a sound source\&.
.PP
\fBThe detailed class documentation is taken verbatim from the VRML97 standard (ISO/IEC 14772-1:1997)\&. It is copyright The Web3D Consortium, and is used by permission of the Consortium:\fP 


.PP
.nf
Sound {
  exposedField SFVec3f  direction     0 0 1   # (-inf, inf)
  exposedField SFFloat  intensity     1       # [0,1]
  exposedField SFVec3f  location      0 0 0   # (-inf, inf)
  exposedField SFFloat  maxBack       10      # [0,inf)
  exposedField SFFloat  maxFront      10      # [0,inf)
  exposedField SFFloat  minBack       1       # [0,inf)
  exposedField SFFloat  minFront      1       # [0,inf)
  exposedField SFFloat  priority      0       # [0,1]
  exposedField SFNode   source        NULL
  field        SFBool   spatialize    TRUE
}

.fi
.PP
.PP
The Sound node specifies the spatial presentation of a sound in a VRML scene\&. The sound is located at a point in the local coordinate system and emits sound in an elliptical pattern (defined by two ellipsoids)\&. The ellipsoids are oriented in a direction specified by the direction field\&. The shape of the ellipsoids may be modified to provide more or less directional focus from the location of the sound\&.
.PP
The source field specifies the sound source for the Sound node\&. If the source field is not specified, the Sound node will not emit audio\&. The source field shall specify either an AudioClip node or a MovieTexture node\&. If a MovieTexture node is specified as the sound source, the MovieTexture shall refer to a movie format that supports sound (e\&.g\&., MPEG1-Systems)\&.
.PP
The intensity field adjusts the loudness (decibels) of the sound emitted by the Sound node (note: this is different from the traditional definition of intensity with respect to sound)\&.
.PP
The intensity field has a value that ranges from 0\&.0 to 1\&.0 and specifies a factor which shall be used to scale the normalized sample data of the sound source during playback\&. A Sound node with an intensity of 1\&.0 shall emit audio at its maximum loudness (before attenuation), and a Sound node with an intensity of 0\&.0 shall emit no audio\&. Between these values, the loudness should increase linearly from a -20 dB change approaching an intensity of 0\&.0 to a 0 dB change at an intensity of 1\&.0\&.
.PP
The priority field provides a hint for the browser to choose which sounds to play when there are more active Sound nodes than can be played at once due to either limited system resources or system load\&. 7\&.3\&.4, Sound priority, attenuation, and spatialization (http://www.web3d.org/x3d/specifications/vrml/ISO-IEC-14772-VRML97/part1/concepts.html#7.3.4), describes a recommended algorithm for determining which sounds to play under such circumstances\&. The priority field ranges from 0\&.0 to 1\&.0, with 1\&.0 being the highest priority and 0\&.0 the lowest priority\&.
.PP
The location field determines the location of the sound emitter in the local coordinate system\&. A Sound node's output is audible only if it is part of the traversed scene\&. Sound nodes that are descended from LOD, Switch, or any grouping or prototype node that disables traversal (i\&.e\&., drawing) of its children are not audible unless they are traversed\&. If a Sound node is disabled by a Switch or LOD node, and later it becomes part of the traversal again, the sound shall resume where it would have been had it been playing continuously\&.
.PP
The Sound node has an inner ellipsoid that defines a volume of space in which the maximum level of the sound is audible\&. Within this ellipsoid, the normalized sample data is scaled by the intensity field and there is no attenuation\&. The inner ellipsoid is defined by extending the direction vector through the location\&.
.PP
The minBack and minFront fields specify distances behind and in front of the location along the direction vector respectively\&. The inner ellipsoid has one of its foci at location (the second focus is implicit) and intersects the direction vector at minBack and minFront\&. The Sound node has an outer ellipsoid that defines a volume of space that bounds the audibility of the sound\&. No sound can be heard outside of this outer ellipsoid\&.
.PP
The outer ellipsoid is defined by extending the direction vector through the location\&. The maxBack and maxFront fields specify distances behind and in front of the location along the direction vector respectively\&. The outer ellipsoid has one of its foci at location (the second focus is implicit) and intersects the direction vector at maxBack and maxFront\&. The minFront, maxFront, minBack, and maxBack fields are defined in local coordinates, and shall be greater than or equal to zero\&. The minBack field shall be less than or equal to maxBack, and minFront shall be less than or equal to maxFront\&. The ellipsoid parameters are specified in the local coordinate system but the ellipsoids' geometry is affected by ancestors' transformations\&.
.PP
Between the two ellipsoids, there shall be a linear attenuation ramp in loudness, from 0 dB at the minimum ellipsoid to -20 dB at the maximum ellipsoid: attenuation = -20 × (d' / d") where d' is the distance along the location-to-viewer vector, measured from the transformed minimum ellipsoid boundary to the viewer, and d" is the distance along the location-to-viewer vector from the transformed minimum ellipsoid boundary to the transformed maximum ellipsoid boundary (see Figure 6\&.14)\&.
.PP
  Figure 6\&.14 -- Sound node geometry 
.PP
The spatialize field specifies if the sound is perceived as being directionally located relative to the viewer\&. If the spatialize field is TRUE and the viewer is located between the transformed inner and outer ellipsoids, the viewer's direction and the relative location of the Sound node should be taken into account during playback\&. Details outlining the minimum required spatialization functionality can be found in 7\&.3\&.4, Sound priority, attenuation, and spatialization (http://www.web3d.org/x3d/specifications/vrml/ISO-IEC-14772-VRML97/part1/concepts.html#7.3.4), If the spatialize field is FALSE, then directional effects are ignored, but the ellipsoid dimensions and intensity will still affect the loudness of the sound\&. If the sound source is multi-channel (e\&.g\&., stereo), then the source should retain its channel separation during playback\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SoVRMLSound::SoVRMLSound (void)"
Constructor\&. 
.SS "SoVRMLSound::~SoVRMLSound (void)\fC [protected]\fP, \fC [virtual]\fP"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSoType\fP SoVRMLSound::getTypeId (void) const\fC [virtual]\fP"

.PP
Returns the type identification of an object derived from a class inheriting \fBSoBase\fP\&. This is used for run-time type checking and 'downward' casting\&. Usage example:
.PP
.PP
.nf
void foo(SoNode * node)
{
  if (node->getTypeId() == SoFile::getClassTypeId()) {
    SoFile * filenode = (SoFile *)node;  // safe downward cast, knows the type
  }
}
.fi
.PP
.PP
For application programmers wanting to extend the library with new nodes, engines, nodekits, draggers or others: this method needs to be overridden in \fIall\fP subclasses\&. This is typically done as part of setting up the full type system for extension classes, which is usually accomplished by using the pre-defined macros available through for instance \fBInventor/nodes/SoSubNode\&.h\fP (SO_NODE_INIT_CLASS and SO_NODE_CONSTRUCTOR for node classes), \fBInventor/engines/SoSubEngine\&.h\fP (for engine classes) and so on\&.
.PP
For more information on writing Coin extensions, see the class documentation of the toplevel superclasses for the various class groups\&. 
.PP
Implements \fBSoBase\fP\&.
.SS "const \fBSoFieldData\fP * SoVRMLSound::getFieldData (void) const\fC [protected]\fP, \fC [virtual]\fP"
Returns a pointer to the class-wide field data storage object for this instance\&. If no fields are present, returns \fCNULL\fP\&. 
.PP
Reimplemented from \fBSoFieldContainer\fP\&.
.SS "void SoVRMLSound::setDopplerVelocity (float velocity)"
Sets the doppler velocity relative to the global coordinate system\&. Not implemented yet\&. 
.SS "float SoVRMLSound::getDopplerVelocity (void) const"
Returns the doppler velocity relative to the global coordinate system\&. Not implemented yet\&. 
.SS "void SoVRMLSound::setDopplerFactor (float factor)"
Sets the doppler factor\&. Not implemented yet\&. 
.SS "float SoVRMLSound::getDopplerFactor (void) const"
Returns the doppler factor\&. Not implemented yet\&. 
.SS "void SoVRMLSound::startPlaying (\fBSoPath\fP * path, void * userdataptr)"
Starts playing the sound\&. Not implemented yet\&. Please use the fields of \fBSoVRMLAudioClip\fP to start and stop sounds\&. 
.SS "void SoVRMLSound::stopPlaying (\fBSoPath\fP * path, void * userdataptr)"
Stops playing the sound\&. Not implemented yet\&. Please use the fields of \fBSoVRMLAudioClip\fP to start and stop sounds\&. 
.SS "void SoVRMLSound::audioRender (\fBSoAudioRenderAction\fP * action)\fC [virtual]\fP"
Action method for \fBSoAudioRenderAction\fP\&.
.PP
Does common processing for \fBSoAudioRenderAction\fP \fIaction\fP instances\&. 
.PP
Reimplemented from \fBSoNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSoSFNode\fP SoVRMLSound::source"
The audio stream\&. Either an \fBSoVRMLAudioClip\fP or an \fBSoVRMLMovieTexture\fP\&. Coin only supports playback of audio from \fBSoVRMLAudioClip\fP, not from \fBSoVRMLMovieTexture\fP\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::intensity"
Sound intensity\&. A value from 0 to 1\&. Default value is 1\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::priority"
Browser hint for how important the sound is\&. A value from 0 to
.IP "1." 4
Default value is 0\&. Coin does not yet support this field\&. 
.PP

.SS "\fBSoSFVec3f\fP SoVRMLSound::location"
The sound position\&. Default value is (0, 0, 0)\&. 
.SS "\fBSoSFVec3f\fP SoVRMLSound::direction"
Sound direction\&. Default value is (0, 0, 1)\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::minFront"
Inner ellipse front value\&. Default value is 1\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::maxFront"
Outer ellipse front value\&. Default value is 10\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::minBack"
Inner ellipse back value\&. Default value is 1\&. 
.SS "\fBSoSFFloat\fP SoVRMLSound::maxBack"
Outer ellips back value\&. Default value is 10\&. 
.SS "\fBSoSFBool\fP SoVRMLSound::spatialize"
Set to TRUE if sound should be spatialized (directional effects are applied) with respect to the viewer\&. Distance attenuation is always applied\&. Default value is TRUE\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
