.TH "SoVRMLImageTexture.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoVRMLImageTexture.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoSubNode\&.h>\fP
.br
\fC#include <Inventor/VRMLnodes/SoVRMLTexture\&.h>\fP
.br
\fC#include <Inventor/fields/SoMFString\&.h>\fP
.br
\fC#include <Inventor/SbImage\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoVRMLImageTexture\fP"
.br
.RI "The \fBSoVRMLImageTexture\fP class is used for mapping a texture file onto geometry\&.
.PP
\fBThe detailed class documentation is taken verbatim from the VRML97 standard (ISO/IEC 14772-1:1997)\&. It is copyright The Web3D Consortium, and is used by permission of the Consortium:\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef SbBool \fBVRMLPrequalifyFileCallback\fP(const \fBSbString\fP &, void *, \fBSoVRMLImageTexture\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSoMFString\fP SoVRMLImageTexture::url The texture file URL\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
