.TH "SoWWWAnchor.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoWWWAnchor.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/nodes/SoSubNode\&.h>\fP
.br
\fC#include <Inventor/nodes/SoLocateHighlight\&.h>\fP
.br
\fC#include <Inventor/fields/SoSFString\&.h>\fP
.br
\fC#include <Inventor/fields/SoSFEnum\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoWWWAnchor\fP"
.br
.RI "The \fBSoWWWAnchor\fP class adds URL callbacks to the highlighted geometry\&.
.PP
In addition to highlighting geometry under the cursor, the application programmer can set callbacks\&. It is possible to set one callback for picking, the fetch callback, and one callback for highlighting\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBSoWWWAnchorCB\fP(const \fBSbString\fP &url, void *data, \fBSoWWWAnchor\fP *node)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
