.TH "storage.h" 3 "Sun May 28 2017" "Version 4.0.0a" "Coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
storage.h
.SH SYNOPSIS
.br
.PP
\fC#include <Inventor/C/basic\&.h>\fP
.br
\fC#include <Inventor/C/threads/common\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBcc_storage_f\fP(void *closure)"
.br
.ti -1c
.RI "typedef void \fBcc_storage_apply_func\fP(void *dataptr, void *closure)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcc_storage\fP * \fBcc_storage_construct\fP (unsigned \fBint\fP size)"
.br
.ti -1c
.RI "\fBcc_storage\fP * \fBcc_storage_construct_etc\fP (unsigned \fBint\fP size, cc_storage_f *constructor, cc_storage_f *destructor)"
.br
.ti -1c
.RI "void \fBcc_storage_destruct\fP (\fBcc_storage\fP *storage)"
.br
.ti -1c
.RI "void * \fBcc_storage_get\fP (\fBcc_storage\fP *storage)"
.br
.ti -1c
.RI "void \fBcc_storage_apply_to_all\fP (\fBcc_storage\fP *storage, cc_storage_apply_func *func, void *closure)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Coin from the source code\&.
