/* This file is autogenerated, do not edit*/
#include "moc_QuarterWidget.cpp"
#include "moc_DragDropHandler.cpp"
#include "moc_EventFilter.cpp"
#include "moc_FocusHandler.cpp"
#include "moc_ContextMenu.cpp"
#include "moc_InteractionMode.cpp"
#include "moc_SensorManager.cpp"
#include "moc_SignalThread.cpp"
